var DOCID='40E7AE0D-B568-476B-9630-D3AB62280DBE'; doc=sketch.getDocuments().find(function(d){return String(d.id)===DOCID;}); H.doc=doc;
var IDS=['projects','projects--empty','project','recent','artifacts','artifacts--empty','artifacts--detail','routines','routines--new','customize','customize--profile'];
function C(r){return H.sw(APP,r);} function F(p,n,w,h,dir,gap,pad,fill){var f=H.frame({parent:p,name:n,w:w,h:h,dir:dir||'col',gap:gap||0,pad:pad||0,fill:fill});f.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;return f;}
function R(p,n,w,h,gap){var r=F(p,n,w,h,'row',gap||8);r.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;return r;}
function T(p,t,size,role,w,bold){return H.text({parent:p,text:t,size:size||14,weight:bold?6:5,color:C(role||'ink'),w:w});}
function sp(p,v){var f=F(p,'spacer',1,1);f[v?'verticalSizing':'horizontalSizing']=sketch.FlexSizing.Fill;return f;}
function icon(p,g){return H.sfg(p,g,{color:C('tertiary'),size:16});}
function btn(p,t,id,primary){var b=H.frame({parent:p,name:'link:'+id,dir:'row',pad:{top:0,right:14,bottom:0,left:14},h:28,radius:999,fill:primary?C('ink'):null});H.sft({parent:b,text:t,size:13,weight:6,color:C(primary?'surface':'secondary')});H.order(b);return b;}
function seg(p,labels,id){var r=R(p,'segments',null,32,4);labels.forEach(function(t,i){var b=btn(r,t,id,false);if(!i)b.style.fills=[{color:C('hover'),fillType:sketch.Style.FillType.Color}];});H.order(r);}
function group(p,label,w){var f=F(p,label,w,null,'col',8);H.caps(f,APP,label);return f;}
function row(p,title,meta,glyph,w,link,trail){return H.quietRow(p,APP,{title:title,meta:meta,glyph:glyph,w:w,tw:w-180,link:link,trail:trail});}
function field(p,label,value,w,multi,select){var r=R(p,'field:'+label,w,multi?80:40,16);r.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;T(r,label,13,'secondary',112);var c=F(r,'control:'+label,w-128,null,'row',8);T(c,value,14,'ink',w-164);if(select)icon(c,'chevron_down');H.order(c);H.order(r);}
function togg(p,title,meta,on,w){var r=R(p,'link:customize--profile',w,48,16);var t=F(r,'label',w-176,null,'col',2);T(t,title,13);if(meta)T(t,meta,12,'tertiary');H.order(t);sp(r);seg(r,on?['On','Off']:['Off','On'],'customize--profile');H.order(r);}
function resolve(){var p=doc.pages.find(function(p){return p.name==='Proto macOS '+APP.split('/')[0];});if(!p)throw Error('Missing page');var s=p.layers.find(function(l){return l.name==='Screen/macos/'+APP+'/'+ID;});if(!s)throw Error('Missing screen');return s;}
function shell(){var pn='Proto macOS '+APP.split('/')[0];if(!doc.pages.find(function(p){return p.name===pn;}))throw Error('Missing page');var p=H.page(pn);p.layers.slice().forEach(function(l){if(l.name==='Screen/macos/'+APP+'/'+ID||(l.name.indexOf('caption/')===0&&l.name.split('/').pop()===ID))l.remove();});var s=H.screen({page:pn,platform:'macos',app:APP,id:ID,w:1440,h:900,x:IDS.indexOf(ID)*1560,y:1060});var b=ID.split('--')[0];var tools=b==='projects'?[['link:project','plus','New project',true]]:b==='routines'?[['link:routines--new','plus','New routine',true]]:b==='recent'?[['link:new-conversation','square_pencil','New conversation',true]]:[];if(ID.indexOf('--empty')>=0)tools=[];var w=H.macWindow(s,APP,{active:b,title:b==='project'?'Personal':ID==='customize--profile'?'General':b.charAt(0).toUpperCase()+b.slice(1),tools:tools,inspector:b==='project'?'Project':false,gap:24});w.main.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;w.finish();s.frame.x=IDS.indexOf(ID)*1560;s.frame.y=1060;return s;}
function body(s){var col=s.layers.find(function(l){return l.name==='content-col';}),m=col.layers.find(function(l){return l.name==='main';}),b=ID.split('--')[0],w=b==='project'?800:1120;
if(ID.indexOf('--empty')>=0){var e=F(m,'empty',w,680,'col',16);e.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;e.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;H.sfg(e,'sparkles',{size:22,color:C('attention-mark')});T(e,b==='projects'?'A place for every part of your work.':'No artifacts are published yet',14,'secondary');btn(e,b==='projects'?'Create a project':'Start a conversation',b==='projects'?'project':'new-conversation',true);H.order(e);}
else if(b==='projects'){T(m,'Keep conversations, files and memory together.',14,'secondary');var g=group(m,'Pinned',w);row(g,'Personal','12 conversations · 3 running','folder',w,'project','13 min ago');row(g,'Weave Cloud','48 conversations · 2 running','folder',w,'project','2 min ago');H.order(g);g=group(m,'All',w);row(g,'Aheli ops','26 conversations · 1 running','folder',w,'project','2 hours ago');H.order(g);g=group(m,'Latest across projects',w);conversations.slice(0,6).forEach(function(d){row(g,d[0],d[1]+' · '+d[3]+' tokens','bubble',w,'conversation',d[2]);});H.order(g);}
else if(b==='project'){T(m,'Notes, plans and things worth remembering.',14,'secondary');seg(m,['Conversations','Work'],'activity--work');var g=group(m,'Recent conversations',w);[conversations[1],conversations[4],conversations[7],conversations[9]].forEach(function(d){row(g,d[0],'General · '+d[3]+' tokens','bubble',w,'conversation',d[2]);});H.order(g);g=group(m,'Work',w);[['Q3 update ready for review','18 KB · Markdown'],['Research memory strategies','Running · 2 min'],['September milestones published','9 KB · Markdown']].forEach(function(d,i){H.quietRow(g,APP,{title:d[0],meta:d[1],dot:H.hex(APP,i===1?'accent':'tertiary'),w:w,tw:620,link:'activity--work'});});H.order(g);sp(m,true);H.composer(m,APP,{w:800,model:false,placeholder:'Start a conversation in Personal'});var ins=s.layers.find(function(l){return l.name==='inspector';}),ib=H.inspBody(ins,APP);[['Instructions','Keep answers direct. Cite research sources. Ask before sending anything externally.'],['Memory','Use Singapore time and SGD. Keep personal and company work separate.'],['Sources','Q3 investor notes.md\nSeptember milestones.md\nProduct reading list.md'],['Working location','~/Developer/personal']].forEach(function(d,i){H.inspSection(ib,APP,d[0],!i);H.quietRow(ib,APP,{title:d[1],glyph:i===3?'folder':'doc',tw:236});});H.order(ib);H.order(ins);}
else if(b==='recent'){['Today','Yesterday'].forEach(function(label,i){var g=group(m,label,w);conversations.slice(i*6,i*6+6).forEach(function(d){row(g,d[0],d[1]+' · '+d[3]+' tokens','bubble',w,'conversation',d[2]);});H.order(g);});}
else if(b==='artifacts'){seg(m,['All','Documents','Code','Images'],'artifacts');for(var i=0;i<2;i++){var gr=R(m,'artifact-row',w,null,24);artifacts.slice(i*3,i*3+3).forEach(function(d){var cw=(w-48)/3,c=F(gr,'link:artifacts--detail',cw,null,'col',10);var th=F(c,'artifact-thumbnail',cw,168,'col',16,20,C('panel'));th.style.corners.radii=[12,12,12,12];icon(th,d[0]);T(th,d[5],14,'secondary',cw-40);H.order(th);T(c,d[1],14,'ink',cw,true);T(c,d[2],12,'tertiary',cw);T(c,d[3],12,'tertiary',cw);H.order(c);});H.order(gr);}T(m,'6 of 48 artifacts · Saved from your conversations',12,'tertiary');}
else if(b==='routines'){T(m,'Weave runs these routines even when you are away.',14,'secondary');var g=group(m,'Scheduled',w);[['Daily brief','Every day · 08:00','Today · 42 sec',true],['Weekly digest','Friday · 17:00','Paused · 11 Sep',false],['Delivery watch','Weekdays · 16:00','Today · 28 sec',true],['Cloud health check','Every day · 09:00','Today · 36 sec',true]].forEach(function(d){var r=R(g,'routine',w,64,14);icon(r,'clock');var tx=F(r,'text',470,null,'col',4);T(tx,d[0],14);T(tx,d[1],12,'tertiary');H.order(tx);sp(r);H.dot(r,H.hex(APP,d[3]?'accent':'tertiary'),5);T(r,d[2],12,'tertiary',180);[['activity--work','play'],['routines',d[3]?'pause':'arrow_clockwise'],['routines--new','pencil']].forEach(function(a){H.sfBtn(r,'link:'+a[0],a[1],APP,{size:16,weight:5,w:28,h:28});});H.order(r);});H.order(g);g=group(m,'Recent runs',w);[['Daily brief','8 priorities from your inbox and calendar'],['Cloud health check','No new staging errors · 212 tests passing'],['Delivery watch','2 orders due Thursday · Dock slot confirmed']].forEach(function(d){row(g,d[0],d[1],'clock',w,'activity--work');});H.order(g);T(m,'Asia/Singapore · External actions still require your approval.',12,'tertiary');}
else if(ID==='customize--profile'){T(m,'Your default profile for thoughtful, everyday work.',14,'secondary');var g=group(m,'Profile',800);field(g,'Name','General',800);field(g,'Description','Be direct, curious and practical. Explain trade-offs, cite evidence and turn decisions into clear next steps.',800,true);field(g,'Model','Claude Fable 5.1',800,false,true);H.order(g);g=group(m,'Tools',800);[['Web search',true],['Read and edit files',true],['Run terminal commands',true],['Send email',false]].forEach(function(d){row(g,d[0],d[1]?'Enabled':'Ask before sending',d[1]?'checkmark_square':'rectangle_on_rectangle',800,'customize--profile');});H.order(g);T(m,'Terminal commands and external messages ask for approval.',12,'tertiary');var r=R(m,'actions',800,32);sp(r);btn(r,'Cancel','back');btn(r,'Save','customize',true);H.order(r);}
else if(b==='customize'){var g=group(m,'Profiles',w);[['General','Ready · Default · Everyday work across your projects','sparkles'],['Reviewer','Ready · Code, risk and acceptance checks','checklist_shield'],['Research','Ready · Sources, evidence and synthesis','book']].forEach(function(d){row(g,d[0],d[1],d[2],w,'customize--profile');});H.order(g);var cols=R(m,'preferences',w,null,40);cols.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;var l=F(cols,'voice-personality',540,null,'col',24),r=F(cols,'tools-skills',540,null,'col',24);g=group(l,'Voice',540);row(g,'Juniper','Warm and clear · Normal rate','mic',540,'customize--profile');togg(g,'Read responses aloud','',false,540);H.order(g);g=group(l,'Personality',540);row(g,'Direct and thoughtful','Detail adapts to the task','sparkles',540,'customize--profile');togg(g,'Remember preferences','',true,540);H.order(g);H.order(l);g=group(r,'Tools',540);togg(g,'Web search','Current information with sources',true,540);togg(g,'Files and terminal','Ask before running commands',true,540);togg(g,'Connected apps','Google Workspace, Linear, GitHub',true,540);H.order(g);g=group(r,'Skills',540);togg(g,'Code review','',true,540);togg(g,'Research & citations','',true,540);togg(g,'Writing in my voice','',false,540);H.order(g);H.order(r);H.order(cols);T(m,'Changes apply to new conversations. Existing conversations keep their current profile.',12,'tertiary');}
H.order(m);col.stackLayout.apply();s.stackLayout.apply();s.frame.x=IDS.indexOf(ID)*1560;s.frame.y=1060;}
function overlay(s){if(ID!=='routines--new'&&ID!=='artifacts--detail')return;H.macScrim(s,APP);var routine=ID==='routines--new',wid=routine?580:760,sh=F(s,routine?'sheet/New routine':'artifact-detail',wid,null,'col',24,28,C('panel'));sh.style.corners.radii=routine?[16,16,16,16]:[12,12,12,12];sh.style.shadows=[{color:'#00000040',blur:32,x:0,y:12,spread:0}];var iw=wid-56;
if(routine){T(sh,'New routine',15,'ink',null,true);field(sh,'Name','Morning priorities',iw);field(sh,'Prompt','Summarize my calendar, priority email and open Linear issues. Suggest the three most important actions for today.',iw,true);field(sh,'Schedule','Every day at 08:00',iw,false,true);field(sh,'Profile','General',iw,false,true);field(sh,'Project','Personal',iw,false,true);T(sh,'Asia/Singapore · Sending messages requires approval.',12,'tertiary',iw);var a=R(sh,'actions',iw,32);sp(a);btn(a,'Cancel','back');btn(a,'Create','routines',true);H.order(a);}
else{var hd=R(sh,'header',iw,32);T(hd,'Q3 investor update',15,'ink',null,true);sp(hd);btn(hd,'Share','artifacts--detail');btn(hd,'Done','back');H.order(hd);seg(sh,['Preview','Code'],'artifacts--detail');H.caps(sh,APP,'Straits Lab / Quarterly letter');T(sh,'A focused quarter. A more reliable cloud.',22,'ink',iw,true);T(sh,'15 September 2026 · Abhi Bansal · Markdown · 18 KB',12,'tertiary');T(sh,'This quarter we concentrated on one promise: agents should make progress you can inspect, trust and recover.',14,'ink',iw);T(sh,'What shipped',15,'ink',iw,true);T(sh,'• Durable sessions with recovery across restarts\n• An inspectable work log for every tool run\n• Native Mac workflows for projects and artifacts',14,'secondary',iw);T(sh,'What comes next',15,'ink',iw,true);T(sh,'We are tightening onboarding and approval boundaries before opening the next cohort. Reliability remains the release gate.',14,'secondary',iw);btn(sh,'Open conversation','conversation');}
H.order(sh);sh.frame.x=(1440-wid)/2;sh.frame.y=routine?140:120;sh.moveToFront();if(!routine){var pop=F(s,'popover/Share',224,null,'col',8,16,C('surface'));pop.style.corners.radii=[12,12,12,12];pop.style.shadows=[{color:'#00000030',blur:24,x:0,y:8,spread:0}];[['link','Copy link'],['envelope','Mail'],['doc','Export Markdown']].forEach(function(d){row(pop,d[1],null,d[0],192,'back');});H.order(pop);pop.frame.x=878;pop.frame.y=182;pop.moveToFront();}}
function normalize(s){function walk(l){if(l.name.indexOf('link:')===0)l.name=l.name.replace(/ \d+$/,'');(l.layers||[]).forEach(walk);}walk(s);}

var conversations=[['Move the billing webhook handler','Weave Cloud','14:40','41k'],['Draft the Q3 investor update','Personal','13:12','18k'],['Why is the Mac build 40 MB bigger','Weave Cloud','11:48','27k'],['Review the SATS delivery packet','Aheli ops','10:30','12k'],['Compare project memory strategies','Personal','09:52','32k'],['Prepare the weekly engineering digest','Weave Cloud','09:06','16k'],['Reconcile August supplier invoices','Aheli ops','17:42','24k'],['Plan the September product milestones','Personal','16:18','21k'],['Audit the session persistence boundary','Weave Cloud','15:06','36k'],['Write the W Sentosa residency outline','Personal','14:22','15k'],['Check staging webhook replay safety','Weave Cloud','11:10','29k'],['Build a quarterly cash-flow forecast','Aheli ops','09:34','22k']];
var artifacts=[['doc','Q3 investor update','Markdown · 18 KB','Personal · Today, 13:12','#bd8840','Q3 / 2026\n\nA focused quarter.\nA more reliable cloud.'],['chevron_left_right','Billing webhook extraction','TypeScript diff · 3 files','Weave Cloud · Today, 14:40','#539d76','+ enqueue(event.id)\n+ replayLedger(event)\n− await sendEmail()'],['photo_on_rectangle','Weave launch direction','PNG · 1440 × 900','Personal · Yesterday, 14:22','#727bc5','WEAVE\n\nA quieter kind of capable.'],['doc','SATS delivery checklist','Markdown · 12 KB','Aheli ops · Today, 10:30','#bd8840','DELIVERY / 18 SEPT\n\n01  Confirm dock slot\n02  Check cold-chain log'],['chevron_left_right','Session recovery tests','Swift · 6 tests','Weave Cloud · Yesterday, 15:06','#539d76','func testRecovery() {\n  restore(session)\n  assertNoLostTurns()\n}'],['doc','September milestones','Markdown · 9 KB','Personal · Yesterday, 16:18','#bd8840','SEPTEMBER\n\nShip the native Mac app.\nMake work inspectable.']];
var APP="Dark/Clean";var ID="customize";var s=shell();console.log(JSON.stringify({id:ID,app:APP,frame:String(s.id),stage:"shell"}));