import { expect, test, type Route } from "@playwright/test";

test("preview switches between supplied document, empty and rejected input without unsafe frames", async ({ page }) => {
  await page.goto("/#vercel:web-preview");
  const example = page.getByTestId("live-example");
  const data = example.getByLabel("Preview data", { exact: true });
  await expect(example.frameLocator("iframe").getByRole("heading", { name: "A quiet place to work." })).toBeVisible();
  await data.selectOption("empty");
  await expect(example.getByRole("status")).toHaveText("No preview URL supplied");
  await expect(example.locator("iframe")).toHaveCount(0);
  await data.selectOption("rejected");
  await expect(example.getByRole("alert")).toHaveText("Preview URL unavailable");
  await expect(example.locator("iframe")).toHaveCount(0);
  await expect(example.getByText("No preview URL supplied")).toHaveCount(0);
  await data.selectOption("document");
  await expect(example.getByRole("alert")).toHaveCount(0);
  await expect(example.frameLocator("iframe").getByRole("heading", { name: "A quiet place to work." })).toBeVisible();
  await expect(example.locator("iframe")).toHaveAttribute("sandbox", "allow-scripts");
  await expect(example.locator("iframe")).toHaveAttribute("referrerpolicy", "no-referrer");
  await expect(example.getByText("Loading preview", { exact: true })).toHaveCount(0);
});

test("preview pending replacement and reload follow real local frame loads while disabled retains identity", async ({ page }) => {
  const pending: Route[] = [];
  await page.route("**/__web-preview-lifecycle/**", route => { pending.push(route); });
  await page.goto("/#vercel:web-preview");
  const example = page.getByTestId("live-example");
  const url = example.getByRole("textbox", { name: "Preview URL", exact: true });
  const open = example.getByRole("button", { name: "Open", exact: true });
  const reload = example.getByRole("button", { name: "Reload", exact: true });
  const address = new URL("/__web-preview-lifecycle/first", page.url()).href;
  const replacement = new URL("/__web-preview-lifecycle/replacement", page.url()).href;
  const initial = await example.locator("iframe").elementHandle();
  await url.fill(address);
  expect(pending).toHaveLength(0);
  await open.click();
  await expect.poll(() => pending.length).toBe(1);
  await expect(example.getByRole("status")).toHaveText("Loading preview");
  expect(await initial!.evaluate(frame => frame.isConnected)).toBe(false);
  await expect(example.locator("iframe")).not.toHaveAttribute("srcdoc");
  await pending[0].fulfill({ contentType: "text/html", body: "<!doctype html><h1>First local fixture</h1>" });
  await expect(example.frameLocator("iframe").getByRole("heading", { name: "First local fixture" })).toBeVisible();
  await expect(example.getByText("Loading preview", { exact: true })).toHaveCount(0);
  const first = await example.locator("iframe").elementHandle();
  await url.fill(replacement);
  await example.getByLabel("Disable preview controls", { exact: true }).check();
  await expect(url).toBeDisabled();
  await expect(open).toBeDisabled();
  await expect(reload).toBeDisabled();
  await open.evaluate(button => (button as HTMLButtonElement).click());
  await reload.evaluate(button => (button as HTMLButtonElement).click());
  await expect(url).toHaveValue(replacement);
  expect(await example.locator("iframe").evaluate((frame, original) => frame === original, first)).toBe(true);
  await expect(example.frameLocator("iframe").getByRole("heading", { name: "First local fixture" })).toBeVisible();
  expect(pending).toHaveLength(1);
  await example.getByLabel("Disable preview controls", { exact: true }).uncheck();
  await expect(url).toBeEnabled();
  await open.click();
  await expect.poll(() => pending.length).toBe(2);
  expect(await first!.evaluate(frame => frame.isConnected)).toBe(false);
  await expect(example.getByRole("status")).toHaveText("Loading preview");
  await pending[1].fulfill({ contentType: "text/html", body: "<!doctype html><h1>Replacement local fixture</h1>" });
  await expect(example.frameLocator("iframe").getByRole("heading", { name: "Replacement local fixture" })).toBeVisible();
  await expect(example.getByText("Loading preview", { exact: true })).toHaveCount(0);
  const second = await example.locator("iframe").elementHandle();
  await reload.click();
  await expect.poll(() => pending.length).toBe(3);
  expect(await second!.evaluate(frame => frame.isConnected)).toBe(false);
  await expect(example.getByRole("status")).toHaveText("Loading preview");
  await pending[2].fulfill({ contentType: "text/html", body: "<!doctype html><h1>Reloaded local fixture</h1>" });
  await expect(example.frameLocator("iframe").getByRole("heading", { name: "Reloaded local fixture" })).toBeVisible();
  await expect(example.getByText("Loading preview", { exact: true })).toHaveCount(0);
  await expect(example.locator("iframe")).toHaveAttribute("sandbox", "allow-scripts");
  await expect(example.locator("iframe")).toHaveAttribute("referrerpolicy", "no-referrer");
});
