import { expect, test } from "@playwright/test";

for (const mode of ["Manual", "Automatic", "Branching"] as const) {
  test(`CHECKPOINT ${mode} local records preserve refused and accepted host selection`, async ({ page }) => {
    await page.goto("/#vercel:checkpoint");
    const sample = page.getByRole("region", { name: "Local checkpoint modes" });
    await sample.getByRole("button", { name: mode, exact: true }).click();
    const history = mode === "Branching" ? "Main" : mode;
    const markers = sample.getByRole("group", { name: `${history} checkpoint markers` });
    await expect(markers.getByRole("button")).toHaveCount(1);
    await sample.getByRole("button", { name: mode === "Automatic" ? "Supply automatic sample records" : "Add local marker", exact: true }).click();
    await expect(markers.getByRole("button")).toHaveCount(2);
    await expect(sample.getByLabel("Local checkpoint selection", { exact: true })).toHaveText(`${history}: None selected`);
    const first = markers.getByRole("button", { name: `${history} marker 1`, exact: true });
    const second = markers.getByRole("button", { name: `${history} marker 2`, exact: true });
    const firstBounds = await first.boundingBox();
    const secondBounds = await second.boundingBox();
    expect(firstBounds!.height).toBeGreaterThan(0);
    expect(firstBounds!.width).toBeGreaterThan(0);
    expect(secondBounds!.y).toBeGreaterThanOrEqual(firstBounds!.y + firstBounds!.height);
    await sample.getByLabel("Local branch or mode draft", { exact: true }).fill(`${mode} retained draft`);
    await first.focus();
    await first.press("Enter");
    await expect(first).toBeFocused();
    await expect(first).toHaveAttribute("aria-pressed", "true");
    await sample.getByLabel("Refuse local checkpoint selection").check();
    await second.click();
    await expect(sample.getByLabel("Local checkpoint request", { exact: true })).toHaveText(`Refused local selection: ${history} marker 2. No runtime action.`);
    await expect(first).toHaveAttribute("aria-pressed", "true");
    await expect(second).toHaveAttribute("aria-pressed", "false");
    await expect(sample.getByLabel("Local checkpoint selection", { exact: true })).toHaveText(`${history}: ${history} marker 1`);
    await sample.getByLabel("Refuse local checkpoint selection").uncheck();
    await second.focus();
    await second.press("Space");
    await expect(second).toBeFocused();
    await expect(second).toHaveAttribute("aria-pressed", "true");
    await expect(first).toHaveAttribute("aria-pressed", "false");
    await expect(sample.getByLabel("Local checkpoint request", { exact: true })).toHaveText(`Accepted local selection: ${history} marker 2. No runtime action.`);
    await expect(sample.getByLabel("Local checkpoint selection", { exact: true })).toHaveText(`${history}: ${history} marker 2`);
    await expect(sample.getByLabel("Local branch or mode draft", { exact: true })).toHaveValue(`${mode} retained draft`);
    await expect(sample.getByText(/These in-memory samples do not save or restore runtime history/)).toBeVisible();
    if (mode === "Automatic") {
      await expect(sample.getByRole("button", { name: "Supply automatic sample records" })).toBeDisabled();
      await expect(sample.getByText("Automatic records are supplied by the sample host, not generated by a clock or runtime.")).toBeVisible();
    }
  });
}

test("CHECKPOINT branch records selections and drafts remain isolated across local modes", async ({ page }) => {
  await page.goto("/#vercel:checkpoint");
  const sample = page.getByRole("region", { name: "Local checkpoint modes" });
  const draft = sample.getByLabel("Local branch or mode draft", { exact: true });
  await sample.getByRole("button", { name: "Branching", exact: true }).click();
  await draft.fill("Main unsaved changes");
  await sample.getByRole("button", { name: "Add local marker", exact: true }).click();
  await sample.getByRole("button", { name: "Main marker 2", exact: true }).click();
  await sample.getByRole("button", { name: "Alternative", exact: true }).click();
  await expect(draft).toHaveValue("Alternative draft");
  await expect(sample.getByLabel("Local checkpoint selection", { exact: true })).toHaveText("Alternative: None selected");
  await expect(sample.getByRole("button", { name: /^Main marker/ })).toHaveCount(0);
  await expect(sample.getByRole("group", { name: "Alternative checkpoint markers" }).getByRole("button")).toHaveCount(1);
  await draft.fill("Alternative unsaved changes");
  await sample.getByLabel("Refuse local checkpoint selection").check();
  await sample.getByRole("button", { name: "Alternative marker 1", exact: true }).click();
  await expect(sample.getByLabel("Local checkpoint selection", { exact: true })).toHaveText("Alternative: None selected");
  await sample.getByLabel("Refuse local checkpoint selection").uncheck();
  await sample.getByRole("button", { name: "Alternative marker 1", exact: true }).click();
  await sample.getByRole("button", { name: "Main", exact: true }).click();
  await expect(draft).toHaveValue("Main unsaved changes");
  await expect(sample.getByLabel("Local checkpoint selection", { exact: true })).toHaveText("Main: Main marker 2");
  await expect(sample.getByRole("group", { name: "Main checkpoint markers" }).getByRole("button")).toHaveCount(2);
  await sample.getByRole("button", { name: "Manual", exact: true }).click();
  await expect(draft).toHaveValue("Manual draft");
  await expect(sample.getByLabel("Local checkpoint selection", { exact: true })).toHaveText("Manual: None selected");
  await sample.getByRole("button", { name: "Automatic", exact: true }).click();
  await expect(draft).toHaveValue("Automatic draft");
  await expect(sample.getByLabel("Local checkpoint selection", { exact: true })).toHaveText("Automatic: None selected");
  await sample.getByRole("button", { name: "Branching", exact: true }).click();
  await sample.getByRole("button", { name: "Alternative", exact: true }).click();
  await expect(draft).toHaveValue("Alternative unsaved changes");
  await expect(sample.getByLabel("Local checkpoint selection", { exact: true })).toHaveText("Alternative: Alternative marker 1");
});

test("CHECKPOINT disabled local host controls cannot change selection or drafts", async ({ page }) => {
  await page.goto("/#vercel:checkpoint");
  await page.getByLabel("Example state").selectOption("disabled");
  const sample = page.getByRole("region", { name: "Local checkpoint modes" });
  for (const button of await sample.getByRole("button").all()) await expect(button).toBeDisabled();
  await expect(sample.getByLabel("Refuse local checkpoint selection")).toBeDisabled();
  await expect(sample.getByLabel("Local branch or mode draft", { exact: true })).toBeDisabled();
  await sample.getByRole("button", { name: "Manual marker 1", exact: true }).evaluate((button: HTMLButtonElement) => button.click());
  await expect(sample.getByLabel("Local checkpoint request", { exact: true })).toHaveText("No local selection requested");
  await expect(sample.getByLabel("Local checkpoint selection", { exact: true })).toHaveText("Manual: None selected");
  await expect(sample.getByLabel("Local branch or mode draft", { exact: true })).toHaveValue("Manual draft");
});
