var p=H.page('AI Voice & Workflow');var out=[];function all(l){var a=[];(l.layers||[]).forEach(function(k){a.push(k);a=a.concat(all(k));});return a;}
p.layers.forEach(function(sh){var app=sh.name.split(' — ')[1];if(!app)return;var fam=sh.name.split(' — ')[0],ls=all(sh);
if(['Canvas','Node','Connection'].indexOf(fam)>=0){ls.filter(function(l){return l.type==='ShapePath'&&Math.abs(l.frame.width-12)<0.1&&Math.abs(l.frame.height-12)<0.1;}).forEach(function(l){l.style.borders=[{color:H.sw(app,'secondary'),thickness:2,position:sketch.Style.BorderPosition.Inside}];});}
if(fam==='MicSelector'){ls.filter(function(l){return l.type==='Text'&&(l.text==='Input level'||l.text==='INPUT DEVICE');}).forEach(function(l){l.style.textColor=H.sw(app,'secondary');});ls.filter(function(l){return l.type==='ShapePath'&&l.frame.width===5&&l.frame.height===12;}).forEach(function(l){if(String(l.style.fills[0].color)===String(H.sw(app,'line')))l.style.fills=[{color:H.sw(app,'tertiary'),fillType:sketch.Style.FillType.Color}];});}
if(fam==='AudioPlayer'){ls.filter(function(l){return l.parent&&l.parent.name==='waveform'&&l.type==='ShapePath';}).forEach(function(l){if(String(l.style.fills[0].color)===String(H.sw(app,'line-strong')))l.style.fills=[{color:H.sw(app,'tertiary'),fillType:sketch.Style.FillType.Color}];});}
if(fam==='Controls'){ls.filter(function(l){return l.type==='ShapePath'&&l.style.borders.length>0;}).forEach(function(l){l.style.borders.forEach(function(b){b.color=H.sw(app,'ink');});});}
if(fam==='Canvas'){var c=ls.find(function(l){return l.name==='node canvas';});var nodes=c.layers.filter(function(l){return /^work unit/.test(l.name);}).sort(function(a,b){return a.frame.x-b.frame.x;});var vectors=c.layers.filter(function(l){return /^editable vector/.test(l.name);});vectors.slice(1).forEach(function(v){v.remove();});c.layers.filter(function(l){return /^chip/.test(l.name)&&l.layers.some(function(t){return t.type==='Text'&&(t.text==='context'||t.text==='result');});}).forEach(function(l){l.remove();});
function coord(n,label){var r=n.layers.find(function(l){return l.layers&&l.layers.some(function(t){return t.type==='Text'&&t.text===label;});});var port=r.layers.find(function(l){return l.type==='ShapePath'&&l.frame.width===12;});return {x:n.frame.x+r.frame.x+port.frame.x+6,y:n.frame.y+r.frame.y+port.frame.y+6};}
for(var i=0;i<2;i++){var a=coord(nodes[i],'Output'),b=coord(nodes[i+1],'Input'),color=H.hex(app,i?'accent':'line-strong');var path='M'+a.x+' '+a.y+' C'+(a.x+60)+' '+a.y+' '+(b.x-60)+' '+b.y+' '+b.x+' '+b.y;var v=sketch.createLayerFromData('<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="640"><path d="'+path+'" fill="none" stroke="'+color+'" stroke-width="2"/><path d="m'+(b.x-6)+' '+(b.y-4)+' 6 4-6 4" fill="none" stroke="'+color+'" stroke-width="2"/></svg>','svg');v.name='port-bound edge';v.parent=c;var t=H.frame({parent:c,name:'edge label',dir:'row',pad:{top:4,right:8,bottom:4,left:8},fill:H.sw(app,'hover'),radius:999});H.text({parent:t,text:i?'result':'context',size:12,color:H.sw(app,i?'accent':'secondary')});H.order(t);t.frame.x=(a.x+b.x)/2-28;t.frame.y=(a.y+b.y)/2-12;out.push({app:app,from:a,to:b});}}
});H.out({fixed:true,connections:out});