from pathlib import Path
import json
root=Path('/tmp/harso-sk/lanes/ai-voice-workflow')
bodies={
'AudioPlayer':'''['default','playing'].forEach(function(s){var f=specimen(s,520);title(f,'Studio chime');txt(f,'Local audio · PCM WAV',13,'secondary');var r=row(f,16);button(r,'',s==='playing'?'pause':'play',true);waveform(r,62,18,48);done(r);var b=row(f,16);H.text({parent:b,text:'0:42 / 3:10',mono:true,size:13,color:H.sw(APP,'secondary')});chip(b,'1×');icon(b,'volume');done(b);done(f);});''',
'MicSelector':'''var f=specimen('trigger/default',360,'row');f.frame.height=36;f.verticalSizing=sketch.FlexSizing.Fixed;f.stackLayout.padding={top:0,right:14,bottom:0,left:14};icon(f,'mic');txt(f,'Studio microphone (1234:abcd)',13,'ink');icon(f,'chevronsUpDown');done(f);var o=specimen('list/open',384);o.style.corners.radii=[16,16,16,16];o.style.shadows=[{color:'#0000001f',blur:24,spread:0,x:0,y:8}];var search=row(o);icon(search,'search');txt(search,'Search microphones',13,'tertiary');done(search);txt(o,'INPUT DEVICE',12,'tertiary');['Studio microphone (1234:abcd)','Built-in microphone','Wireless headset'].forEach(function(t,i){var r=H.frame({parent:o,name:'device',dir:'col',pad:10,gap:8,w:352,fill:i===0?H.sw(APP,'hover'):null,radius:6,align:sketch.StackLayout.AlignItems.Start});var h=row(r);icon(h,'mic');txt(h,t,13,'ink',274);if(!i)icon(h,'check','accent');done(h);var b=row(r);txt(b,'Input level',12,'tertiary',220);meter(b,7-i*2);done(b);done(r);if(i<2){var sep=row(o);H.rect({parent:sep,w:26,h:1});line(sep,326);done(sep);}});done(o);''',
'Persona':'''['default','selected'].forEach(function(s){var f=specimen(s,320);if(s==='selected')f.style.borders=[{color:H.sw(APP,'accent'),thickness:2,position:sketch.Style.BorderPosition.Inside}];var h=row(f,12);var av=H.frame({parent:h,name:'avatar',dir:'row',w:48,h:48,justify:sketch.StackLayout.JustifyContent.Center,radius:999,fill:H.sw(APP,'accent-soft')});icon(av,'user','accent',24);done(av);var c=col(h,4);title(c,'Maya');txt(c,'British · Feminine',12,'secondary');done(c);done(h);txt(f,'Warm, unhurried and clear.',14,'secondary',288);var b=row(f);button(b,'Preview','play');if(s==='selected')chip(b,'Selected','accent');done(b);done(f);});''',
'SpeechInput':'''['idle','active'].forEach(function(s){var f=specimen(s,520);var h=row(f,12);button(h,'',s==='active'?'mic':'mic',s==='active');title(h,s==='active'?'Listening…':'Speech input');if(s==='active')waveform(h,30,30,32);done(h);txt(f,s==='active'?'The brief is ready. Work is progressing…':'Nothing starts until you press Speak.',14,s==='active'?'ink':'tertiary',488);var b=row(f);button(b,s==='active'?'Cancel':'Speak',s==='active'?'x':'mic',false);if(s==='active')button(b,'Done','check',true);done(b);done(f);});''',
'Transcription':'''var f=specimen('live',560);var h=row(f,24);title(h,'Project update');H.text({parent:h,text:'00:03 / 00:09',size:13,mono:true,color:H.sw(APP,'tertiary')});chip(h,'Live','positive');done(h);[['Maya','00:00','The brief is ready.'],['Eli','00:02','Work is progressing.'],['Maya','00:05','Next, review the references…']].forEach(function(v,i){var r=col(f,8);var a=row(r,12);title(a,v[0]);H.text({parent:a,text:v[1],size:13,mono:true,color:H.sw(APP,'tertiary')});if(i===2)chip(a,'Interim');done(a);txt(r,v[2],14,i===2?'tertiary':'ink',528);done(r);});txt(f,'Select a phrase to move the playhead.',12,'secondary');done(f);''',
'VoiceSelector':'''var f=specimen('grid/selected',744);title(f,'Find your conversational rhythm.');txt(f,'A voice that feels natural',13,'secondary');var rr=row(f,12);[['Maya','British · Feminine','Warm, unhurried and clear.'],['Eli','American · Masculine','Direct, calm and conversational.'],['River','Australian · Neutral','Bright, relaxed and expressive.']].forEach(function(v,i){var c=H.frame({name:'voice card',parent:rr,dir:'col',pad:16,gap:12,w:228,radius:12,border:H.sw(APP,i===0?'accent':'line'),bw:i===0?2:1,fill:H.sw(APP,'surface'),align:sketch.StackLayout.AlignItems.Start});var h=row(c);title(h,v[0]);if(!i)icon(h,'check','accent');done(h);txt(c,v[1],12,'secondary',196);txt(c,v[2],13,'secondary',196);button(c,'Preview','play');done(c);});done(rr);done(f);''',
'Canvas':'''var f=specimen('default',1056);var c=absolute(f,'node canvas',1024,640);H.rect({parent:c,w:1024,h:640,fill:H.sw(APP,'canvas'),radius:12});var dots='';for(var yy=16;yy<640;yy+=24)for(var xx=16;xx<1024;xx+=24)dots+='<circle cx="'+xx+'" cy="'+yy+'" r="1" fill="'+H.hex(APP,'line-strong')+'"/>';svg(c,dots,1024,640);curve(c,296,195,392,315,false,'context');curve(c,632,315,728,435,true,'result');[['Research','idle',56,96],['Work unit','running',392,216],['Result','idle',728,336]].forEach(function(a){var n=node(c,a[0],a[1],a[1]==='running');n.frame.x=a[2];n.frame.y=a[3];});var status=chip(c,'100% · 0, 0');status.frame.x=24;status.frame.y=596;done(f);''',
'Node':'''['idle','running','error','selected'].forEach(function(s){var f=specimen(s);f.style.fills=[];f.style.borders=[];f.stackLayout.padding=0;node(f,'Work unit',s==='selected'?'idle':s,s==='selected');done(f);});''',
'Edge':'''['default','selected'].forEach(function(s){var f=specimen(s,544);var c=absolute(f,'connection path',512,160);var color=H.hex(APP,s==='selected'?'accent':'line-strong');svg(c,'<path d="M16 32 C210 32 290 128 496 128" fill="none" stroke="'+color+'" stroke-width="2"/><path d="m488 123 8 5-8 5" fill="none" stroke="'+color+'" stroke-width="2"/>',512,160);var tag=chip(c,'context',s==='selected'?'accent':'secondary');tag.frame.x=216;tag.frame.y=62;done(f);});''',
'Connection':'''['default','hover'].forEach(function(s){var f=specimen(s,100);f.style.fills=[];f.style.borders=[];var c=absolute(f,'port area',32,32);if(s==='hover')H.rect({parent:c,x:3,y:3,w:26,h:26,oval:true,border:H.sw(APP,'accent'),bw:2});var d=H.rect({parent:c,x:10,y:10,w:12,h:12,oval:true,fill:H.sw(APP,'surface'),border:H.sw(APP,s==='hover'?'accent':'line-strong'),bw:2});done(f);});''',
'Controls':'''var f=specimen('vertical/default',48);f.stackLayout.padding=6;f.stackLayout.gap=0;f.style.corners.radii=[20,20,20,20];f.style.shadows=[{color:'#0000001f',blur:24,spread:0,x:0,y:8}];['plus','minus','maximize','lock'].forEach(function(k){var b=button(f,'',k);b.frame.width=36;b.horizontalSizing=sketch.FlexSizing.Fixed;b.style.borders=[];});done(f);''',
'Panel':'''var f=specimen('inspector/default',320);title(f,'Work unit');txt(f,'Node inspector',12,'tertiary');var tabs=row(f);chip(tabs,'Properties','ink');txt(tabs,'Runs',13,'secondary');txt(tabs,'Settings',13,'secondary');done(tabs);line(f,288);[['Name','Work unit'],['Model','Balanced'],['Temperature','0.7'],['Max tokens','2,048']].forEach(function(a,i){var r=H.frame({parent:f,name:'form row',dir:'row',gap:12,h:36});txt(r,a[0],13,'secondary',94);var c=H.frame({parent:r,name:'field',dir:'row',pad:8,w:182,h:32,radius:8,fill:H.sw(APP,'canvas'),border:H.sw(APP,'line')});txt(c,a[1],13,'ink',132);if(i===1)icon(c,'chevronsUpDown',null,14);if(i>1)icon(c,'chevronsUpDown',null,14);done(c);done(r);});txt(f,'Instructions',13,'secondary');var area=H.frame({parent:f,name:'instructions',dir:'col',pad:12,w:288,h:96,fill:H.sw(APP,'canvas'),border:H.sw(APP,'line'),radius:8,align:sketch.StackLayout.AlignItems.Start});txt(area,'Review the brief and produce a clear, concise result.',13,'ink',264);done(area);button(f,'Apply changes','check',true);done(f);''',
'Toolbar':'''var f=specimen('canvas/default',null,'row');f.style.corners.radii=[16,16,16,16];f.stackLayout.padding=8;button(f,'Run','play',true);button(f,'','undo');button(f,'','redo');H.rect({parent:f,w:1,h:24,fill:H.sw(APP,'line')});button(f,'Add node','plus');button(f,'Layout','layers');button(f,'Share','upload');done(f);''',
'Image':'''var f=specimen('generating',320);var p=absolute(f,'image placeholder',288,192);H.rect({parent:p,w:288,h:192,radius:8,fill:H.sw(APP,'hover')});H.rect({parent:p,x:100,y:0,w:72,h:192,fill:H.sw(APP,'surface')});var im=icon(p,'image','tertiary',32);im.frame.x=128;im.frame.y=68;var t=txt(p,'Generating image…',12,'tertiary');t.frame.x=84;t.frame.y=118;title(f,'A quiet landscape');txt(f,'Generated image · 1024 × 1024',12,'secondary');var r=row(f);button(r,'','download');button(r,'','refresh');done(r);done(f);''',
'OpenInChat':'''['small','default','large'].forEach(function(s){var f=specimen(s,null,'row');f.stackLayout.padding={top:0,right:s==='small'?10:14,bottom:0,left:s==='small'?10:14};f.frame.height=s==='small'?28:s==='large'?44:36;f.verticalSizing=sketch.FlexSizing.Fixed;f.style.corners.radii=[8,8,8,8];icon(f,'chat','secondary',s==='small'?14:16);H.text({parent:f,text:'Open in Weave',size:s==='small'?12:14,weight:6,color:H.sw(APP,'ink')});icon(f,'external','secondary',s==='small'?14:16);done(f);});'''
}
common=(root/'common.js').read_text()
footer="\nH.order(sh);H.relayout(sh);var made=H.symbolize(sh,new RegExp('^'+FAMILY+'/'));H.relayout(sh);sh.frame.x=apps.indexOf(APP)*1600;sh.frame.y=y;H.out({ok:true,family:FAMILY,app:APP,sheet:String(sh.id),made:made,h:Math.round(sh.frame.height),w:Math.round(sh.frame.width),y:sh.frame.y});\n"
for family,body in bodies.items():
 (root/(family+'.js')).write_text("var APP = 'Light/Clean';\nvar FAMILY = '"+family+"';\n"+common+'\n'+body+footer)
(root/'families.json').write_text(json.dumps(list(bodies)))
print('Generated',len(bodies),'family scripts')
