var page=H.page('Charts'),name=CFG[0]+' — '+APP,old=page.layers.find(l=>l.name===name);if(!old)throw Error('Missing target');var xx=old.frame.x,yy=old.frame.y;H.dropSheet('Charts',name);
var sh=H.sheet({name:name,parent:page,x:xx,y:yy,fill:H.hex(APP,'canvas-deep')});sh.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;
H.text({parent:sh,text:name,size:20,weight:6,color:H.sw(APP,'ink')});
function frame(parent,name,dir,w,gap){var f=H.frame({parent:parent,name:name,dir:dir,w:w,gap:gap||0});f.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;return f;}
function txt(parent,text,size,role,w,weight){return H.text({parent:parent,text:text,size:size||12,color:H.sw(APP,role||'secondary'),w:w,weight:weight||5});}
function select(parent,labels,selected){var f=H.frame({parent:parent,name:labels.length===1?'period selector':'segmented control',dir:'row',pad:3,gap:2,radius:8,fill:H.sw(APP,'hover'),border:H.sw(APP,'line'),h:30});labels.forEach((v,i)=>{var q=H.frame({parent:f,name:'option '+v,dir:'row',pad:{top:3,right:10,bottom:3,left:10},h:24,radius:6,fill:i===selected?H.sw(APP,'surface'):null,gap:8});txt(q,v,12,'ink',null,6);if(labels.length===1)H.icon({parent:q,d:H.paths.chevronDown,size:12,color:C.secondary});H.order(q);});H.order(f);return f;}
var card=H.frame({name:CFG[0]+'/'+APP+'/default',parent:sh,dir:'col',gap:12,pad:20,w:1000,radius:12,fill:H.sw(APP,'surface'),border:H.sw(APP,'line')});card.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;
var hd=frame(card,'header','row',960,16),titles=frame(hd,'titles','col',680,4);txt(titles,CFG[2],14,'ink',680,6);if(CFG[3])txt(titles,CFG[3],12,'secondary',680);H.order(titles);
var controls=frame(hd,'controls','row',264,6);controls.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.End;
if(CFG[1]==='line')select(controls,['Weekly','Monthly','Yearly'],1);else if(CFG[1]==='revenue')select(controls,['Week','Month'],0);else if(!['activity','days','contributions'].includes(CFG[1])){select(controls,[['area','combo'].includes(CFG[1])?'Monthly':CFG[1]==='heatmap'?'Current period':['sankey','scatter'].includes(CFG[1])?'This month':'Week'],0);if(['radial','radar'].includes(CFG[1]))select(controls,[CFG[1]==='radar'?'filled':'rings'],0);}H.order(controls);if(['activity','days','contributions'].includes(CFG[1])){controls.remove();}H.order(hd);
var kind=CFG[1];if(['activity','days'].includes(kind))card.stackLayout.gap=6;
if(['orders','revenue'].includes(kind))txt(card,'Current: 0.75 · Previous: 0.375 · Change: +100%',12,'secondary',960);
else if(kind==='area')txt(card,'Total: 18,350',24,'ink',960,6);
else if(kind==='line')txt(card,'Revenue observations · total: 12,500',14,'ink',960,6);
else if(kind==='combo')txt(card,'Sessions · total: 12,500 · Conversion · average: 3.5%',14,'ink',960,6);
else if(kind==='heatmap')txt(card,'Total: 315 · Compared periods supplied by the host',12,'secondary',960);
else if(kind==='sankey')txt(card,'Source total: $3,000 · Sink total: $3,000',12,'secondary',960);
else if(kind==='scatter')txt(card,'6 observations · Focus or touch a point to inspect',12,'secondary',960);
else if(!['activity','days','contributions'].includes(kind))txt(card,'Focus or touch a value to inspect',12,'secondary',960);
function calendar(parent,selected){var cal=frame(parent,'calendar','col',960,4),nav=frame(cal,'month navigation','row',960,12);txt(nav,'September 2026',13,'ink',864,6);['<path d="m15 18-6-6 6-6"/>',H.paths.chevronRight].forEach(d=>{var btn=H.frame({parent:nav,name:'month button',dir:'row',w:32,h:24,radius:6,fill:H.sw(APP,'hover'),justify:sketch.StackLayout.JustifyContent.Center});H.icon({parent:btn,d:d,size:14,color:C.secondary});H.order(btn);});H.order(nav);var days=frame(cal,'weekdays','row',960,0);['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(v=>{var t=txt(days,v,12,'secondary',137);t.style.alignment='center';});H.order(days);for(var r=0;r<5;r++){var row=frame(cal,'week','row',960,0);for(var c=0;c<7;c++){var n=r*7+c-1,cell=H.frame({parent:row,name:'day '+n,dir:'row',w:137,h:20,justify:sketch.StackLayout.JustifyContent.Center});if(n>=1&&n<=30){var pill=H.frame({parent:cell,name:n===selected?'selected date':'date',dir:'row',w:26,h:20,radius:10,fill:n===selected?H.sw(APP,'ink'):null,justify:sketch.StackLayout.JustifyContent.Center});txt(pill,String(n),12,n===selected?'inverse':'ink');H.order(pill);}H.order(cell);}H.order(row);}H.order(cal);}
if(kind==='days'){calendar(card,1);txt(card,'2026-09-01 activity',13,'ink',960,6);}
var pp=plot(kind),pl=sketch.createLayerFromData(pp.svg,'svg');pl.name='vector plot';pl.parent=card;pl.frame.width=960;pl.frame.height=pp.h;
if(kind==='activity'){txt(card,'Activity days',13,'ink',960,6);calendar(card,7);}
function legend(entries,vertical){var f=frame(card,'series values','row',960,16);if(vertical)f.stackLayout.direction=sketch.StackLayout.Direction.Column;entries.forEach(e=>{var row=frame(f,'series','row',vertical?960:Math.floor((960-(entries.length-1)*16)/entries.length),8);H.rect({parent:row,w:6,h:6,oval:true,fill:H.sw(APP,e[1])});txt(row,e[0],12,'secondary',vertical?930:Math.floor((960-(entries.length-1)*16)/entries.length)-14);H.order(row);});H.order(f);}
if(kind==='area')legend([['Organic · total: 12,500','accent'],['Referral · total: 4,000','secondary'],['Paid · total: 1,850','tertiary']]);
if(kind==='combo')legend([['Sessions · total: 12,500','secondary'],['Conversion · average: 3.5%','accent']]);
if(['orders','revenue'].includes(kind))legend([['Current','accent'],['Previous','secondary']]);
if(kind==='scatter')legend([['Research · 3 points · Mean Outcome: 26.7','accent'],['Delivery · 3 points · Mean Outcome: 27.7','secondary']]);
if(kind==='sleep')legend([['Stage 1: 0 / 1','accent'],['Stage 2: 0.25 / 1','secondary'],['Stage 3: 0.5 / 1','tertiary']],true);
if(['radial','radar'].includes(kind)){H.rect({parent:card,w:960,h:1,fill:H.sw(APP,'line')});var tiles=frame(card,'metric tiles','row',960,16);['Speed','Quality','Care','Reach'].forEach((n,i)=>{var tile=frame(tiles,'metric','col',228,4);var row=frame(tile,'name','row',228,6);if(kind==='radial')H.rect({parent:row,w:6,h:6,oval:true,fill:H.sw(APP,['accent','secondary','tertiary','accent'][i])});txt(row,(kind==='radial'?'Ring '+(i+1)+' · ':'')+n,12,'secondary');H.order(row);txt(tile,['0','0.25','75','100'][i]+(kind==='radial'?'%':''),20,'ink',228,6);H.order(tile);});H.order(tiles);}
if(kind==='sankey'){var lists=frame(card,'node and link breakdown','row',960,24);var node=frame(lists,'nodes','col',510,6),links=frame(lists,'links','col',426,6);txt(node,'Nodes',12,'ink',510,6);txt(links,'Links',12,'ink',426,6);['Salary · In: $0 · Out: $2,400','Freelance · In: $0 · Out: $600','Budget · In: $3,000 · Out: $3,000','Home · In: $1,200 · Out: $0 · 40% of sinks','Everyday · In: $800 · Out: $0 · 26.7% of sinks','Savings · In: $1,000 · Out: $0 · 33.3% of sinks'].forEach(v=>txt(node,v+' ↗',12,'secondary',510));['Salary → Budget: $2,400','Freelance → Budget: $600','Budget → Home: $1,200','Budget → Everyday: $800','Budget → Savings: $1,000'].forEach(v=>txt(links,v+' ↗',12,'secondary',426));H.order(node);H.order(links);H.order(lists);}
if(kind==='contributions'){card.frame.width=440;hd.frame.width=400;titles.frame.width=400;titles.layers.forEach(l=>{l.frame.width=400;});pl.frame.width=400;pl.frame.height=80;}
H.order(card);H.order(sh);H.relayout(sh);var made=H.symbolize(sh,new RegExp('^'+CFG[0]+'/'));sh.frame.x=xx;sh.frame.y=yy;H.out({family:CFG[0],app:APP,sheet:sh.id,made:made,x:sh.frame.x,y:sh.frame.y,h:sh.frame.height});
