var CATS=[['devices','Devices','display'],['account','Account','person'],['general','General','gear'],['appearance','Appearance','sun'],['voice','Voice & Live','mic'],['notifications','Notifications','bell'],['connections','Connections','link'],['billing','Usage & Billing','chart_bar'],['privacy','Data & Privacy','lock'],['shortcuts','Shortcuts','command'],['about','About','info_circle']];
var IDS=['settings','settings-account','settings-devices','settings-general','settings-appearance','settings-voice','settings-notifications','settings-connections','settings-billing','settings-privacy','settings-shortcuts','settings-about','settings--sign-out','settings-billing--plan'];
function buildSettings(APP,ID,phase){
var pageName='Proto macOS '+APP.split('/')[0],page=H.page(pageName),name='Screen/macos/'+APP+'/'+ID;
var cat=(ID==='settings'||ID==='settings--sign-out')?'account':ID.replace('settings-','').split('--')[0];var meta=CATS.find(function(c){return c[0]===cat;});var own='settings-'+cat;
function F(o){var f=H.frame(o);if(o.dir==='col')f.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;return f;}
function T(p,t,o){o=o||{};return H.sft({parent:p,text:String(t),size:o.size||13,weight:o.weight||5,color:o.color||H.sw(APP,'ink'),w:o.w});}
function space(p){var f=F({name:'flex',parent:p,pad:0,h:1});f.horizontalSizing=sketch.FlexSizing.Fill;return f;}
function button(p,text,link,kind){var primary=kind==='primary'||text==='Change plan';var f=F({name:'link:'+(link||own),parent:p,pad:{top:0,right:12,bottom:0,left:12},h:28,radius:999,fill:H.sw(APP,primary?'ink':'hover')});T(f,text,{color:H.sw(APP,primary?'surface':kind==='danger'?'negative':'ink')});H.order(f);return f;}
function control(p,r){var type=r[2]||'value',val=r[1];
if(type==='toggle'){var t=F({name:'link:'+own,parent:p,pad:2,w:26,h:15,radius:999,fill:val?H.sw(APP,'ink'):H.alpha(H.hex(APP,'ink'),0.16),justify:val?sketch.StackLayout.JustifyContent.End:sketch.StackLayout.JustifyContent.Start});H.rect({parent:t,name:'knob',w:11,h:11,oval:true,fill:H.sw(APP,'surface')});H.order(t);}
else if(type==='popup'||type==='stepper'){var f=F({name:'link:'+own,parent:p,pad:{top:0,right:10,bottom:0,left:12},h:28,radius:999,gap:8,fill:H.sw(APP,'hover')});T(f,val);H.sfg(f,'chevron_down',{size:10,color:H.sw(APP,'secondary')});H.order(f);}
else if(type==='segment'){var f=F({name:'segments',parent:p,pad:2,gap:2,h:28,radius:999,fill:H.sw(APP,'hover')});val.forEach(function(v,i){var b=F({name:'link:'+own,parent:f,pad:{top:0,right:12,bottom:0,left:12},h:24,radius:999,fill:i===0?H.sw(APP,'ink'):null});T(b,v,{color:H.sw(APP,i===0?'surface':'secondary')});H.order(b);});H.order(f);}
else if(type==='button')button(p,val,r[3],r[4]);
else if(type==='field'){var f=F({name:'link:'+own,parent:p,pad:{top:0,right:10,bottom:0,left:10},h:28,w:260,radius:8,fill:H.sw(APP,'hover')});T(f,val);H.order(f);}
else if(type==='status'){H.dot(p,H.hex(APP,'accent'),5);T(p,val,{color:H.sw(APP,'secondary')});if(r[3])button(p,r[3],r[4]);}
else if(type==='keys'){val.forEach(function(k){var f=F({name:'key',parent:p,pad:0,w:k==='Space'?52:28,h:24,radius:8,fill:H.sw(APP,'hover'),justify:sketch.StackLayout.JustifyContent.Center});if(k==='command')H.sfg(f,k,{size:13,color:H.sw(APP,'secondary')});else T(f,k,{size:12});H.order(f);});}
else{if(type==='ring')H.ring(p,APP,41200/500000,16);T(p,val,{color:H.sw(APP,'secondary')});if(r[3])button(p,r[3],r[4],r[5]);}H.order(p);}
var s=page.layers.find(function(l){return l.name===name;});
if(phase==='shell'){
page.layers.slice().forEach(function(l){if(l.name===name||(/^caption\//.test(l.name)&&l.name.split('/').pop()===ID))l.remove();});
s=H.screen({page:pageName,platform:'macos',app:APP,id:ID,w:1440,h:900,x:IDS.indexOf(ID)*1560,y:2120});
var w=H.macWindow(s,APP,{active:'settings',title:'Settings',subtitle:meta[1],search:false});w.main.stackLayout.padding={top:24,right:40,bottom:24,left:28};w.main.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;
var split=F({name:'settings-split',parent:w.main,dir:'row',gap:40,pad:0,w:1132,h:792});split.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;
var nav=F({name:'categories',parent:split,dir:'col',gap:2,pad:0,w:220,h:792});var hd=F({name:'category-heading',parent:nav,pad:{top:0,right:10,bottom:12,left:10},h:32});H.caps(hd,APP,'Settings');H.order(hd);
CATS.forEach(function(c){var sel=cat===c[0];var row=F({name:'link:settings-'+c[0],parent:nav,dir:'row',gap:10,pad:{top:0,right:10,bottom:0,left:10},w:220,h:32,radius:8,fill:sel?H.alpha(H.hex(APP,'ink'),0.05):null});H.sfg(row,c[2],{size:16,w:20,color:H.sw(APP,sel?'ink':'secondary')});T(row,c[1],{weight:sel?6:5,color:H.sw(APP,sel?'ink':'secondary')});H.order(row);});H.order(nav);
F({name:'settings-detail',parent:split,dir:'col',gap:24,pad:0,w:824,h:792});H.order(split);w.finish();s.frame.x=IDS.indexOf(ID)*1560;s.frame.y=2120;console.log(JSON.stringify({id:ID,app:APP,frame:s.id,phase:phase}));return;}
if(!s)throw new Error('Missing '+name);
var detail=s.layers.find(function(l){return l.name==='content-col';}).layers.find(function(l){return l.name==='main';}).layers.find(function(l){return l.name==='settings-split';}).layers.find(function(l){return l.name==='settings-detail';});
function group(title,rows,footer){var sec=F({name:'section:'+title,parent:detail,dir:'col',gap:8,pad:0,w:824});H.caps(sec,APP,title);var g=F({name:'group:'+title,parent:sec,dir:'col',gap:0,pad:4,w:824,radius:12,fill:H.sw(APP,'panel')});rows.forEach(function(r){var row=F({name:'form:'+r[0],parent:g,dir:'row',gap:16,pad:{top:0,right:12,bottom:0,left:12},w:816,h:36});T(row,r[0]);space(row);var cp=F({name:'control',parent:row,dir:'row',gap:8,pad:0,h:28});control(cp,r);H.order(row);if(r[3]&&(r[2]==='toggle'||r[2]==='popup')){var help=F({name:'helper',parent:g,pad:{top:0,right:12,bottom:8,left:12},w:816});T(help,r[3],{size:12,color:H.sw(APP,'tertiary'),w:792});H.order(help);}});H.order(g);if(footer)T(sec,footer,{size:12,color:H.sw(APP,'tertiary'),w:824});H.order(sec);}
if(phase==='detail'){detail.layers.slice().forEach(function(l){l.remove();});var hd=F({name:'detail-heading',parent:detail,dir:'col',gap:8,pad:0,w:824});T(hd,meta[1],{size:15,weight:6});T(hd,{account:'Your identity, workspace and signed-in devices.',devices:'Manage the Macs and iPhone connected to your account.',general:'Make Weave work the way you do.',appearance:'Choose how Weave looks on this Mac.',voice:'Natural conversations, on your terms.',notifications:'Choose when Weave asks for your attention.',connections:'Bring your tools into the conversation.',billing:'Your plan and usage, all in one place.',privacy:'You control your conversations and your data.',shortcuts:'Keep your hands on the keyboard.',about:'A thoughtful workspace for working with AI.'}[cat],{size:12,color:H.sw(APP,'tertiary')});H.order(hd);
// CONTENT
H.order(detail);detail.parent.stackLayout.apply();s.frame.x=IDS.indexOf(ID)*1560;s.frame.y=2120;
}
if(phase==='overlay'){H.macScrim(s,APP);
if(ID==='settings--sign-out'){var a=H.macAlert(s,APP,{title:'Sign out of this Mac?',body:'Local agents will stop and this Mac will be disconnected. Your conversations and files stay in your account.',glyph:'person',w:360,buttons:[['back','Cancel','secondary'],['signin','Sign out','primary']]});a.style.borders=[];a.style.fills=[{color:H.sw(APP,'panel')}];a.layers.forEach(function(l){if(l.name==='icon'){l.style.fills=[];l.frame.width=32;l.frame.height=32;l.layers.forEach(function(g){g.style.fontSize=24;});}if(l.type==='Text'&&l.style.fontSize===11)l.style.fontSize=12;if(l.name==='buttons')l.layers.forEach(function(b){b.style.borders=[];b.style.shadows=[];b.style.fills=[{color:H.sw(APP,b.name==='link:signin'?'ink':'hover')}];b.layers.forEach(function(t){t.style.textColor=H.sw(APP,b.name==='link:signin'?'surface':'ink');});b.style.corners.radii=[999,999,999,999];});});a.stackLayout.apply();}
else{var sh=F({name:'plan-sheet',parent:s,dir:'col',gap:24,pad:24,w:560,radius:16,fill:H.sw(APP,'panel'),shadow:{color:'#00000040',blur:32,x:0,y:16,spread:0}});T(sh,'Change plan',{size:15,weight:6});T(sh,'Room for your next idea, or your whole team.',{size:12,color:H.sw(APP,'tertiary')});[['Free','S$0 / month','50,000 tokens · 1 device'],['Pro','S$32 / month','500,000 tokens · 5 devices · Renews 14 Oct 2026'],['Team','S$96 / month','2 million tokens · Shared workspace']].forEach(function(p,i){var r=F({name:'link:settings-billing',parent:sh,dir:'row',gap:12,pad:0,w:512,h:64});var tx=F({name:'plan-copy',parent:r,dir:'col',gap:6,pad:0});T(tx,p[0],{weight:6});T(tx,p[2],{size:12,color:H.sw(APP,'tertiary'),w:320});H.order(tx);space(r);T(r,p[1]);var ck=F({name:'selection',parent:r,pad:0,w:16,h:16});if(i===1)H.sfg(ck,'checkmark_circle_fill',{size:16,color:H.sw(APP,'accent')});H.order(ck);H.order(r);});T(sh,'Prices in Singapore dollars. Changes apply at your next renewal.',{size:12,color:H.sw(APP,'tertiary'),w:512});var acts=F({name:'sheet-actions',parent:sh,pad:0,gap:8,w:512,h:28});space(acts);button(acts,'Cancel','back');button(acts,'Done','settings-billing','primary');H.order(acts);H.order(sh);sh.frame.x=568;sh.frame.y=52;sh.moveToFront();}}
function clean(l){if(l.name&&l.name.indexOf('link:')===0)l.name=l.name.replace(/ \d+$/,'');(l.layers||[]).forEach(clean);}clean(s);
console.log(JSON.stringify({id:ID,app:APP,frame:s.id,phase:phase}));
}
