from pathlib import Path
p=Path('/tmp/harso-sk/lanes/fix-ai-chat')
s=Path('/tmp/harso-sk/lanes/ai-chat/components.js').read_text()
s=s.replace("var c=box(b,'file details',null,null,null,0,'col',4);txt(c,", "var c=box(b,'file details',176,null,null,{top:3,bottom:3,left:3,right:3},'col',6);txt(c,")
s=s.replace("'requirements.md',13);txt(c,", "'requirements.md',13,'ink',170);txt(c,")
s=s.replace("'Markdown · 4 KB',12,'tertiary');", "'Markdown · 4 KB',12,'tertiary',170);")
s=s.replace("c=box(r,'step track',16,null,null,0,'col',4);", "c=box(r,'step track',16,null,null,0,'col',4);c.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;")
s=s.replace("ico(r,i===0?'circleCheck':s==='checkbox'?'square':'circle',i===0?'accent':'tertiary');", "ico(r,i===0?(s==='checkbox'?'<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"3\"/><path d=\"m7 12 3 3 7-7\"/>':'<circle cx=\"12\" cy=\"12\" r=\"9\"/><circle cx=\"12\" cy=\"12\" r=\"4\" fill=\"'+H.hex(APP,'accent')+'\" stroke=\"none\"/>'):(s==='checkbox'?'square':'circle'),i===0?'accent':'tertiary');")
a=s.index("var svg='<circle",s.index("case 'Context'"));b=s.index("txt(r,'32k",a)
s=s[:a]+"var angle=2*Math.PI*0.16;var ex=16+12*Math.sin(angle),ey=16-12*Math.cos(angle);var svg='<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" viewBox=\"0 0 32 32\"><circle cx=\"16\" cy=\"16\" r=\"12\" fill=\"none\" stroke=\"'+H.hex(APP,'line-strong')+'\" stroke-width=\"3\"/><path d=\"M16 4 A12 12 0 0 1 '+ex+' '+ey+'\" fill=\"none\" stroke=\"'+H.hex(APP,'accent-mark')+'\" stroke-width=\"3\"/></svg>';var ring=sketch.createLayerFromData(svg,'svg');ring.parent=r;ring.name='usage ring 16 percent';"+s[b:]
a=s.index("case 'Task':");b=s.index("case 'ChainOfThought':",a)
s=s[:a]+'''case 'Task': ['running','completed'].forEach(function(s){b=spec(sh,fam,s,640,'surface','line');r=row(b,608);txt(r,'Shape the launch brief',16,'ink',360,6);chip(r,s==='running'?'2 working · 1 decision':'Complete',s==='running'?'accent':'positive');ico(r,'chevronDown');[['Shaping the recommendation','Writing agent'],['Checking the evidence','Research agent'],['Six sources reviewed','']].forEach(function(v,i){r=row(b,608,12);ico(r,s==='completed'||i===2?'circleCheck':'loader',s==='completed'||i===2?'positive':'accent');c=box(r,'task detail',420,null,null,0,'col',4);txt(c,v[0],14,'ink',420,6);if(v[1])txt(c,v[1],12,'secondary',420);chip(r,s==='completed'||i===2?'Reviewed':'Working',s==='completed'||i===2?'positive':'secondary');});line(b,608);r=row(b,608);ico(r,'file');txt(r,'launch-brief.md',13,'ink',440,6,true);chip(r,'Draft','secondary');txt(b,'Task notes',13,'secondary',608,6);c=box(b,'task notes field',608,'canvas','line',12,'col',4,8,72);txt(c,'',13,'tertiary',580);line(b,608);txt(b,s==='running'?'A decision is needed before the final step.':'The final step is complete.',13,'secondary',608);r=row(b);btn(r,s==='running'?'Review decision':'Decision reviewed',true,'check');});break;
case 'Plan': ['expanded','collapsed'].forEach(function(s){b=spec(sh,fam,s,640,'surface','line');r=row(b,608);txt(r,'Start smaller.',20,'ink',420,6);chip(r,'Draft plan','secondary');txt(b,'One audience. One excellent first experience.',13,'secondary',608);r=row(b,608);txt(r,'Plan details',14,'ink',576,6);ico(r,s==='expanded'?'chevronDown':'chevronRight');if(s==='expanded'){line(b,608);r=row(b,608);txt(r,'Three considered steps',14,'ink',576,6);ico(r,'chevronDown');['Understand the strongest need.','Shape one useful workflow.','Test it with a small group.'].forEach(function(v,i){r=row(b,608);chip(r,String(i+1),i===0?'positive':i===1?'accent':'tertiary');txt(r,v,14,'ink',440);chip(r,['Complete','Working','Waiting'][i],i===0?'positive':i===1?'accent':'secondary');});}txt(b,'Notes on the plan',13,'secondary',608,6);c=box(b,'plan notes field',608,'canvas','line',12,'col',4,8,72);txt(c,'Keep your own thoughts here…',13,'tertiary',580);txt(b,'A quick choice · Who are we speaking to?',13,'secondary',608);r=row(b);btn(r,'Our team',false,'user');btn(r,'Everyone',false,'user');});break;
'''+s[b:]
s=s.replace("var y=0;page.layers.forEach(function(l){if(l.name.endsWith(' — '+APP))y=Math.max(y,l.frame.y+l.frame.height+80);});\nif(page.layers.some(function(l){return l.name===FAMILY+' — '+APP;}))throw Error('Sheet already exists; patch by ID');", "var old=page.layers.find(function(l){return l.name===FAMILY+' — '+APP;});if(!old)throw Error('Missing original sheet');var y=old.frame.y;x=old.frame.x;H.dropSheet('AI Chat',FAMILY+' — '+APP);")
# preserve actual thumbnail illustration rather than regress to a glyph
s=s.replace("ico(t,'image','accent',24);", "t.stackLayout.padding=0;var image=sketch.createLayerFromData('<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"40\" height=\"40\" viewBox=\"0 0 600 400\"><rect width=\"600\" height=\"400\" fill=\"#dbe4df\"/><circle cx=\"430\" cy=\"110\" r=\"65\" fill=\"#faf6e9\"/><path d=\"M0 260 Q160 120 300 260 T600 200 V400 H0Z\" fill=\"#748b83\"/><path d=\"M0 360 Q230 220 600 360 V400 H0Z\" fill=\"#415b54\"/></svg>','svg');image.parent=t;image.frame.width=40;image.frame.height=40;")
# Two attachment cards still fit 640 after explicit text bounds.
s=s.replace("var c=box(b,'file details',176", "var c=box(b,'file details',160").replace("'ink',170);txt(c,", "'ink',154);txt(c,").replace("'tertiary',170);", "'tertiary',154);")
p.joinpath('components.js').write_text(s)
