var APP = 'Light/Clean';
var FAMILY = 'Agent';
var baseFrame=H.frame;H.frame=function(o){var f=baseFrame(o);if(o.align!==undefined)f.stackLayout.alignItems=o.align;return f;};
var realOrder=H.order; H.order=function(f){return f;};
var page=H.page('AI Code');
var apps=['Light/Clean','Light/Cozy','Dark/Clean','Dark/Cozy'];
var oldSheet=page.layers.find(function(l){return l.name===FAMILY+' — '+APP;});if(!oldSheet)throw new Error('Missing original sheet');var y=oldSheet.frame.y;H.dropSheet(page.name,FAMILY+' — '+APP);
var sh=H.sheet({name:FAMILY+' — '+APP,parent:page,x:apps.indexOf(APP)*1600,y:y,fill:H.sw(APP,'canvas-deep')});
function txt(p,t,role,size,w,mono){return H.text({parent:p,text:t,color:H.sw(APP,role||'ink'),size:size||14,w:w,mono:mono});}
function row(p,w,fill,pad,h){return H.frame({name:'row',parent:p,dir:'row',gap:10,w:w,pad:pad===undefined?0:pad,h:h,fill:fill?H.sw(APP,fill):null,radius:6});}
function col(p,w,pad,fill,gap){return H.frame({name:'content',parent:p,dir:'col',gap:gap===undefined?12:gap,w:w,pad:pad||0,fill:fill?H.sw(APP,fill):null,align:sketch.StackLayout.AlignItems.Start});}
function ic(p,n,role){H.icon({parent:p,d:H.paths[n]||H.paths.code,color:H.hex(APP,role||'secondary'),size:16});}
function spacer(p){var s=H.frame({name:'spacer',parent:p,h:1});s.horizontalSizing=sketch.FlexSizing.Fill;}
function chip(p,t,role){var c=H.frame({name:'chip',parent:p,pad:{top:4,right:8,bottom:4,left:8},fill:H.sw(APP,'hover'),radius:999,gap:5});txt(c,t,role||'secondary',12);H.order(c);return c;}
function button(p,t,n,primary){var b=H.frame({name:'action',parent:p,h:28,pad:{top:4,right:8,bottom:4,left:8},radius:8,fill:H.sw(APP,primary?'ink':'surface'),border:H.sw(APP,'line'),gap:6});if(n)ic(b,n,primary?'inverse':'secondary');if(t)txt(b,t,primary?'inverse':'ink',12);H.order(b);return b;}
function title(p,t,n,status,role){var r=row(p,688);if(n)ic(r,n);H.text({parent:r,text:t,size:14,weight:6,color:H.sw(APP,'ink')});spacer(r);if(status)chip(r,status,role);H.order(r);return r;}
function line(p){var r=row(p,688,null,{top:0,right:0,bottom:0,left:24});H.rect({parent:r,w:664,h:1,fill:H.sw(APP,'line')});H.order(r);}
function mono(p,t,role){return txt(p,t,role,13,undefined,true);}
function tabs(p,a,active){var r=row(p,688);a.forEach(function(t){var b=row(r,undefined,t===active?'hover':null,{top:6,right:12,bottom:6,left:12},32);txt(b,t,t===active?'ink':'secondary',13);H.order(b);});H.order(r);}
function code(p,lines,diff){lines.forEach(function(t,i){var role=t[0]==='+'?'positive':t[0]==='-'?'negative':'ink';var r=row(p,688,(diff&&role!=='ink')?'hover':i===0?'accent-soft':null,8,32);txt(r,String(i+1),'tertiary',13,24,true);mono(r,t,role);H.order(r);});}
function preview(p,web){var b=col(p,688,24,'canvas',12);chip(b,web?'LOCAL PREVIEW':'✓ RESEARCH COMPLETE',web?'secondary':'positive');H.text({parent:b,text:web?'A quiet place to work.':'A clearer view of the evidence',size:24,weight:6,color:H.sw(APP,'ink'),w:640});txt(b,web?'This is a local, isolated preview. No external site is loaded until you enter an address and choose Open.':'Three firsthand sources reviewed. Key findings and open questions are ready for your next decision.','secondary',14,640);if(!web)mono(b,'3 sources · 2 open questions','tertiary');H.order(b);}
function card(variant,state){txt(sh,variant+(state?' · '+state:''),'tertiary',12);return H.frame({name:FAMILY+'/'+APP+'/'+variant+(state?'/'+state:''),parent:sh,dir:'col',w:720,pad:16,gap:12,fill:H.sw(APP,'surface'),border:H.sw(APP,'line'),radius:12,align:sketch.StackLayout.AlignItems.Start});}
H.text({parent:sh,text:FAMILY+' — '+APP,size:20,weight:6,color:H.sw(APP,'ink')});
var c,r,b;
if(FAMILY==='Agent'){
 ['ready','running'].forEach(function(st){c=card('research',st);r=row(c,688);b=H.frame({name:'avatar',parent:r,w:36,h:36,pad:10,fill:H.sw(APP,'accent-soft'),radius:8});ic(b,'sparkles','accent');H.order(b);H.text({parent:r,text:'Your research partner',size:16,weight:6,color:H.sw(APP,'ink')});spacer(r);chip(r,st==='running'?'Working':'Ready',st==='running'?'attention':'positive');H.order(r);txt(c,'Host-selected model · Research assistant','secondary',13);txt(c,'INSTRUCTIONS','tertiary',12);txt(c,'Start with the question, not an answer.','ink',14);txt(c,'• Prefer firsthand evidence.\n• Keep uncertainty visible.\n• Ask before taking consequential action.','secondary',14,688);['search_evidence','summarize_findings'].forEach(function(t,i){r=row(c,688,'canvas',10,48);ic(r,i?'layers':'search');var co=col(r,580,0,null,2);mono(co,t);txt(co,i?'Bring the useful parts together':'Find sources worth reading','secondary',12);H.order(co);ic(r,'chevronRight');H.order(r);});txt(c,'OUTPUT SCHEMA','tertiary',12);mono(c,'{ "summary": "string", "sources": ["source-id"],\n  "uncertainties": ["string"] }');r=row(c,688);button(r,st==='running'?'Pause':'Run agent',st==='running'?'pause':'play',true);button(r,'Configure','settings');H.order(r);H.order(c);});
}
if(FAMILY==='Artifact'){
 ['preview','code'].forEach(function(st){c=card('document',st);r=title(c,'A quieter place to think','file');button(r,'','copy');button(r,'','download');button(r,'','maximize');H.order(r);txt(c,'Research brief · Synthetic example','secondary',13);tabs(c,['Preview','Code'],st==='preview'?'Preview':'Code');line(c);if(st==='preview'){txt(c,'The best workspace leaves room for the work.','ink',16);txt(c,'What stood out','ink',14);txt(c,'People want to see what matters now, with the detail one deliberate step away. Progress stays visible without taking over the conversation.','secondary',14,688);txt(c,'The next small step','ink',14);txt(c,'Try the calmer flow with one real task. Keep the decisions visible, and let the rest recede.','secondary',14,688);}else code(c,['# A quieter place to think','','The best workspace leaves room for the work.'],false);H.order(c);});
}
if(FAMILY==='CodeBlock'){
 ['default','diff'].forEach(function(st){c=card(st,'ready');r=title(c,'work-unit.ts','code','typescript');button(r,'Copy','copy');H.order(r);code(c,st==='diff'?['- const result = "Pending";','+ const result: string = "Work complete";','','  console.log(result);']:['const result: string = "Work complete";','','console.log(result);',''],st==='diff');H.order(c);});
}
if(FAMILY==='Commit'){
 ['collapsed','expanded'].forEach(function(st){c=card('default',st);r=row(c,688);b=H.frame({name:'avatar',parent:r,w:32,h:32,pad:6,radius:999,fill:H.sw(APP,'hover')});txt(b,'AB','secondary',12);H.order(b);var co=col(r,578,0,null,6);txt(co,'Keep work progress clear and quiet','ink',14);mono(co,'a71b9028 · Alex Bennett · 2 hours ago','secondary');H.order(co);button(r,'','copy');H.order(r);r=row(c,688);ic(r,st==='expanded'?'chevronDown':'chevronRight');txt(r,'4 changed files','secondary',13);spacer(r);txt(r,'+84','positive',13);txt(r,'−12','negative',13);H.order(r);if(st==='expanded')['src/conversation.tsx','src/components/progress.tsx','src/work.ts','README.md'].forEach(function(t){r=row(c,688,null,8,32);ic(r,'file');mono(r,t);H.order(r);});H.order(c);});
}
if(FAMILY==='EnvironmentVariables'){
 ['masked','hover-revealed'].forEach(function(st){c=card('table',st);r=title(c,'Workspace configuration','settings');button(r,'Show values','eye');H.order(r);r=row(c,688);txt(r,'KEY','tertiary',12,340);txt(r,'VALUE','tertiary',12);H.order(r);['SAMPLE_TOKEN','SAMPLE_REGION','SAMPLE_OPTIONAL'].forEach(function(t,i){line(c);r=row(c,688,st==='hover-revealed'&&i===1?'hover':null,8,40);txt(r,t,'ink',13,330,true);txt(r,st==='hover-revealed'?['sample-token','us-east-1','Not supplied'][i]:'••••••••','secondary',13,220,true);ic(r,'eye');if(st==='hover-revealed'&&i===1)button(r,'','copy');H.order(r);});r=row(c,688);button(r,'Add variable','plus');H.order(r);txt(c,'Synthetic values only. Nothing is read from your environment.','tertiary',12);H.order(c);});
}
if(FAMILY==='FileTree'){
 c=card('default','selected');title(c,'Workspace files','folder');[['src',0,'folder',true],['conversation.tsx',1,'code',false],['components',1,'folder',true],['progress.tsx',2,'code',false],['empty',1,'folder',false],['README.md',1,'file',false],['Unavailable example',1,'file',false]].forEach(function(a,i){r=row(c,688,i===1?'hover':null,{top:6,right:12,bottom:6,left:12+a[1]*24},36);if(a[2]==='folder')ic(r,a[3]?'chevronDown':'chevronRight');else H.rect({parent:r,w:16,h:1});ic(r,a[2]);txt(r,a[0],i===6?'tertiary':'ink',14);spacer(r);if(i===1||i===3){H.rect({parent:r,w:6,h:6,oval:true,fill:H.sw(APP,i===1?'attention-mark':'positive-mark')});txt(r,i===1?'M':'A',i===1?'attention':'positive',12);}H.order(r);});H.order(c);
}
if(FAMILY==='JsxPreview'){
 c=card('rendered','desktop');r=title(c,'Rendered result','code');button(r,'Desktop','square');button(r,'Mobile','panelLeft');button(r,'','maximize');H.order(r);preview(c,false);H.order(c);
}
if(FAMILY==='PackageInfo'){
 c=card('npm','minor');r=title(c,'@sample/workspace','box','2.2.0');chip(r,'Minor','attention');H.order(r);mono(c,'2.1.0 → 2.2.0','secondary');txt(c,'Small improvements to how observations come together. This is supplied sample data, not an available update.','secondary',14,688);r=row(c,688,'canvas',12,48);mono(r,'npm install @sample/workspace');spacer(r);button(r,'Copy','copy');H.order(r);txt(c,'Dependencies','ink',14);[['@sample/observations','1.4.0'],['@sample/context','0.8.2'],['@sample/optional-export','Version not supplied']].forEach(function(a){line(c);r=row(c,688);mono(r,a[0]);spacer(r);mono(r,a[1],'secondary');H.order(r);});r=row(c,688);chip(r,'3 dependencies');chip(r,'npm');chip(r,'Sample data');H.order(r);H.order(c);
}
if(FAMILY==='Sandbox'){
 ['running','completed'].forEach(function(st){c=card('workspace',st);r=title(c,'work.tsx','chevronDown',st==='running'?'● Running':'● Completed',st==='running'?'attention':'positive');if(st==='running')button(r,'Stop','square');H.order(r);tabs(c,['Code','Output','Console','Network'],st==='running'?'Console':'Code');code(c,st==='running'?['$ npm run dev','> Workspace ready on localhost:3000','  Watching for file changes…']:['const result = await work();'],false);H.order(c);});
}
if(FAMILY==='SchemaDisplay'){
 ['collapsed','expanded'].forEach(function(st){c=card('endpoint',st);r=row(c,688);chip(r,'GET','positive');mono(r,'/work/{id}');H.order(r);['Parameters','Response body'].forEach(function(t,i){line(c);r=row(c,688,null,8,36);ic(r,st==='expanded'?'chevronDown':'chevronRight');txt(r,t,'ink',14);if(!i)chip(r,'1');H.order(r);if(st==='expanded'){r=row(c,688,'canvas',12,40);mono(r,i?'status':'id');chip(r,'string','accent');if(!i){H.rect({parent:r,w:6,h:6,oval:true,fill:H.sw(APP,'negative-mark')});txt(r,'Required','secondary',12);}H.order(r);txt(c,i?'Current state of the work.':'Unique work identifier · path parameter','secondary',13);}});H.order(c);});
}
if(FAMILY==='Snippet'){
 ['default','copied'].forEach(function(st){c=card('command',st);r=row(c,688);mono(r,'$','tertiary');mono(r,'example status');spacer(r);button(r,st==='copied'?'Copied':'Copy',st==='copied'?'check':'copy');H.order(r);H.order(c);});
}
if(FAMILY==='StackTrace'){
 ['collapsed','expanded'].forEach(function(st){c=card('error',st);r=title(c,'TypeError','alert');r.layers.filter(function(t){return t.type==='Text'&&t.text==='TypeError'}).forEach(function(t){t.style.textColor=H.sw(APP,'negative')});txt(r,'Stack frames','secondary',13);ic(r,st==='expanded'?'chevronDown':'chevronRight');H.order(r);txt(c,'Cannot read the work result','negative',16);if(st==='expanded'){[['readWorkResult','src/work.ts:42:18'],['renderWorkspace','src/conversation.tsx:86:9'],['handleRequest','src/api/work.ts:21:5']].forEach(function(a){line(c);r=row(c,688,null,8,40);ic(r,'chevronRight');mono(r,a[0]);spacer(r);mono(r,a[1],'secondary');H.order(r);});r=row(c,688);button(r,'Show 12 more','chevronDown');H.order(r);}H.order(c);});
}
if(FAMILY==='Terminal'){
 ['ready','running','error'].forEach(function(st){c=card('build-log',st);r=title(c,'Build log','terminal',st==='ready'?'Exit 0':st==='error'?'Exit 1':'Running',st==='error'?'negative':st==='ready'?'positive':'attention');button(r,'Clear','trash');H.order(r);b=H.frame({name:'console',parent:c,dir:'col',w:688,pad:16,gap:12,fill:H.sw('Dark/Clean','canvas-deep'),radius:8,align:sketch.StackLayout.AlignItems.Start});['$ npm run build',st==='error'?'error Cannot read the work result':'✓ build complete',st==='running'?'info watching for changes…':'info ready'].forEach(function(t){H.text({parent:b,text:t,mono:true,size:13,color:H.sw('Dark/Clean',t.startsWith('error')?'negative':'ink')});});if(st==='running'){r=row(b,656);H.icon({parent:r,d:H.paths.loader,color:H.hex('Dark/Clean','attention')});H.rect({parent:r,w:8,h:16,fill:H.sw('Dark/Clean','ink')});H.order(r);}H.order(b);H.order(c);});
}
if(FAMILY==='TestResults'){
 ['collapsed','expanded'].forEach(function(st){c=card('suite',st);r=row(c,688);ic(r,'circleCheck','positive');txt(r,'3 passed','positive',13);ic(r,'circleX','negative');txt(r,'1 failed','negative',13);txt(r,'Skipped 1','secondary',13);txt(r,'5 total','secondary',13);spacer(r);txt(r,'1.25s','tertiary',13);H.order(r);r=row(c,688);H.rect({parent:r,w:400,h:4,fill:H.sw(APP,'positive-mark'),radius:2});H.rect({parent:r,w:124,h:4,fill:H.sw(APP,'negative-mark'),radius:2});H.rect({parent:r,w:144,h:4,fill:H.sw(APP,'faint'),radius:2});H.order(r);r=title(c,'API suite',st==='expanded'?'chevronDown':'chevronRight');txt(c,'3 passed   1 failed   1 skipped','secondary',13);if(st==='expanded'){['reads workspace','lists observations','updates context','returns work result','exports optional report'].forEach(function(t,i){r=row(c,688,null,8,36);ic(r,i===3?'circleX':i===4?'minus':'check',i===3?'negative':i===4?'tertiary':'positive');txt(r,t,'ink',14);spacer(r);mono(r,['180ms','260ms','210ms','600ms','—'][i],'tertiary');H.order(r);});}H.order(c);});
}
if(FAMILY==='WebPreview'){
 ['default','console-open'].forEach(function(st){c=card('browser',st);r=row(c,688);button(r,'','arrowLeft');button(r,'','arrowRight');button(r,'','refresh');var u=row(r,400,'canvas',8,36);ic(u,'lock');txt(u,'https://example.com','secondary',13);H.order(u);button(r,'Open','maximize');H.order(r);tabs(c,['Desktop','Tablet','Mobile'],'Desktop');preview(c,true);r=row(c,688);ic(r,st==='console-open'?'chevronDown':'chevronRight');txt(r,'Console','secondary',13);spacer(r);chip(r,'0 errors','positive');H.order(r);if(st==='console-open'){b=col(c,688,12,'canvas',8);mono(b,'info Local preview ready','secondary');mono(b,'>','tertiary');H.order(b);}H.order(c);});
}
// Ordering once at every structural level; promotion only once after layout.
function orderTree(f){(f.layers||[]).forEach(function(k){if(k.layers)orderTree(k)});if(f.stackLayout)realOrder(f);}
orderTree(sh);H.relayout(sh);
var made=H.symbolize(sh,new RegExp('^'+FAMILY+'/'));
H.relayout(sh);sh.frame.x=apps.indexOf(APP)*1600;sh.frame.y=y;H.out({family:FAMILY,app:APP,sheet:String(sh.id),made:made,h:Math.round(sh.frame.height),w:Math.round(sh.frame.width),x:sh.frame.x,y:sh.frame.y});
