import { useRef, useState } from "react";
import { AiChat, Button, Checkbox, CodeBlock, Composer, Conversation, ConversationContent, ConversationEmptyState, ConversationScrollButton, FileTree, FileTreeFile, FileTreeFolder, Message, MessageActionButton, MessageActions, MessageContent, MessageResponse, PromptInputActionAddAttachments, PromptInputFooter, PromptInputSubmit, PromptInputTextarea, Select, WebPreview, WebPreviewBody } from "@harso/ui";
import type { ExampleState } from "./examples";

type ChatMessage = { id: string; role: "user" | "assistant"; text: string };
const initial: Record<string, ChatMessage[]> = {
  landing: [{ id: "request", role: "user", text: "Create a calm landing page for our studio." }, { id: "response", role: "assistant", text: "I’ve prepared a minimal page with clear typography and generous spacing. You can inspect the proposed **Changes** or open the **Browser** preview." }],
  tests: [{ id: "tests", role: "assistant", text: "The host has not started this task. No test results are available yet." }],
};
const code = "export function Welcome() {\n  return <main>\n    <h1>A little space to create.</h1>\n  </main>;\n}";
export function AiChatExample({ state }: { state: ExampleState }) {
  const [chat, setChat] = useState("landing");
  const [messages, setMessages] = useState(initial);
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const [attachments, setAttachments] = useState<Record<string, string[]>>({});
  const [panel, setPanel] = useState<"changes" | "browser" | null>(null);
  const [scenario, setScenario] = useState("ready");
  const [running, setRunning] = useState<Set<string>>(() => new Set());
  const [model, setModel] = useState("host-default");
  const [hold, setHold] = useState(false);
  const [feedback, setFeedback] = useState<Record<string, string>>({});
  const [selectedPath, setSelectedPath] = useState<string | null>(null);
  const [request, setRequest] = useState("Synthetic workspace. No repository, model or runtime connected.");
  const sequence = useRef(0);
  const disabled = state === "disabled" || scenario === "disabled";
  const loading = scenario === "loading";
  const error = state === "error" || scenario === "error";
  const busy = running.has(chat);
  const mutate = (label: string, action: () => void) => { if (disabled) return; setRequest(`${label}${hold ? "; host retained state" : ""}.`); if (!hold) action(); };
  const selectChat = (next: string) => mutate(`Open ${next}`, () => { setChat(next); setPanel(null); setSelectedPath(null); });
  const send = (text: string) => {
    if (disabled || loading || error || busy || !text.trim()) return;
    mutate("Send requested", () => { const id = `message-${++sequence.current}`; setMessages(current => ({ ...current, [chat]: [...(current[chat] ?? []), { id, role: "user", text }, { id: `${id}-reply`, role: "assistant", text: "Synthetic host update: preparing the response…" }] })); setDrafts(current => ({ ...current, [chat]: "" })); setAttachments(current => ({ ...current, [chat]: [] })); setRunning(current => new Set([...current, chat])); setScenario("ready"); });
  };
  const transcript = scenario === "empty" ? [] : messages[chat] ?? [];
  return <div className="hkl-example-stack" style={{ maxWidth: "none" }}><div className="hk-data-toolbar">
    <label>Chat state<Select aria-label="Chat state" value={scenario} onChange={event => setScenario(event.target.value)}>{["ready", "empty", "loading", "error", "disabled"].map(value => <option key={value}>{value}</option>)}</Select></label>
    <Checkbox label="Hold host state" checked={hold} onChange={event => setHold(event.target.checked)} />
    {busy && <Button disabled={disabled} onClick={() => mutate("Synthetic update advanced", () => { setMessages(current => ({ ...current, [chat]: current[chat].map((message, index) => index === current[chat].length - 1 ? { ...message, text: "Synthetic host result: the proposed update is ready for inspection. No files were written." } : message) })); setRunning(current => new Set([...current].filter(id => id !== chat))); })}>Advance synthetic update</Button>}
  </div>
    <AiChat title={chat === "landing" ? "Studio landing page" : "Test planning"} status={<span className="hk-ai-example-status">{busy ? "Running · synthetic" : "Local example"}</span>}
      navigation={<><Button disabled={disabled} onClick={() => mutate("New conversation requested", () => { const id = `chat-${++sequence.current}`; setMessages(current => ({ ...current, [id]: [] })); setChat(id); setPanel(null); })}>New conversation</Button><h3>Repositories</h3><FileTree disabled={disabled} selectedPath={selectedPath} defaultExpanded={new Set(["studio"])} onSelect={next => mutate(`Inspect ${next}`, () => { setSelectedPath(next); if (next.endsWith(".tsx")) setPanel("changes"); })}><FileTreeFolder path="studio" name="studio"><FileTreeFile path="studio/Welcome.tsx" name="Welcome.tsx" /></FileTreeFolder></FileTree><h3>Recent conversations</h3>{Object.keys(messages).map(id => <Button key={id} disabled={disabled} aria-current={chat === id ? "page" : undefined} onClick={() => selectChat(id)}>{id === "landing" ? "Studio landing page" : id === "tests" ? "Test planning" : "New conversation"}</Button>)}</>}
      actions={<><Button disabled={disabled} onClick={() => mutate("Changes opened", () => setPanel("changes"))}>Changes</Button><Button disabled={disabled} onClick={() => mutate("Browser opened", () => setPanel("browser"))}>Browser</Button></>}
      panel={panel ? { title: panel === "changes" ? "Proposed changes" : "Browser preview", onClose: () => { setRequest(`Close panel${hold ? "; host retained state" : ""}.`); if (!hold) setPanel(null); }, content: <><div className="hk-data-toolbar"><Button disabled={disabled} aria-pressed={panel === "changes"} onClick={() => mutate("Changes opened", () => setPanel("changes"))}>Changes</Button><Button disabled={disabled} aria-pressed={panel === "browser"} onClick={() => mutate("Browser opened", () => setPanel("browser"))}>Browser</Button></div>{panel === "changes" ? <><p>Welcome.tsx · Proposed, not applied</p><CodeBlock code={code} language="tsx" showLineNumbers disabled={disabled} /></> : <WebPreview><WebPreviewBody title="Synthetic studio preview" sandbox="" srcDoc="<!doctype html><html lang='en'><head><title>Studio preview</title></head><body style='font-family:system-ui;padding:24px'><h1>A little space to create.</h1><p>Static, sandboxed preview. No network or scripts.</p></body></html>" /></WebPreview>}</> } : null}
      composer={<Composer key={chat} value={drafts[chat] ?? ""} onValueChange={text => { if (!disabled) setDrafts(current => ({ ...current, [chat]: text })); }} onSubmit={send}><PromptInputTextarea aria-label="Message" placeholder="What would you like to build?" disabled={disabled || loading || error} />{(attachments[chat] ?? []).map((name, index) => <Button key={`${name}-${index}`} disabled={disabled} aria-label={`Remove attachment ${name}`} onClick={() => mutate("Attachment removed", () => setAttachments(current => ({ ...current, [chat]: current[chat].filter((_, position) => position !== index) })))}>{name} ×</Button>)}<PromptInputFooter><PromptInputActionAddAttachments disabled={disabled || busy} onFiles={files => { if (files && !disabled && !busy) { const names = Array.from(files, file => file.name); mutate("Attachment selected locally", () => setAttachments(current => ({ ...current, [chat]: [...(current[chat] ?? []), ...names] }))); } }} /><Select aria-label="Model" disabled={disabled || busy} value={model} onChange={event => mutate("Model selected", () => setModel(event.target.value))}><option value="host-default">Host default</option><option value="host-fast">Host fast</option></Select>{busy ? <Button disabled={disabled} onClick={() => mutate("Stop requested", () => setRunning(current => new Set([...current].filter(id => id !== chat))))}>Stop</Button> : <PromptInputSubmit disabled={disabled || loading || error || !(drafts[chat] ?? "").trim()} />}</PromptInputFooter></Composer>}
    ><Conversation key={chat}><ConversationContent>{loading ? <p role="status">Loading conversation…</p> : error ? <div role="alert">The host could not load this conversation.<Button disabled={disabled} onClick={() => mutate("Retry requested", () => setScenario("ready"))}>Retry</Button></div> : !transcript.length ? <ConversationEmptyState title="A little space to create." description="Start with a question or a task." /> : transcript.map(message => <Message key={message.id} from={message.role}><MessageContent><MessageResponse streaming={busy && message === transcript[transcript.length - 1]}>{message.text}</MessageResponse></MessageContent><MessageActions><MessageActionButton label="Copy" disabled={disabled} onClick={() => { if (hold) { mutate("Copy requested", () => {}); return; } void navigator.clipboard.writeText(message.text).then(() => setRequest("Message copied."), () => setRequest("Copy failed.")); }} />{message.role === "assistant" ? <><MessageActionButton label="Helpful" disabled={disabled} aria-pressed={feedback[`${chat}:${message.id}`] === "helpful"} onClick={() => mutate("Feedback requested", () => setFeedback(current => ({ ...current, [`${chat}:${message.id}`]: "helpful" })))} /><MessageActionButton label="Not helpful" disabled={disabled} aria-pressed={feedback[`${chat}:${message.id}`] === "unhelpful"} onClick={() => mutate("Feedback requested", () => setFeedback(current => ({ ...current, [`${chat}:${message.id}`]: "unhelpful" })))} /><MessageActionButton label="Retry" disabled={disabled || busy} onClick={() => mutate("Retry requested; synthetic only", () => setRunning(current => new Set([...current, chat])))} /></> : <MessageActionButton label="Edit" disabled={disabled || busy} onClick={() => mutate("Edit requested", () => setDrafts(current => ({ ...current, [chat]: message.text })))} />}</MessageActions></Message>)}</ConversationContent><ConversationScrollButton /></Conversation></AiChat>
    <output aria-label="Workspace request">{request}</output>
  </div>;
}
