import { SelectorsExample } from "./selectors-examples";
import { SpeechInputExample } from "./native-speech-examples";
import { PromptInputExample, QueueExample, SocialButtonExample, ToolbarExample } from "./consumer-readiness-examples";
import { NotificationExample } from "./notification-examples";
import { ComposerExample } from "./composer-example";
import { WebPreviewExample } from "./web-preview-example";
import { QuestionnaireExample } from "./questionnaire-example";
import { SettingsExample } from "./settings-example";
import { PersonaExample } from "./persona-example";
import { AgentLimitsExample } from "./agent-limits-example";
import { AgentProgressExample, AgentThinkingExample } from "./agent-activity-example";
import { ChartModesExample } from "./chart-modes-example";
import { AgentTrailsExample } from "./agent-trails-example";
import { FinanceExample } from "./finance-example";
import { ScatterExample } from "./scatter-example";
import { RingsExample } from "./rings-example";
import { SankeyExample } from "./sankey-example";
import { HeatmapExample } from "./heatmap-example";
import { AiChatExample } from "./ai-chat-example";
import { ChatStarterExample } from "./chat-starter-example";
import { ImageGenerationExample, sampleImage } from "./image-generation-example";
import { AiProfileExample } from "./ai-profile-example";
import { HomeDashboardExample } from "./home-dashboard-example";
import { HrManagementExample } from "./hr-management-example";
import { MarketingDashboardExample } from "./marketing-dashboard-example";
import { MedicalProfileExample } from "./medical-profile-example";
import { SharedChartExample, sharedChartExports } from "./shared-chart-example";
import type { ExampleState } from "./examples";
import { ActivityRingsCard, AgentLimitsCard, AgentProgress, AgentThinking, AiChat, AiImageGeneration, AiProfile, AreaChartCard, AuthCard, AuthMediaCarousel, BarListCard, ChatStarter, Color, ComboChartCard, Composer, ComposerAttachmentStrip, ComposerAttachmentTile, ComposerAttachments, ComposerLoader, ComposerPanel, ComposerStatusTab, ComposerWithAttachments, ContributionsCard, EarningsChartCard, FinanceDashboard, FunnelChartCard, HeatmapChartCard, HomeDashboard, HrManagement, LineChartCard, MarketingDashboard, MedicalProfile, MostActiveDaysCard, Notification, NotificationCenter, OpenIn, OpenInChatGPT, OpenInClaude, OpenInContent, OrdersChartCard, Persona, RadarChartCard, RadialChartCard, RevenueChartCard, Sandbox, SandboxContent, SandboxHeader, SandboxTabContent, SandboxTabs, SandboxTabsBar, SandboxTabsList, SandboxTabsTrigger, SankeyChartCard, ScatterChartCard, SchemaDisplay, SettingsModal, SleepScoreCard, SocialButton, StageBarsCard, StepsCard, TaskList, Typography, WebSearch, JsxPreview } from "@harso/ui";
import { AudioPlayer, AudioPlayerControlBar, AudioPlayerElement, AudioPlayerPlayButton, Canvas, Connection, Controls, Edge, Image, Node, NodeContent, NodeHeader, NodeTitle, Panel, PromptInput, PromptInputSubmit, PromptInputTextarea, Question, QuestionOption, QuestionOptions, QuestionPrompt, Queue, QueueItem, Toolbar, Transcription, WebPreview, WebPreviewBody, WebPreviewNavigation, WebPreviewNavigationButton, WebPreviewUrl } from "@harso/ui";
import { CanvasExample } from "./canvas-example";
import { RadialRadarExample } from "./radial-radar-example";

export const catalogueExports = ["Questionnaire", "ActivityRingsCard", "AgentLimitsCard", "AgentProgress", "AgentThinking", "AiChat", "AiImageGeneration", "AiProfile", "AreaChartCard", "AudioPlayer", "AuthCard", "BarListCard", "Canvas", "ChatStarter", "Color", "ComboChartCard", "Composer", "ComposerAttachments", "ComposerLoader", "ComposerPanel", "Connection", "Controls", "ContributionsCard", "EarningsChartCard", "Edge", "FinanceDashboard", "FunnelChartCard", "HeatmapChartCard", "HomeDashboard", "HrManagement", "Image", "JsxPreview", "LineChartCard", "MarketingDashboard", "MedicalProfile", "MicSelector", "ModelSelector", "MostActiveDaysCard", "Node", "Notification", "NotificationCenter", "OpenInChat", "OpenIn", "OpenInChatGPT", "OpenInClaude", "OpenInContent", "OrdersChartCard", "Panel", "Persona", "PromptInput", "Question", "Queue", "RadarChartCard", "RadialChartCard", "RevenueChartCard", "Sandbox", "SchemaDisplay", "SettingsModal", "SleepScoreCard", "SocialButton", "SpeechInput", "StageBarsCard", "StepsCard", "TaskList", "Toolbar", "Transcription", "Typography", "VoiceSelector", "WebPreview", "WebSearch", "SankeyChartCard", "ScatterChartCard"] as const;
export type CatalogueExport = typeof catalogueExports[number] | string;
const data = [{ label: "Mon", value: 36 }, { label: "Tue", value: 52 }, { label: "Wed", value: 42 }, { label: "Thu", value: 72 }, { label: "Fri", value: 61 }];
const stats = [{ id: "one", label: "Active", value: "24" }, { id: "two", label: "Trend", value: "+18%", trend: "positive" as const }];

export function CatalogueExample({ component, state = "default" }: { component: string; state?: ExampleState }) {
  if (component === "RadarChartCard" || component === "RadialChartCard") return <RadialRadarExample component={component} state={state} />;
  if (["AreaChartCard", "LineChartCard", "ComboChartCard"].includes(component)) return <ChartModesExample component={component} state={state} />;
  if (component === "SettingsModal") return <SettingsExample state={state} />;
  if (component === "TaskList" || component === "WebSearch") return <AgentTrailsExample component={component} state={state} />;
  if (component === "Questionnaire") return <QuestionnaireExample state={state} />;
  if (component === "Notification" || component === "NotificationCenter") return <NotificationExample component={component} state={state} />;
  if (component === "OpenIn" || component === "OpenInChat") return <OpenIn query="Explain this result"><OpenInContent><OpenInChatGPT /><OpenInClaude /></OpenInContent></OpenIn>;
  if (component === "OpenInChatGPT" || component === "OpenInClaude" || component === "OpenInContent") return <OpenIn query="Explain this result"><OpenInContent>{component === "OpenInChatGPT" ? <OpenInChatGPT /> : component === "OpenInClaude" ? <OpenInClaude /> : <OpenInContent>Host-provided destination content</OpenInContent>}</OpenInContent></OpenIn>;
  if (component === "SchemaDisplay") return <SchemaDisplay method="GET" path="/work/{id}" parameters={[{ name: "id", type: "string", required: true, location: "path" }]} responseBody={[{ name: "status", type: "string" }]} />;
  if (component === "Sandbox") return <Sandbox open><SandboxHeader state="output-available" title="work.tsx" /><SandboxContent><SandboxTabs><SandboxTabsBar><SandboxTabsList><SandboxTabsTrigger value="code">Code</SandboxTabsTrigger><SandboxTabsTrigger value="output">Output</SandboxTabsTrigger></SandboxTabsList></SandboxTabsBar><SandboxTabContent value="code">const result = await work();</SandboxTabContent><SandboxTabContent value="output">Completed.</SandboxTabContent></SandboxTabs></SandboxContent></Sandbox>;
  if (component === "AudioPlayer") return <AudioPlayer><AudioPlayerElement /><AudioPlayerControlBar><AudioPlayerPlayButton /></AudioPlayerControlBar></AudioPlayer>;
  if (component === "Canvas") return <CanvasExample state={state} />;
  if (component === "Connection") return <Connection aria-label="Work connection" fromX={20} fromY={30} toX={180} toY={80} />;
  if (component === "Controls") return <CanvasExample state={state} />;
  if (component === "Edge") return <Edge.Animated sourceX={20} sourceY={30} targetX={180} targetY={80} />;
  if (component === "Image") return <Image alt="Illustrative landscape, a local sample" src={sampleImage(0)} />;
  if (component === "MicSelector") return <SelectorsExample component={component} state={state} />;
  if (component === "ModelSelector") return <SelectorsExample component={component} state={state} />;
  if (component === "Node") return <Node><NodeHeader><NodeTitle>Work unit</NodeTitle></NodeHeader><NodeContent>Live node content</NodeContent></Node>;
  if (component === "Panel") return <Panel position="top-right">Inspector</Panel>;
  if (component === "PromptInput") return <PromptInputExample state={state} />;
  if (component === "Question") return <Question><QuestionPrompt>What should happen next?</QuestionPrompt><QuestionOptions><QuestionOption value="continue">Continue</QuestionOption></QuestionOptions></Question>;
  if (component === "Queue") return <QueueExample state={state} />;
  if (component === "SpeechInput") return <SpeechInputExample disabled={state === "disabled"} />;
  if (component === "Toolbar") return <ToolbarExample state={state} />;
  if (component === "Transcription") return <Transcription segments={[{ text: "Work is progressing.", startSecond: 0, endSecond: 2 }]}>{segment => <span>{segment.text}</span>}</Transcription>;
  if (component === "VoiceSelector") return <SelectorsExample component={component} state={state} />;
  if (component === "WebPreview") return <WebPreviewExample state={state} />;
  if (component === "AgentLimitsCard") return <AgentLimitsExample />;
  if (component === "AgentProgress") return <AgentProgressExample />;
  if (component === "AgentThinking") return <AgentThinkingExample />;
  if (component === "AiChat") return <AiChatExample state={state} />;
  if (component === "AiImageGeneration") return <ImageGenerationExample state={state} />;
  if (component === "AiProfile") return <AiProfileExample state={state} />;
  if (component === "ChatStarter") return <ChatStarterExample state={state} />;
  if (component === "Color") return <Color value="#6b7cff" label="Accent" />;
  if (component === "Typography") return <Typography variant="display">Boundaryless</Typography>;
  if (component === "Persona") return <PersonaExample state={state} />;
  if (component === "SocialButton") return <SocialButtonExample state={state} />;
  if (component === "AuthCard") return <AuthCard title="Continue to Harso" description="Use your workspace identity."><AuthMediaCarousel><div className="hkl-example-stack"><Typography variant="caption">One calm workspace for every work unit.</Typography><label className="hk-field">Workspace name<input className="hk-input" placeholder="Your workspace" /></label></div><Typography variant="caption">A quiet surface for live progress and results.</Typography><Typography variant="caption">Your data stays scoped to your workspace.</Typography></AuthMediaCarousel></AuthCard>;
  if (["Composer", "ComposerAttachments", "ComposerLoader", "ComposerPanel"].includes(component)) return <ComposerExample component={component} state={state} />;
  if (component === "JsxPreview") return <JsxPreview jsx="<Result />" />;
  if (component === "ContributionsCard") return <ContributionsCard items={[{ label: "Mon", value: 4 }, { label: "Tue", value: 8 }]} />;
  if (component === "FinanceDashboard") return <FinanceExample state={state} />;
  if (component === "ScatterChartCard") return <ScatterExample state={state} />;
  if (component === "ActivityRingsCard") return <RingsExample state={state} />;
  if (component === "SankeyChartCard") return <SankeyExample state={state} />;
  if (component === "HeatmapChartCard") return <HeatmapExample state={state} />;
  if (component === "HomeDashboard") return <HomeDashboardExample state={state} />;
  if (component === "HrManagement") return <HrManagementExample state={state} />;
  if (component === "MarketingDashboard") return <MarketingDashboardExample state={state} />;
  if (component === "MedicalProfile") return <MedicalProfileExample state={state} />;
  if (sharedChartExports.includes(component)) return <SharedChartExample component={component} state={state} />;
  const cards = { ActivityRingsCard, AreaChartCard, BarListCard, ComboChartCard, EarningsChartCard, FunnelChartCard, HeatmapChartCard, LineChartCard, MostActiveDaysCard, OrdersChartCard, RadarChartCard, RadialChartCard, RevenueChartCard, SankeyChartCard, ScatterChartCard, SleepScoreCard, StageBarsCard, StepsCard } as Record<string, typeof AreaChartCard>;
  const Card = cards[component];
  return Card ? <Card title={component} value="82%" data={data} /> : <section role="status" aria-label={`${component} example`}>Example not yet wired for this mapped reference.</section>;
}
