import { useRef, useState } from "react";
import { DotsThreeIcon } from "@phosphor-icons/react";
import { AgentThinking, AuthCard, Button, ChatStarter, Checkbox, Composer, Conversation, ConversationContent, ConversationDownload, ConversationEmptyState, Dropdown, DropdownItem, DropdownPopover, DropdownTrigger, Field, Input, Message, MessageActionButton, MessageActions, MessageContent, MessageResponse, PromptInputFooter, PromptInputSubmit, PromptInputTextarea, Select, Snippet, SnippetCopyButton, StatCards, Tooltip, type ChatStarterProps, type ConversationText } from "@harso/ui";
import type { ExampleState } from "./examples";
import { useLocalReadAloud } from "./native-speech-examples";

type Chat = { id: string; title: string; unread: boolean; messages: ConversationText[] };
export function ChatStarterExample({ state }: { state: ExampleState }) {
  const [team, setTeam] = useState("Personal");
  return <>{["Personal", "Studio"].map(workspace => <StarterWorkspace key={workspace} team={workspace} active={team === workspace} onTeamChange={setTeam} state={state} />)}</>;
}
function StarterWorkspace({ team, active, onTeamChange, state }: { team: string; active: boolean; onTeamChange: (team: string) => void; state: ExampleState }) {
  const [view, setView] = useState<ChatStarterProps["view"]>("chat");
  const [chats, setChats] = useState<Chat[]>([{ id: "welcome", title: `${team} welcome`, unread: false, messages: [{ role: "assistant", content: `This is the isolated ${team} example. What would you like to explore?` }] }, { id: "ideas", title: `${team} ideas`, unread: true, messages: [{ role: "assistant", content: "A few ideas are ready for your review." }] }]);
  const [selected, setSelected] = useState("welcome");
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const [running, setRunning] = useState<Set<string>>(() => new Set());
  const [hold, setHold] = useState(false);
  const [scenario, setScenario] = useState("ready");
  const [renaming, setRenaming] = useState<string | null>(null);
  const [name, setName] = useState("");
  const [deleting, setDeleting] = useState<string | null>(null);
  const [exported, setExported] = useState<string | null>(null);
  const [feedback, setFeedback] = useState<Record<string, boolean>>({});
  const [negative, setNegative] = useState<Record<string, boolean>>({});
  const [request, setRequest] = useState("Synthetic only. Team drafts stay isolated in memory until this example closes; nothing is persisted.");
  const sequence = useRef(0);
  const current = chats.find(chat => chat.id === selected);
  const disabled = state === "disabled" || scenario === "disabled";
  const loading = scenario === "loading";
  const error = state === "error" || scenario === "error";
  const busy = running.has(selected);
  const speech = useLocalReadAloud(`${team}:${selected}:${view}:${active}:${scenario}:${busy}`, disabled || !active || loading || error);
  const act = (label: string, change: () => void) => { if (disabled) return; setRequest(`${label}${hold ? "; host retained state" : ""}.`); if (!hold) change(); };
  const open = (id: string) => act("Conversation selected", () => { setSelected(id); setView("chat"); setRenaming(null); setDeleting(null); setExported(null); setChats(previous => previous.map(chat => chat.id === id ? { ...chat, unread: false } : chat)); });
  const finish = (stop: boolean) => { if (!busy || !current) return; act(stop ? "Stop requested" : "Synthetic update advanced", () => { setRunning(previous => new Set([...previous].filter(id => id !== selected))); setChats(previous => previous.map(chat => chat.id === selected ? { ...chat, messages: [...chat.messages, { role: "assistant", content: stop ? "Stopped in this synthetic example." : "Synthetic result: ready for your review. No provider was called." }] } : chat)); }); };
  const advanceChunk = () => {
    if (!busy || !current || loading || error) return;
    act("Local synthetic chunk advanced; no provider called", () => setChats(previous => previous.map(chat => {
      if (chat.id !== selected) return chat;
      const last = chat.messages.at(-1);
      const messages: ConversationText[] = last?.role === "assistant"
        ? [...chat.messages.slice(0, -1), { ...last, content: `${last.content} Local chunk.` }]
        : [...chat.messages, { role: "assistant", content: "Partial synthetic response: Local chunk." }];
      return { ...chat, messages };
    })));
  };
  if (!active) return null;
  const auth = (signup: boolean) => <AuthCard className="hk-starter-auth" title={signup ? "Create an account" : "Welcome back"} description="UI example only. Do not enter real credentials."><form key={signup ? "signup" : "signin"} onSubmit={event => { event.preventDefault(); const form = event.currentTarget; act(signup ? "Sign-up requested; no authentication performed" : "Sign-in requested; no authentication performed", () => form.reset()); }}>
    {signup && <Field label="Name" required>{props => <Input {...props} name="name" required disabled={disabled} autoComplete="off" />}</Field>}
    <Field label="Email" required>{props => <Input {...props} name="email" type="email" required disabled={disabled} autoComplete="off" />}</Field>
    <Field label="Password" required>{props => <Input {...props} name="password" type="password" required minLength={8} disabled={disabled} autoComplete="new-password" />}</Field>
    <Button type="submit" disabled={disabled}>{signup ? "Request sign-up" : "Request sign-in"}</Button><Button disabled={disabled} onClick={() => act("Authentication page selected", () => setView(signup ? "sign-in" : "sign-up"))}>{signup ? "Use existing account" : "Create account"}</Button>
  </form></AuthCard>;
  return <div className="hkl-example-stack" style={{ maxWidth: "none" }}><div className="hk-data-toolbar"><Checkbox label="Hold host state" checked={hold} onChange={event => setHold(event.target.checked)} /><label>Starter state<Select aria-label="Starter state" value={scenario} onChange={event => setScenario(event.target.value)}>{["ready", "empty", "loading", "error", "disabled"].map(value => <option key={value}>{value}</option>)}</Select></label>{busy && <><Button disabled={disabled || loading || error} onClick={advanceChunk}>Advance local chunk (synthetic)</Button><Button disabled={disabled} onClick={() => finish(false)}>Advance synthetic update</Button></>}</div>
    <ChatStarter title={view === "chat" ? current?.title ?? "New conversation" : view === "dashboard" ? "Overview" : "Account"} view={view} disabled={disabled}
      teamMenu={<Dropdown label="Teams" disabled={disabled}><DropdownTrigger>{team} team</DropdownTrigger><DropdownPopover>{["Personal", "Studio"].map(next => <DropdownItem key={next} label={next} selected={team === next} onSelect={() => act("Team selected", () => onTeamChange(next))} />)}</DropdownPopover></Dropdown>}
      navigation={<><Button disabled={disabled} onClick={() => act("Chat page selected", () => setView("chat"))}>Chat</Button><Button disabled={disabled} onClick={() => act("Dashboard selected", () => setView("dashboard"))}>Dashboard</Button><Button disabled={disabled} onClick={() => act("New chat requested", () => { const id = `new-${++sequence.current}`; setChats(previous => [...previous, { id, title: "New conversation", unread: false, messages: [] }]); setSelected(id); setView("chat"); setExported(null); })}>New chat</Button></>}
      history={<div className="hk-starter-history"><h3>History</h3>{chats.map(chat => <div key={chat.id}><div className="hk-starter-history-row"><Button disabled={disabled} aria-current={selected === chat.id && view === "chat" ? "page" : undefined} onClick={() => open(chat.id)}>{chat.title}{chat.unread && <span className="hk-starter-unread">{" "}Unread</span>}</Button><Dropdown label={`Actions for ${chat.title}`} disabled={disabled}><DropdownTrigger aria-label={`Actions for ${chat.title}`}><DotsThreeIcon size={18} aria-hidden="true" /></DropdownTrigger><DropdownPopover><DropdownItem label="Rename" onSelect={() => { setRenaming(chat.id); setName(chat.title); }} /><DropdownItem label={chat.unread ? "Mark read" : "Mark unread"} onSelect={() => act("Read state requested", () => setChats(previous => previous.map(item => item.id === chat.id ? { ...item, unread: !item.unread } : item)))} /><DropdownItem label="Delete" onSelect={() => setDeleting(chat.id)} /></DropdownPopover></Dropdown></div>{renaming === chat.id && <form onSubmit={event => { event.preventDefault(); if (name.trim()) act("Rename requested", () => { setChats(previous => previous.map(item => item.id === chat.id ? { ...item, title: name.trim() } : item)); setRenaming(null); }); }}><Input aria-label="Conversation name" value={name} disabled={disabled} onChange={event => setName(event.target.value)} maxLength={100} required /><Button type="submit" disabled={disabled || !name.trim()}>Save name</Button><Button onClick={() => setRenaming(null)}>Cancel rename</Button></form>}{deleting === chat.id && <div><p>Delete this synthetic conversation?</p><Button disabled={disabled} onClick={() => act("Delete requested", () => { const remaining = chats.filter(item => item.id !== chat.id); setChats(remaining.map(item => selected === chat.id && view === "chat" && item.id === remaining[0]?.id ? { ...item, unread: false } : item)); if (selected === chat.id) setSelected(remaining[0]?.id ?? ""); setExported(null); setDeleting(null); setDrafts(previous => Object.fromEntries(Object.entries(previous).filter(([id]) => id !== chat.id))); setRunning(previous => new Set([...previous].filter(id => id !== chat.id))); })}>Confirm delete</Button><Button onClick={() => setDeleting(null)}>Cancel delete</Button></div>}</div>)}</div>}
      userMenu={<Dropdown label="Account" disabled={disabled}><DropdownTrigger>Example account</DropdownTrigger><DropdownPopover><DropdownItem label="Sign in" onSelect={() => act("Sign-in page selected", () => setView("sign-in"))} /><DropdownItem label="Sign up" onSelect={() => act("Sign-up page selected", () => setView("sign-up"))} /></DropdownPopover></Dropdown>}
      thinking={busy ? <AgentThinking>Working · synthetic</AgentThinking> : undefined}
      actions={view === "chat" ? <ConversationDownload disabled={disabled} messages={current?.messages ?? []} onDownload={markdown => act("Export preview requested", () => setExported(markdown))}>Export preview</ConversationDownload> : undefined}
      composer={<Composer value={drafts[selected] ?? ""} onValueChange={text => { if (current) act("Draft changed", () => setDrafts(previous => ({ ...previous, [selected]: text }))); }} onSubmit={text => { if (disabled || !current || loading || error || busy || !text.trim()) return; act("Send requested", () => { setChats(previous => previous.map(chat => chat.id === selected ? { ...chat, messages: [...chat.messages, { role: "user", content: text }] } : chat)); setDrafts(previous => ({ ...previous, [selected]: "" })); setRunning(previous => new Set([...previous, selected])); setScenario("ready"); }); }}><PromptInputTextarea aria-label="Starter message" disabled={disabled || loading || error || !current} placeholder="What would you like to explore?" /><PromptInputFooter>{busy ? <Button disabled={disabled} onClick={() => finish(true)}>Stop</Button> : <PromptInputSubmit disabled={disabled || loading || error || !current || !(drafts[selected] ?? "").trim()} />}</PromptInputFooter></Composer>}
      dashboard={<section className="hk-starter-dashboard" aria-label="Starter dashboard"><StatCards label="Local workspace metrics" items={[{ id: "chats", label: "Conversations", value: chats.length }, { id: "unread", label: "Unread", value: chats.filter(chat => chat.unread).length }, { id: "messages", label: "Messages", value: chats.reduce((sum, chat) => sum + chat.messages.length, 0) }]} /><h3>Recent activity</h3>{chats.map(chat => <Button key={chat.id} disabled={disabled} onClick={() => open(chat.id)}>{chat.title} · {chat.messages.length} messages</Button>)}</section>}
      signIn={auth(false)} signUp={auth(true)}
      suggestions={!current?.messages.length ? ["Explore an idea", "Plan my next step"] : []} onSelect={text => { if (current) act("Suggestion selected", () => setDrafts(previous => ({ ...previous, [selected]: text }))); }}
    ><Conversation key={selected}><ConversationContent>{loading ? <p role="status">Loading history…</p> : error ? <div role="alert">Conversation unavailable.<Button disabled={disabled} onClick={() => act("Retry requested", () => setScenario("ready"))}>Retry</Button></div> : scenario === "empty" || !current?.messages.length ? <ConversationEmptyState /> : current.messages.map((message, index) => <Message key={index} from={message.role}><MessageContent><MessageResponse streaming={busy && message.role === "assistant" && index === current.messages.length - 1}>{message.content}</MessageResponse></MessageContent><MessageActions><Snippet code={message.content} disabled={disabled}><Tooltip content="Copy"><SnippetCopyButton timeout={1500} label={message.role === "assistant" ? "Copy assistant message" : "Copy"} onClick={event => { if (hold) { event.preventDefault(); act("Copy requested", () => {}); } }} /></Tooltip></Snippet>{message.role === "assistant" ? <><MessageActionButton label="Helpful" disabled={disabled} aria-pressed={!!feedback[`${selected}:${index}`]} onClick={() => act("Feedback requested", () => { setFeedback(previous => ({ ...previous, [`${selected}:${index}`]: !previous[`${selected}:${index}`] })); setNegative(previous => ({ ...previous, [`${selected}:${index}`]: false })); })} /><MessageActionButton label="Not helpful" disabled={disabled} aria-pressed={!!negative[`${selected}:${index}`]} onClick={() => act("Feedback requested", () => { setNegative(previous => ({ ...previous, [`${selected}:${index}`]: !previous[`${selected}:${index}`] })); setFeedback(previous => ({ ...previous, [`${selected}:${index}`]: false })); })} /><MessageActionButton label="Retry" disabled={disabled || busy} onClick={() => act("Retry requested; synthetic only", () => setRunning(previous => new Set([...previous, selected])))} /><MessageActionButton label={speech.reading === index ? "Stop reading" : "Read aloud"} disabled={disabled || busy} title="Read using a local English system voice only." aria-pressed={speech.reading === index} onClick={() => act("Read aloud requested", () => speech.read(message.content, index))} /></> : <MessageActionButton label="Edit" disabled={disabled || busy} onClick={() => act("Edit requested", () => setDrafts(previous => ({ ...previous, [selected]: message.content })))} />}</MessageActions></Message>)}</ConversationContent></Conversation>{exported !== null && <section aria-label="Export preview"><h3>Markdown export preview</h3><pre tabIndex={0}>{exported}</pre><Button onClick={() => setExported(null)}>Close export preview</Button></section>}</ChatStarter>
    {speech.error && <p role="alert">{speech.error}</p>}
    <output aria-label="Starter request">{request}</output>
  </div>;
}
