import { useState } from "react";
import { Select, CodeBlock, CodeBlockActions, CodeBlockContainer, CodeBlockContent, CodeBlockCopyButton, CodeBlockFilename, CodeBlockHeader, CodeBlockLanguageSelector, CodeBlockLanguageSelectorContent, CodeBlockLanguageSelectorItem, CodeBlockLanguageSelectorTrigger, CodeBlockTitle } from "@harso/ui";
import type { ExampleState } from "./examples";
export const codeBlockExports = ["CodeBlock"] as const;
export type CodeBlockExport = typeof codeBlockExports[number];
export const codeBlockNotes = { CodeBlock: { behavior: "Inert syntax-highlighted source with exact-text copy, line numbers and keyboard language selection. Shiki tokens follow Light/Dark; unknown languages remain readable plain text. Harso never executes supplied code.", example: '<CodeBlock code={code} language="typescript" showLineNumbers><CodeBlockHeader><CodeBlockTitle><CodeBlockFilename>example.ts</CodeBlockFilename></CodeBlockTitle><CodeBlockActions><CodeBlockCopyButton /></CodeBlockActions></CodeBlockHeader></CodeBlock>' } };
export function CodeBlockExample({ state }: { state: ExampleState }) {
  const [sample, setSample] = useState(state === "error" ? "error" : "ready");
  const [language, setLanguage] = useState("typescript");
  const [hold, setHold] = useState(false);
  const [disabled, setDisabled] = useState(false);
  const [standalone, setStandalone] = useState(false);
  const code = ["empty", "loading", "error"].includes(sample) ? "" : sample === "replacement" ? 'const replacement = "Host supplied replacement";' : state === "long-content" ? "export function renderWorkUnit() {\n  return {\n    status: \"running\",\n    progress: \"supplied by host\",\n  };\n}" : language === "typescript" ? 'const result: string = "Work complete";\r\n\r\nconsole.log(result);\r\n' : 'const result = "Work complete";\n\nconsole.log(result);\n';
  return <div><div className="hk-code-example"><div className="hk-example-controls"><label>Code sample<Select value={sample} onChange={event => setSample(event.target.value)}>{["ready", "empty", "loading", "error", "replacement", "disabled"].map(value => <option key={value}>{value}</option>)}</Select></label><label><input type="checkbox" checked={hold} onChange={event => setHold(event.target.checked)} />Hold language requests</label><label><input type="checkbox" checked={disabled} onChange={event => setDisabled(event.target.checked)} />Disable code controls</label><label><input type="checkbox" checked={standalone} onChange={event => setStandalone(event.target.checked)} />Standalone code content</label></div>{standalone ? <CodeBlockContainer><CodeBlockContent code={code} language={language} showLineNumbers /></CodeBlockContainer> : <CodeBlock aria-busy={sample === "loading"} code={code} language={language} showLineNumbers disabled={disabled || state === "disabled" || sample === "disabled" || sample === "loading" || sample === "error"}><CodeBlockHeader><CodeBlockTitle><CodeBlockFilename>work-unit.{language === "typescript" ? "ts" : "js"}</CodeBlockFilename></CodeBlockTitle><CodeBlockActions><CodeBlockLanguageSelector value={language} onValueChange={next => { if (!hold) setLanguage(next); }}><CodeBlockLanguageSelectorTrigger aria-label="Code language" /><CodeBlockLanguageSelectorContent><CodeBlockLanguageSelectorItem value="typescript">TypeScript</CodeBlockLanguageSelectorItem><CodeBlockLanguageSelectorItem value="javascript">JavaScript</CodeBlockLanguageSelectorItem></CodeBlockLanguageSelectorContent></CodeBlockLanguageSelector><CodeBlockCopyButton /></CodeBlockActions></CodeBlockHeader></CodeBlock>}</div><p role={sample === "error" ? "alert" : "status"}>Code sample: {sample}. {sample === "empty" ? "No code supplied." : sample === "loading" ? "Waiting for host code." : sample === "error" ? "Host could not supply code." : "Supplied source is never executed."}</p></div>;
}
