import { useId, useRef, useState } from "react";
import { MagnifyingGlassIcon, XIcon, TrayIcon, TrashIcon, UploadSimpleIcon } from "@phosphor-icons/react";
import { Avatar, Badge, Button, Checkbox, CheckboxCard, Field, FileUpload, IconButton, Input, InputOtp, Kbd, PhoneNumberInput, RadioCard, RadioDot, RadioGroup, RangeSlider, Select, SelectItem, Slider, Switch, SwitchCard, type FileUploadItem } from "@harso/ui";
import type { ExampleState } from "./examples";

export const controlExports = ["Input", "Checkbox", "Switch", "RadioGroup", "Select", "Slider", "Badge", "InputOtp", "FileUpload"] as const;
export type ControlExport = typeof controlExports[number];
const rangeScales = [
  { label: "Budget", min: 0, max: 100, step: 5, value: [20, 80] },
  { label: "Decimal", min: 0, max: 0.3, step: 0.1, value: [0.1, 0.3] },
  { label: "Partial last step", min: 0, max: 0.9999999999999999, step: 0.1, value: [0.5, 1] },
  { label: "Large origin", min: 1e12, max: 1e12 + 1, step: 0.0002, value: [1e12 + 0.3333, 1e12 + 0.7777] },
  { label: "Out of bounds", min: 0, max: 101, step: 5, value: [-10, 200] },
  { label: "Precision limit", min: 1e12, max: 1e12 + 0.009, step: 0.0002, value: [1e12, 1e12 + 0.009] },
] satisfies { label: string; min: number; max: number; step: number; value: [number, number] }[];
export const controlNotes: Record<ControlExport, { behavior: string; example: string }> = {
  Input: { behavior: "Native editing, autocomplete, form values and refs; leading/trailing content leaves the input intact. PhoneNumberInput uses supplied calling-code choices and unformatted telephone text—no invented E.164 normalization or country database.", example: '<Input leading={icon} trailing={clearButton} value={query} onChange={update} />' },
  Checkbox: { behavior: "Native checkbox, mixed-state presentation, three visual sizes and an unboxed selectable-card composition. The host supplies the aggregate state. Description is separate from the accessible name; no extra selection store.", example: '<Checkbox indeterminate={partlySelected} checked={allSelected} label="All references" onChange={toggleAll} />' },
  Switch: { behavior: "Pill/rectangle switches in three sizes, with a quiet SwitchCard composition. Native form/reset behavior; the host owns controlled reset. Changing this example never requests a microphone or saves preferences.", example: '<SwitchCard label="Voice responses" description="Read the reply aloud" checked={enabled} onChange={update} />' },
  RadioGroup: { behavior: "Native single-choice groups and RadioCard/RadioDot parts. One shared name gives keyboard selection and FormData/reset without a custom roving-focus store. No nested interactive elements inside choice labels.", example: '<fieldset><legend>Audience</legend><RadioCard name="audience" label="Our team" value="team" defaultChecked /></fieldset>' },
  Select: { behavior: "SelectItem renders a native option with optional text description. The OS owns the picker. Rich icons, avatars and custom popup search are not claimed by this native example.", example: '<Select aria-label="Workspace"><SelectItem value="team" description="Shared space">Team</SelectItem></Select>' },
  Slider: { behavior: "A single native range input plus a controlled minimum/maximum pair. Two labelled tracks deliberately replace overlapping thumbs, preserving touch and keyboard targets. Values are finite, stepped and bounded; invalid bounds disable the pair.", example: '<RangeSlider label="Budget" value={range} onValueChange={setRange} min={0} max={100} step={5} />' },
  Badge: { behavior: "Semantic count/status indicators and a native Kbd hint. Keyboard hints describe host actions; this component registers no shortcuts. Counts are never inferred from status.", example: '<Badge tone="active">3</Badge><Kbd>⌘ K</Kbd>' },
  InputOtp: { behavior: "One native code field preserves paste, selection, undo, autocomplete and form validity. Numeric/alphanumeric, 1–12 characters. Completion requests no verification and never auto-submits. Optional grouped slots mirror the same native field without replacing autofill or form data.", example: '<InputOtp aria-label="One-time code" length={6} required onComplete={showReady} />' },
  FileUpload: { behavior: "Native chooser and drag/drop share atomic count/type/size checks. Only File objects reach the host; contents are never read, previewed, stored or uploaded by the kit. Supplied statuses/progress/actions are real host props, not a timer. File metadata checks are UX constraints, not server-side security validation.", example: '<FileUpload label="Reference files" accept=".txt,.md" multiple files={files} onFilesSelect={select} onRemove={remove} />' },
};

export function ControlsExample({ component, state }: { component: ControlExport; state: ExampleState }) {
  const identity = useId();
  const nextFile = useRef(0);
  const disabled = state === "disabled";
  const [query, setQuery] = useState(state === "long-content" ? "A quietly ambitious launch with a clear direction and room to grow" : "Launch research");
  const [country, setCountry] = useState("sg");
  const [phone, setPhone] = useState("8123 4567");
  const [selected, setSelected] = useState(["notes"]);
  const [enabled, setEnabled] = useState(false);
  const [size, setSize] = useState<"small" | "medium" | "large">("medium");
  const [audience, setAudience] = useState("team");
  const [range, setRange] = useState<readonly [number, number]>([20, 80]);
  const [scale, setScale] = useState(0);
  const [volume, setVolume] = useState(45);
  const [code, setCode] = useState("");
  const [alphabet, setAlphabet] = useState<"numeric" | "alphanumeric">("numeric");
  const [message, setMessage] = useState("");
  const [files, setFiles] = useState<FileUploadItem[]>([]);
  const options = [{ value: "team", label: "Our team" }, { value: "everyone", label: "Everyone" }, { value: "external", label: "External", disabled: true }];
  const sizes = <Field label="Control size">{props => <Select {...props} value={size} onChange={event => setSize(event.target.value as typeof size)}><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></Select>}</Field>;
  switch (component) {
    case "Input": return <div className="hkl-example-stack"><Field label="Project name" required error={state === "error" ? "Use a name your team can recognize." : undefined}>{props => <Input {...props} value={query} disabled={disabled} onChange={event => setQuery(event.target.value)} leading={<MagnifyingGlassIcon aria-hidden="true" />} trailing={<IconButton label="Clear project name" disabled={disabled} onClick={() => setQuery("")}><XIcon /></IconButton>} />}</Field><Field label="Phone number" description="Choose a calling code. Your number stays exactly as typed.">{props => <PhoneNumberInput {...props} disabled={disabled} countries={[{ value: "sg", label: "Singapore", dialCode: "+65" }, { value: "gb", label: "United Kingdom", dialCode: "+44" }]} country={country} onCountryChange={setCountry} value={phone} onChange={event => setPhone(event.target.value)} />}</Field></div>;
    case "Checkbox": return <div className="hkl-example-stack">{sizes}<Checkbox label="All references" disabled={disabled} controlSize={size} checked={selected.length === 2} indeterminate={selected.length === 1} onChange={event => setSelected(event.target.checked ? ["notes", "research"] : [])} /><div>{["notes", "research"].map(value => <CheckboxCard key={value} label={value === "notes" ? "Conversation notes" : "Research sources"} description={value === "notes" ? "Keep the important decisions nearby." : "Bring the evidence into view."} controlSize={size} disabled={disabled} checked={selected.includes(value)} onChange={event => setSelected(previous => event.target.checked ? [...previous, value] : previous.filter(item => item !== value))} />)}</div><output aria-live="polite">{selected.length} reference{selected.length === 1 ? "" : "s"} selected</output></div>;
    case "Switch": return <div className="hkl-example-stack">{sizes}<Switch label="Pill switch" controlSize={size} checked={enabled} disabled={disabled} onChange={event => setEnabled(event.target.checked)} /><Switch label="Rectangle switch" shape="rectangle" controlSize={size} checked={enabled} disabled={disabled} onChange={event => setEnabled(event.target.checked)} /><SwitchCard label="Voice responses" description="An illustrative preference, not a microphone request." controlSize={size} disabled={disabled} checked={enabled} onChange={event => setEnabled(event.target.checked)} /><output aria-live="polite">Voice responses {enabled ? "on" : "off"}</output></div>;
    case "RadioGroup": return <div className="hkl-example-stack"><RadioGroup label="Who are we speaking to?" options={options} value={audience} onValueChange={setAudience} disabled={disabled} /><form onSubmit={event => { event.preventDefault(); setMessage(`Native form: ${new FormData(event.currentTarget).get("delivery")}`); }}><fieldset className="hkl-choice-set" disabled={disabled}><legend>Delivery</legend><RadioCard label="A focused brief" description="The recommendation, with its evidence." name="delivery" value="brief" defaultChecked /><RadioCard label="A full report" description="The context, details and alternatives." name="delivery" value="report" /><label className="hk-choice"><RadioDot name="delivery" value="archive" disabled /><span>Archive only · unavailable</span></label></fieldset><div className="hkl-example-row"><Button type="submit" disabled={disabled}>Read form</Button><Button type="reset" disabled={disabled}>Reset choices</Button></div></form><output aria-live="polite">{message || "The keyboard works just as you expect."}</output></div>;
    case "Select": return <div className="hkl-example-stack"><Field label="Audience">{props => <Select {...props} value={audience} disabled={disabled} onChange={event => setAudience(event.target.value)}><SelectItem value="team" description="A shared workspace">Our team</SelectItem><SelectItem value="everyone" description="All project participants">Everyone</SelectItem><SelectItem value="external" disabled>External · unavailable</SelectItem></Select>}</Field><Field label="Rich audience">{props => <Select {...props} customizable value={audience} disabled={disabled} onChange={event => setAudience(event.target.value)}><SelectItem value="team" textValue="Our team"><Avatar name="Alex Bennett" size="sm" /><span>Shared workspace</span></SelectItem><SelectItem value="everyone" textValue="Everyone"><span aria-hidden="true">●</span><span>Project participants</span></SelectItem><SelectItem value="external" textValue="External" disabled>Not available</SelectItem></Select>}</Field></div>;
    case "Slider": return <form className="hkl-example-stack" onReset={event => { event.preventDefault(); setRange(rangeScales[scale].value); setVolume(45); }}><label>Range scale<Select disabled={disabled} value={scale} onChange={event => { const next = Number(event.target.value); setScale(next); setRange(rangeScales[next].value); }}>{rangeScales.map((item, index) => <option key={item.label} value={index}>{item.label}</option>)}</Select></label><RangeSlider {...rangeScales[scale]} label="Budget" value={range} onValueChange={setRange} disabled={disabled} name={["minimum", "maximum"]} /><output aria-label="Supplied range">{JSON.stringify(range)}</output><div><label htmlFor={identity}>Volume · {volume}%</label><Slider id={identity} showValue formatValue={value => `${value}%`} disabled={disabled} value={volume} onChange={event => setVolume(event.target.valueAsNumber)} /></div><Button type="reset" disabled={disabled}>Reset range</Button></form>;
    case "Badge": return <div className="hkl-example-stack"><div className="hkl-example-row"><Badge>Draft</Badge><Badge tone="active">3</Badge><Badge tone="positive">Complete</Badge><Badge tone="attention">Needs your input</Badge><Badge tone="negative">Couldn’t finish</Badge></div><div className="hkl-example-row"><span>Find anything</span><Kbd>⌘ K</Kbd><span>Close details</span><Kbd>Esc</Kbd></div></div>;
    case "InputOtp": return <form className="hkl-example-stack" onSubmit={event => { event.preventDefault(); setMessage("Code submitted to the demo host. No verification request."); }} onReset={event => { event.preventDefault(); setCode(""); setMessage(""); }}><Field label="Code alphabet">{props => <Select {...props} value={alphabet} onChange={event => { setAlphabet(event.target.value as typeof alphabet); setCode(""); setMessage(""); }}><option value="numeric">Numeric</option><option value="alphanumeric">Alphanumeric</option></Select>}</Field><Field label="One-time code" required description="Six characters. Paste or type; submit when ready." error={state === "error" ? "That sample code was not accepted. Try another." : undefined}>{props => <InputOtp {...props} groupEvery={3} disabled={disabled} alphabet={alphabet} name="code" value={code} onValueChange={value => { setCode(value); setMessage(""); }} onComplete={() => setMessage("Code is complete. Submit when ready.")} />}</Field><div className="hkl-example-row"><Button type="submit" variant="primary" disabled={disabled}>Continue</Button><Button type="reset" disabled={disabled}>Clear code</Button></div><output aria-live="polite">{message}</output></form>;
    case "FileUpload": return <div className="hkl-example-stack"><FileUpload icon={<UploadSimpleIcon size={20} />} label="Reference files" description="Text or Markdown · up to 4 files · 1,024 bytes each. This example does not read or upload contents." accept=".txt,.md" multiple maxFiles={4} maxSizeBytes={1024} disabled={disabled} files={files} onFilesSelect={selection => { setFiles(previous => [...previous, ...selection.map(file => ({ id: `${identity}-${nextFile.current++}`, name: file.name, size: file.size, status: "selected" as const }))]); setMessage("Selection received. Nothing was uploaded."); }} onRemove={id => setFiles(previous => previous.filter(file => file.id !== id))} onRetry={id => { setFiles(previous => previous.map(file => file.id === id ? { ...file, status: "selected", message: "Retry requested. No upload started." } : file)); }} /><div className="hkl-example-row"><Button variant="ghost" leadingIcon={<TrayIcon size={16} />} disabled={disabled} onClick={() => setFiles([{ id: "sample-upload", name: "launch-brief.md", size: 920, status: "uploading", progress: .35 }, { id: "sample-error", name: "research-notes.txt", status: "error", message: "Connection lost. Your file is still available." }, { id: "sample-done", name: "decisions.txt", status: "complete", size: 310 }])}>Show supplied transfer states</Button><Button variant="ghost" leadingIcon={<TrashIcon size={16} />} disabled={disabled} onClick={() => { setFiles([]); setMessage(""); }}>Clear sample files</Button></div><output aria-live="polite">{message || "Progress is supplied by the example host, never simulated by a timer."}</output></div>;
  }
}
