import { useState } from "react";
import { Badge, Button, Checkbox, EnvironmentVariable, EnvironmentVariableCopyButton, EnvironmentVariableGroup, EnvironmentVariableName, EnvironmentVariableRequired, EnvironmentVariableValue, EnvironmentVariables, EnvironmentVariablesContent, EnvironmentVariablesHeader, EnvironmentVariablesTitle, EnvironmentVariablesToggle, Field, PackageInfo, PackageInfoChangeType, PackageInfoContent, PackageInfoDependencies, PackageInfoDependency, PackageInfoDescription, PackageInfoHeader, PackageInfoName, PackageInfoVersion, Select, Snippet, SnippetAddon, SnippetCopyButton, SnippetInput, SnippetText, type PackageChangeType } from "@harso/ui";
import type { ExampleState } from "./examples";

export const developerContentExports = ["Snippet", "PackageInfo", "EnvironmentVariables"] as const;
export type DeveloperContentExport = typeof developerContentExports[number];
export const developerContentNotes: Record<DeveloperContentExport, { behavior: string; example: string }> = {
  Snippet: { behavior: "A command is selectable text, not an executable action. Copy uses the native clipboard only after a click, reports failure without a fallback, and ignores late completion after the content changes. Prefix and copy controls are composable. No syntax-highlighting claim.", example: '<Snippet code={command}><SnippetAddon><SnippetText>$</SnippetText></SnippetAddon><SnippetInput aria-label="Command" /><SnippetCopyButton onError={reportCopyFailure} /></Snippet>' },
  PackageInfo: { behavior: "Dependency changes sit directly on the canvas. Every version and change classification comes from the host; missing versions stay visibly unknown. Major, minor, patch, added and removed have text labels as well as tone. No installation, registry lookup or semver inference.", example: '<PackageInfo name={name} currentVersion={current} newVersion={next} changeType="minor"><PackageInfoHeader><PackageInfoName /><PackageInfoVersion /><PackageInfoChangeType /></PackageInfoHeader><PackageInfoContent><PackageInfoDependencies><PackageInfoDependency name="dependency" version="1.0.0" /></PackageInfoDependencies></PackageInfoContent></PackageInfo>' },
  EnvironmentVariables: { behavior: "Authorized, host-supplied sample values are hidden by default, including custom value children. Reveal may be refused; hidden values cannot be copied, but names can. Export copies POSIX-quoted text with a validated variable name—never executes it. Key this surface by conversation/environment identity; masking is not a secret vault.", example: '<EnvironmentVariables key={environmentId}><EnvironmentVariablesHeader><EnvironmentVariablesTitle /><EnvironmentVariablesToggle /></EnvironmentVariablesHeader><EnvironmentVariablesContent><EnvironmentVariable name="SAMPLE_KEY" value={authorizedValue}><EnvironmentVariableName /><EnvironmentVariableValue /><EnvironmentVariableCopyButton copyFormat="value" /></EnvironmentVariable></EnvironmentVariablesContent></EnvironmentVariables>' },
};

function SnippetExample({ state }: { state: ExampleState }) {
  const [replacement, setReplacement] = useState(false);
  const [prefix, setPrefix] = useState(true);
  const [hold, setHold] = useState(false);
  const [request, setRequest] = useState("Copy is optional. Nothing runs from this surface.");
  const command = state === "long-content" ? 'example inspect --project "a thoughtful space for long-running work" --output summary --include-observations --format plain-text' : replacement ? "example inspect --summary" : "example status";
  return <div className="hkl-example-stack"><div className="hk-data-toolbar"><Checkbox label="Show command prefix" checked={prefix} onChange={event => setPrefix(event.target.checked)} /><Checkbox label="Prevent copy" checked={hold} onChange={event => setHold(event.target.checked)} /><Button size="small" onClick={() => { setReplacement(!replacement); setRequest("Sample command changed. Nothing executed."); }}>Replace sample command</Button></div><Snippet code={command} disabled={state === "disabled"}>{prefix && <SnippetAddon><SnippetText aria-hidden="true">$</SnippetText></SnippetAddon>}<SnippetInput /><SnippetCopyButton onClick={event => { if (hold) event.preventDefault(); }} onCopy={() => setRequest("Command copied. Nothing executed.")} onError={() => setRequest("Copy failed. Select the command and copy manually.")} /></Snippet><output aria-label="Developer request">{request}</output></div>;
}

function PackageExample({ state }: { state: ExampleState }) {
  const [changeType, setChangeType] = useState<PackageChangeType>("minor");
  const [missing, setMissing] = useState(false);
  return <div className="hkl-example-stack"><div className="hk-data-toolbar"><Field label="Change type">{props => <Select {...props} value={changeType} onChange={event => setChangeType(event.target.value as PackageChangeType)}>{["major", "minor", "patch", "added", "removed"].map(type => <option key={type}>{type}</option>)}</Select>}</Field><Checkbox label="Versions unavailable" checked={missing} onChange={event => setMissing(event.target.checked)} /></div><PackageInfo name={state === "long-content" ? "@sample/thoughtful-workspace-observations-and-personal-context" : "@sample/workspace"} currentVersion={missing || changeType === "added" ? undefined : "2.1.0"} newVersion={missing || changeType === "removed" ? undefined : "2.2.0"} changeType={changeType}><PackageInfoHeader><PackageInfoName /><PackageInfoVersion /><PackageInfoChangeType /></PackageInfoHeader><PackageInfoDescription>Small improvements to how observations come together. This is supplied sample data, not an available update.</PackageInfoDescription><PackageInfoContent><h3>Dependencies</h3><PackageInfoDependencies><PackageInfoDependency name="@sample/observations" version="1.4.0" /><PackageInfoDependency name="@sample/context" version="0.8.2" /><PackageInfoDependency name="@sample/optional-export" /></PackageInfoDependencies></PackageInfoContent></PackageInfo></div>;
}

function EnvironmentExample({ state }: { state: ExampleState }) {
  const [shown, setShown] = useState(false);
  const [hold, setHold] = useState(false);
  const [generation, setGeneration] = useState(0);
  const [format, setFormat] = useState<"name" | "value" | "export">("value");
  const [request, setRequest] = useState("Synthetic values only. Nothing is read from your environment.");
  const name = state === "long-content" ? "SAMPLE_WORKSPACE_OBSERVATION_EXPORT_DESCRIPTION" : "SAMPLE_TOKEN";
  const value = state === "long-content" ? "A longer sample value with a quote ' and $(literal text), not an instruction or a real credential." : generation ? "demo-sample-two" : "demo-sample-one";
  return <div className="hkl-example-stack"><div className="hk-data-toolbar"><Field label="Copy format">{props => <Select {...props} value={format} onChange={event => setFormat(event.target.value as typeof format)}><option value="value">Value</option><option value="name">Name</option><option value="export">POSIX export</option></Select>}</Field><Checkbox label="Hold host visibility" checked={hold} onChange={event => setHold(event.target.checked)} /><Button size="small" onClick={() => { setGeneration(generation + 1); setShown(false); setRequest("Sample environment replaced and hidden."); }}>Change sample environment</Button></div><EnvironmentVariables key={generation} showValues={shown} disabled={state === "disabled"} onShowValuesChange={next => { if (hold) { setRequest("Host refused visibility change."); return false; } setShown(next); }}><EnvironmentVariablesHeader><EnvironmentVariablesTitle>Workspace configuration</EnvironmentVariablesTitle><EnvironmentVariablesToggle /></EnvironmentVariablesHeader><EnvironmentVariablesContent><EnvironmentVariable name={name} value={value}><EnvironmentVariableGroup><EnvironmentVariableName /><EnvironmentVariableRequired /></EnvironmentVariableGroup><EnvironmentVariableValue /><EnvironmentVariableCopyButton copyFormat={format} onCopy={() => setRequest("Selected sample copied. Nothing executed.")} onError={() => setRequest("Copy failed. Your browser may block clipboard access.")} /></EnvironmentVariable><EnvironmentVariable name="SAMPLE_REGION" value="sample-local"><EnvironmentVariableName /><EnvironmentVariableValue /><EnvironmentVariableCopyButton copyFormat={format} /></EnvironmentVariable><EnvironmentVariable name="SAMPLE_OPTIONAL" value=""><EnvironmentVariableGroup><EnvironmentVariableName /><Badge>Optional</Badge></EnvironmentVariableGroup><EnvironmentVariableValue /><EnvironmentVariableCopyButton copyFormat={format} /></EnvironmentVariable></EnvironmentVariablesContent></EnvironmentVariables><output aria-label="Developer request">{request}</output></div>;
}

export function DeveloperContentExample({ component, state }: { component: DeveloperContentExport; state: ExampleState }) {
  if (component === "Snippet") return <SnippetExample state={state} />;
  if (component === "PackageInfo") return <PackageExample state={state} />;
  return <EnvironmentExample state={state} />;
}
