import { useState } from "react";
import { ArrowRightIcon, ChatCircleIcon, FileTextIcon, HouseIcon, LinkIcon, SparkleIcon } from "@phosphor-icons/react";
import { Announcement, Avatar, Breadcrumb, BreadcrumbItem, Button, ButtonGroup, Checkbox, Chip, CloseButton, Field, IconButton, Input, KitProvider, Pagination, SegmentedControl, Select, Sidebar, SidebarItem, StatusDot, Tabs, ThemeToggle, Tooltip, type Appearance, type Palette, type ChipTone } from "@harso/ui";
import type { ExampleState } from "./examples";

export const navigationExports = ["Breadcrumb", "ButtonGroup", "Chip", "CloseButton", "Pagination", "SegmentedControl", "Tabs", "ThemeToggle", "Tooltip", "Announcement"] as const;
export type NavigationExport = typeof navigationExports[number];
export const navigationNotes: Record<NavigationExport, { behavior: string; example: string }> = {
  Breadcrumb: { behavior: "Native ancestor links, optional icon/avatar content and a noninteractive current location. Narrow paths collapse older ancestors and truncate the current location instead of wrapping separators.", example: '<Breadcrumb><BreadcrumbItem href="/projects">Projects</BreadcrumbItem><BreadcrumbItem current>Launch</BreadcrumbItem></Breadcrumb>' },
  ButtonGroup: { behavior: "Joined single/multi-select actions use native radios or checkboxes: keyboard, form submission, reset, controlled/uncontrolled values and labelled icon-only items. The host receives selection intent, not new persistent state.", example: '<ButtonGroup label="Export formats" items={formats} multiple selected={selected} onSelectionChange={update} />' },
  Chip: { behavior: "Bold, subtle and caption treatments with semantic tones. Text conveys meaning; StatusDot is decorative. Donor decorative color aliases become Harso semantic tones, not a second rainbow palette.", example: '<Chip tone="positive"><StatusDot tone="positive" />Ready</Chip>' },
  CloseButton: { behavior: "Four icon scales retain a generous hit target and accessible label. Disabled closes do nothing; dismissing a panel always remains a supplied action.", example: '<CloseButton label="Close work details" onClick={close} size="small" />' },
  Pagination: { behavior: "Bounded first/last and sibling page window, previous/next, ellipses and current-page semantics. No fetch or implicit selection. Invalid/empty totals say No pages; large page counts never allocate a page-sized array.", example: '<Pagination page={page} pageCount={24} onPageChange={setPage} siblings={1} />' },
  SegmentedControl: { behavior: "Native single selection, controlled or uncontrolled. All options are labelled and submitted using the supplied form name. Reset is native; group identities do not leak between instances.", example: '<SegmentedControl label="View" items={views} value={view} onValueChange={setView} />' },
  Tabs: { behavior: "Related panels with automatic arrow-key activation, Home/End, disabled-item skipping, unique relations and retained drafts. Underline/pill, neutral/accent, icons and count content; horizontal/vertical and RTL navigation. Selection state remains local UI or controlled by the host.", example: '<Tabs label="Work details" items={panels} variant="pill" tone="accent" />' },
  ThemeToggle: { behavior: "System, Light and Dark selection plus compact cycling. The host owns persistence; this preview never writes preferences. No circular reveal: the approved motion policy keeps appearance changes immediate and respects reduced motion.", example: '<ThemeToggle value={appearance} onValueChange={setAppearance} compact={collapsed} />' },
  Tooltip: { behavior: "Installed Radix supplies hover/focus, boundary collision and Escape behavior. Content stays in its theme scope instead of an unthemed body portal. Four placements, two densities; hints never hide required decisions or replace action labels.", example: '<Tooltip content="Copy a link" side="top"><IconButton label="Copy link" onClick={copy}><LinkIcon /></IconButton></Tooltip>' },
  Announcement: { behavior: "A quiet announcement with optional icon, description, action and explicit dismiss callback. The host removes it; no automatic expiry or essential information hidden behind a tooltip.", example: '<Announcement title="A new chapter" description={description} action={action} onDismiss={dismiss} />' },
};

export function NavigationExample({ component, state, palette = "clean" }: { component: NavigationExport; state: ExampleState; palette?: Palette }) {
  const [selection, setSelection] = useState("overview");
  const [formats, setFormats] = useState(["pdf"]);
  const [page, setPage] = useState(12);
  const [message, setMessage] = useState("");
  const [appearance, setAppearance] = useState<Appearance>("system");
  const [themePlacement, setThemePlacement] = useState("standalone");
  const [visible, setVisible] = useState(true);
  const [variant, setVariant] = useState("underline");
  const [placement, setPlacement] = useState<"top" | "bottom" | "left" | "right">("top");
  const [localDisabled, setLocalDisabled] = useState(false);
  const [holdSelection, setHoldSelection] = useState(false);
  const [hostRequest, setHostRequest] = useState("");
  const [tabContent, setTabContent] = useState("full");
  const [hintContent, setHintContent] = useState("Copy a link to this sample brief");
  const [hintOpen, setHintOpen] = useState(true); // the default capture shows the bubble; hover/focus/Escape still drive it
  const [holdHint, setHoldHint] = useState(false);
  const disabled = state === "disabled" || localDisabled;
  const lifecycleControls = <Checkbox label="Disable example controls" checked={localDisabled} onChange={event => setLocalDisabled(event.target.checked)} />;
  const selectionControls = <><Checkbox label="Hold host selection" checked={holdSelection} onChange={event => setHoldSelection(event.target.checked)} /><output aria-label="Host request">{hostRequest}</output></>;
  const changeAppearance = (next: Appearance) => { setHostRequest(`Requested: ${next}`); if (!holdSelection) setAppearance(next); };
  const choices = [{ value: "overview", label: "Overview" }, { value: "activity", label: "Activity" }, { value: "files", label: "Files", disabled: true }];
  switch (component) {
    case "Breadcrumb": return <Breadcrumb><BreadcrumbItem href="#boardui:button"><HouseIcon aria-hidden="true" />Workspace</BreadcrumbItem><BreadcrumbItem href="#boardui:avatar"><Avatar name="Harso launch" size={24} />Harso launch</BreadcrumbItem><BreadcrumbItem current>{state === "long-content" ? "A thoughtful launch research journey with a longer project name" : "Launch research"}</BreadcrumbItem></Breadcrumb>;
    case "ButtonGroup": return <div className="hkl-example-stack"><span className="hkl-example-label">Export formats</span><ButtonGroup label="Export formats" multiple items={[{ value: "pdf", label: "PDF" }, { value: "markdown", label: "Markdown" }, { value: "html", label: "HTML", disabled: true }]} selected={formats} onSelectionChange={setFormats} disabled={disabled} /><output aria-live="polite">Selected: {formats.length ? formats.join(", ") : "None"}</output><ButtonGroup label="Document view" selected={[selection]} onSelectionChange={values => setSelection(values[0])} disabled={disabled} items={[{ value: "overview", label: "Conversation", content: <ChatCircleIcon size={18} aria-hidden="true" /> }, { value: "activity", label: "Document", content: <FileTextIcon size={18} aria-hidden="true" /> }]} /></div>;
    case "Chip": return <div className="hkl-example-stack">{(["bold", "subtle", "caption"] as const).map(style => <section key={style} aria-label={`${style} chips`}><span className="hkl-example-label" style={{ display: "block", marginBottom: 12 }}>{style === "bold" ? "Bold" : style === "subtle" ? "Subtle" : "Caption"}</span><div className="hkl-example-row" style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(132px, 1fr))", justifyItems: "start", gap: 12 }}>{([{ tone: "neutral", label: "Draft" }, { tone: "accent", label: "Working" }, { tone: "positive", label: "Ready" }, { tone: "attention", label: "Needs input" }, { tone: "negative", label: "Couldn’t finish" }] as { tone: ChipTone; label: string }[]).map(item => <Chip key={item.tone} tone={item.tone} variant={style}><StatusDot tone={item.tone} />{item.label}</Chip>)}</div></section>)}</div>;
    case "CloseButton": return <div className="hkl-example-stack"><div className="hkl-example-row">{(["2xs", "xs", "small", "medium"] as const).map(size => <CloseButton key={size} label={`Close ${size} example`} size={size} disabled={disabled} onClick={() => setMessage(`${size} close action received`)} />)}</div><output aria-live="polite">{message || "Quiet icons. Full-sized hit targets."}</output></div>;
    case "Pagination": return <div className="hkl-example-stack"><Pagination page={page} pageCount={24} onPageChange={setPage} disabled={disabled} /><output aria-live="polite">Page {page} of 24 · sample results</output><Pagination label="Single page example" page={1} pageCount={1} onPageChange={() => undefined} disabled={disabled} /></div>;
    case "SegmentedControl": return <div className="hkl-example-stack"><SegmentedControl label="Work view" items={choices} value={selection} onValueChange={setSelection} disabled={disabled} /><output aria-live="polite">Showing {selection}</output><form className="hkl-example-stack" onSubmit={event => { event.preventDefault(); setMessage(`Native form: ${new FormData(event.currentTarget).get("detail")}`); }}><SegmentedControl label="Detail density" name="detail" items={[{ value: "comfortable", label: "Comfortable" }, { value: "compact", label: "Compact" }]} defaultValue="comfortable" disabled={disabled} /><div className="hkl-example-row"><Button type="submit" disabled={disabled}>Read form</Button><Button type="reset" disabled={disabled}>Reset</Button></div><output aria-live="polite">{message}</output></form></div>;
    case "Tabs": return <div className="hkl-example-stack">{lifecycleControls}{selectionControls}<p>Panels are supplied synchronously; there is no loading or error contract. Empty content removes panels; disabling keeps drafts mounted, with no active panel until re-enabled.</p><Field label="Tab content">{props => <Select {...props} value={tabContent} onChange={event => setTabContent(event.target.value)}><option value="full">All panels</option><option value="replacement">Remove sources</option><option value="empty">No panels</option></Select>}</Field>{tabContent === "empty" && <p>No panels supplied.</p>}<Field label="Tab treatment">{props => <Select {...props} value={variant} onChange={event => setVariant(event.target.value)}><option value="underline">Underline</option><option value="pill">Quiet pills</option><option value="accent">Accent pills</option><option value="vertical">Vertical</option></Select>}</Field><Tabs label="Work details" value={selection} onValueChange={next => { setHostRequest(`Requested: ${next}`); if (!holdSelection) setSelection(next); }} variant={variant === "pill" || variant === "accent" ? "pill" : "underline"} tone={variant === "accent" ? "accent" : "neutral"} orientation={variant === "vertical" ? "vertical" : "horizontal"} items={(tabContent === "empty" ? [] : [{ value: "overview", label: <><FileTextIcon aria-hidden="true" />Overview</>, disabled, content: <div className="hkl-example-stack"><h3>Start smaller.</h3><p>{state === "long-content" ? "Make the first experience exceptional. This longer summary stays readable as the available space changes, without boxing every thought into a card." : "Make the first experience exceptional."}</p><Field label="Draft title">{props => <Input {...props} defaultValue="A focused launch" disabled={disabled} />}</Field></div> }, { value: "sources", label: <>Sources <Chip variant="caption">6</Chip></>, disabled, content: <ul className="hkl-source-example"><li>Customer interviews <span>3 notes</span></li><li>Product research <span>2 reports</span></li><li>Launch strategy <span>1 brief</span></li></ul> }, { value: "history", label: "History", disabled: true, content: "No history supplied in this example." }]).filter(item => tabContent !== "replacement" || item.value !== "sources")} /></div>;
    case "ThemeToggle": return <div className="hkl-example-stack">
      {lifecycleControls}{selectionControls}<p>Appearance is a required synchronous value, not fetched content: empty, loading and error states do not apply. Host refusal leaves the current appearance unchanged; nothing is persisted.</p>
      <Field label="Theme placement">{props => <Select {...props} value={themePlacement} onChange={event => setThemePlacement(event.target.value)}><option value="standalone">Standalone controls</option><option value="expanded">Expanded sidebar</option><option value="collapsed">Collapsed sidebar</option></Select>}</Field>
      <KitProvider appearance={appearance} palette={palette} className="hkl-theme-example">
        {themePlacement === "standalone" ? <><ThemeToggle value={appearance} onValueChange={changeAppearance} disabled={disabled} /><p>A shared canvas, in your preferred light.</p><div className="hkl-example-row"><ThemeToggle value={appearance} onValueChange={changeAppearance} compact disabled={disabled} /><span>Compact control</span></div></> : <Sidebar label="Appearance workspace" collapsed={themePlacement === "collapsed"} onCollapsedChange={collapsed => setThemePlacement(collapsed ? "collapsed" : "expanded")}>
          <SidebarItem label="Overview" icon={<HouseIcon size={20} />} selected disabled={disabled} />
          <ThemeToggle value={appearance} onValueChange={changeAppearance} compact={themePlacement === "collapsed"} disabled={disabled} />
        </Sidebar>}
      </KitProvider><output aria-live="polite">Example appearance: {appearance}. Nothing is saved.</output>
    </div>;
    case "Tooltip": return <div className="hkl-example-stack">{lifecycleControls}<Checkbox label="Hold hint state" checked={holdHint} onChange={event => setHoldHint(event.target.checked)} /><Field label="Hint content">{props => <Input {...props} value={hintContent} onChange={event => setHintContent(event.target.value)} />}</Field><p>Hints are synchronous optional text, not loading or error feedback. Empty copy suppresses this hint. A disabled native trigger blocks the action; hover disclosure is separate from activation.</p><Field label="Hint placement">{props => <Select {...props} value={placement} onChange={event => setPlacement(event.target.value as typeof placement)}>{["top", "bottom", "left", "right"].map(side => <option key={side}>{side}</option>)}</Select>}</Field><div className="hkl-example-row"><Tooltip content={hintContent} side={placement} open={!!hintContent && hintOpen} onOpenChange={next => { if (!holdHint) setHintOpen(next); }}><IconButton label="Copy link" disabled={disabled} onClick={() => setMessage("Copy action received; no clipboard write.")}><LinkIcon /></IconButton></Tooltip><Tooltip content="Open the sample brief" side={placement} size="small"><Button disabled={disabled} onClick={() => setMessage("Open action received")}>Open brief <ArrowRightIcon aria-hidden="true" size={16} /></Button></Tooltip></div><output aria-live="polite">{message || "Focus or hover. Escape dismisses the hint."}</output></div>;
    case "Announcement": return <div className="hkl-example-stack"><Announcement open={visible} title="A little more room to think." icon={<SparkleIcon />} description={state === "long-content" ? "Keep your conversation in focus while the details wait just to the side. This longer description deliberately tests a narrow space without turning it into another boxed dashboard." : "Your work, with fewer distractions."} action={<Button onClick={() => setMessage("Explore action received")}>Take a look <ArrowRightIcon size={16} aria-hidden="true" /></Button>} onDismiss={() => setVisible(false)} />{!visible && <Button onClick={() => setVisible(true)}>Show announcement again</Button>}<Announcement title="A title is sometimes enough." /><output aria-live="polite">{message}</output></div>;
  }
}
