import { useState } from "react";
import { MicSelector, MicSelectorContent, MicSelectorEmpty, MicSelectorInput, MicSelectorItem, MicSelectorLabel, MicSelectorList, MicSelectorTrigger, MicSelectorValue, ModelSelector, ModelSelectorContent, ModelSelectorDialog, ModelSelectorEmpty, ModelSelectorGroup, ModelSelectorInput, ModelSelectorItem, ModelSelectorList, ModelSelectorLogo, ModelSelectorLogoGroup, ModelSelectorName, ModelSelectorSeparator, ModelSelectorShortcut, ModelSelectorTrigger, VoiceSelector, VoiceSelectorAccent, VoiceSelectorAge, VoiceSelectorAttributes, VoiceSelectorBullet, VoiceSelectorContent, VoiceSelectorDescription, VoiceSelectorDialog, VoiceSelectorEmpty, VoiceSelectorGender, VoiceSelectorGroup, VoiceSelectorInput, VoiceSelectorItem, VoiceSelectorList, VoiceSelectorName, VoiceSelectorPreview, VoiceSelectorSeparator, VoiceSelectorShortcut, VoiceSelectorTrigger } from "@harso/ui";
import type { ExampleState } from "./examples";

const models = [{ id: "balanced", name: "Balanced", provider: "Everyday", description: "Writing and everyday work", shortcut: "Fast" }, { id: "focus", name: "Focus", provider: "Everyday", description: "Deeper reasoning and analysis", shortcut: "Thoughtful" }, { id: "local", name: "On device", provider: "Private", description: "Offline, local tasks", shortcut: "Local" }];
const voices = [{ id: "maya", name: "Maya", gender: "Feminine", accent: "British", age: "Adult", description: "Warm, unhurried and clear." }, { id: "eli", name: "Eli", gender: "Masculine", accent: "American", age: "Adult", description: "Direct, calm and conversational." }, { id: "river", name: "River", gender: "Neutral", accent: "Australian", age: "Adult", description: "Bright, relaxed and expressive." }];
const microphones = [{ deviceId: "desk", label: "Studio microphone (1234:abcd)" }, { deviceId: "built-in", label: "Built-in microphone" }, { deviceId: "headset", label: "Wireless headset" }];

export function SelectorsExample({ component, state = "default" }: { component: string; state?: ExampleState }) {
  const [scenario, setScenario] = useState("ready");
  const [selected, setSelected] = useState<string | null>(component === "ModelSelector" ? "balanced" : component === "VoiceSelector" ? "maya" : "desk");
  const [preview, setPreview] = useState<string | null>(null);
  const [alternative, setAlternative] = useState(false);
  const [request, setRequest] = useState("");
  const currentScenario = state === "default" ? scenario : state;
  const empty = currentScenario === "empty" || currentScenario === "denied";
  const loading = currentScenario === "loading";
  const error = currentScenario === "error";
  const long = currentScenario === "long-content";
  const common = { value: selected, disabled: currentScenario === "disabled", readOnly: currentScenario === "read-only", onValueChange: (value: string) => { setRequest(value); if (currentScenario !== "host-refusal") setSelected(value); } };
  const title = component === "ModelSelector" ? "A little more possibility." : component === "VoiceSelector" ? "Find your conversational rhythm." : "Make yourself heard.";
  const suffix = long ? " — an intentionally extended descriptive label to test wrapping on a small screen" : "";
  const controls = <div className="hk-selector-demo-controls"><label>Scenario <select aria-label="Selector scenario" value={scenario} disabled={state !== "default"} onChange={event => { setScenario(event.target.value); setRequest(""); }}><option value="ready">Ready</option><option value="empty">Empty</option><option value="loading">Loading</option><option value="error">Error</option><option value="disabled">Disabled</option><option value="read-only">Read only</option><option value="host-refusal">Host refuses selection</option><option value="denied">Permission denied</option><option value="long-content">Long content</option></select></label>{component !== "MicSelector" && <label><input type="checkbox" checked={alternative} onChange={event => setAlternative(event.target.checked)} /> Alternative dialog part</label>}</div>;
  const status = <>{loading && <p role="status">Loading options…</p>}{error && <p role="alert">Options could not be refreshed. The previous choices remain available.</p>}</>;
  const ModelSurface = alternative ? ModelSelectorDialog : ModelSelectorContent;
  const VoiceSurface = alternative ? VoiceSelectorDialog : VoiceSelectorContent;
  return <section className="hk-selector-demo"><h3 className="hk-selector-demo-heading">{title}</h3><p className="hk-selector-demo-copy">A quiet choice, with the details one step away. These options and host responses are synthetic; no model, microphone or audio service is contacted.</p>{controls}
    {component === "ModelSelector" ? <ModelSelector {...common}><ModelSelectorTrigger>{models.find(model => model.id === selected)?.name ?? "Choose a model"}</ModelSelectorTrigger><ModelSurface title="Choose how you work"><ModelSelectorInput placeholder="Search models or capabilities" />{status}<ModelSelectorList>{["Everyday", "Private"].map(provider => <ModelSelectorGroup key={provider} heading={provider}>{!empty && models.filter(model => model.provider === provider).map(model => <ModelSelectorItem key={model.id} value={model.id} keywords={[model.description, provider]}><ModelSelectorLogoGroup><ModelSelectorLogo aria-hidden="true">{model.name.slice(0, 1)}</ModelSelectorLogo></ModelSelectorLogoGroup><ModelSelectorName>{model.name}{suffix}</ModelSelectorName><ModelSelectorShortcut>{model.shortcut}</ModelSelectorShortcut></ModelSelectorItem>)}</ModelSelectorGroup>)}<ModelSelectorEmpty /></ModelSelectorList><ModelSelectorSeparator /><p className="hk-selector-demo-copy">Your host determines availability. Selection does not start a run.</p></ModelSurface></ModelSelector>
      : component === "VoiceSelector" ? <VoiceSelector {...common}><VoiceSelectorTrigger>{voices.find(voice => voice.id === selected)?.name ?? "Choose a voice"}</VoiceSelectorTrigger><VoiceSurface title="A voice that feels natural"><VoiceSelectorInput placeholder="Search names, accents or qualities" />{status}<VoiceSelectorList><VoiceSelectorGroup heading="Conversation">{!empty && voices.map(voice => <div className="hk-selector-row" key={voice.id}><VoiceSelectorItem value={voice.id} keywords={[voice.accent, voice.gender, voice.description]}><VoiceSelectorName>{voice.name}{suffix}</VoiceSelectorName><VoiceSelectorShortcut>{voice.age}</VoiceSelectorShortcut></VoiceSelectorItem><VoiceSelectorPreview aria-label={`Preview ${voice.name}`} loading={loading} playing={preview === voice.id} onPlay={() => setPreview(preview === voice.id ? null : voice.id)} /><div className="hk-selector-row-details"><VoiceSelectorAttributes><VoiceSelectorGender>{voice.gender}</VoiceSelectorGender><VoiceSelectorBullet /><VoiceSelectorAccent>{voice.accent}</VoiceSelectorAccent><VoiceSelectorBullet /><VoiceSelectorAge>{voice.age}</VoiceSelectorAge></VoiceSelectorAttributes><VoiceSelectorDescription>{voice.description}</VoiceSelectorDescription></div></div>)}</VoiceSelectorGroup><VoiceSelectorEmpty /></VoiceSelectorList><VoiceSelectorSeparator /><p className="hk-selector-demo-copy">Preview controls demonstrate host state only; this example plays no audio.</p></VoiceSurface></VoiceSelector>
      : <MicSelector {...common} devices={empty ? [] : microphones.map(device => ({ ...device, label: device.label + suffix }))} permission={currentScenario === "denied" ? "denied" : "unknown"} loading={loading} error={error ? "Microphone service unavailable. Your permissions have not changed." : null} loadDevices={() => setRequest("Microphone access requested from the host (demo only)")}><MicSelectorTrigger><MicSelectorValue /></MicSelectorTrigger><MicSelectorContent><MicSelectorInput placeholder="Search microphones" /><MicSelectorList>{devices => devices.map(device => <MicSelectorItem value={device.deviceId} key={device.deviceId}><MicSelectorLabel device={device} /></MicSelectorItem>)}</MicSelectorList><MicSelectorEmpty /></MicSelectorContent></MicSelector>}
    <output className="hk-selector-demo-copy" aria-live="polite">{request ? `Host request: ${request}${currentScenario === "host-refusal" ? ". Selection kept unchanged." : ""}` : "Ready when you are."}</output>
  </section>;
}
