import { useState } from "react";
import { Button, Checkbox, StackTrace, StackTraceActions, StackTraceContent, StackTraceCopyButton, StackTraceError, StackTraceErrorMessage, StackTraceErrorType, StackTraceExpandButton, StackTraceFrames, StackTraceHeader } from "@harso/ui";
import type { ExampleState } from "./examples";

export const stackTraceExports = ["StackTrace"] as const;
export type StackTraceExport = typeof stackTraceExports[number];
export const stackTraceNotes = { StackTrace: { behavior: "A quiet supplied error summary with explicit, separate copy and disclosure actions. Standard JavaScript/Node locations become host callbacks only when selected; unknown lines remain literal. Internal frames can be hidden with an honest count. This example uses synthetic data and never opens or executes files. Host redaction, recovery and data authority stay outside the kit.", example: '<StackTrace trace={trace} onFilePathClick={inspect}><StackTraceHeader><StackTraceError><StackTraceErrorType /><StackTraceErrorMessage /></StackTraceError><StackTraceActions><StackTraceCopyButton /><StackTraceExpandButton /></StackTraceActions></StackTraceHeader><StackTraceContent><StackTraceFrames /></StackTraceContent></StackTrace>' } };

export function StackTraceExample({ state }: { state: ExampleState }) {
  const [open, setOpen] = useState(false), [hold, setHold] = useState(false), [internals, setInternals] = useState(true), [empty, setEmpty] = useState(false), [alternate, setAlternate] = useState(false), [selection, setSelection] = useState("");
  const path = state === "long-content" ? "/src/conversation/continuous-work-progress-with-accessible-decisions-and-unabridged-names.tsx" : "/src/work/progress.ts";
  const trace = empty ? "" : `${alternate ? "RangeError: The supplied position is outside this result" : "TypeError: Cannot read the work result"}\n    at renderResult (${path}:42:8)\n    at C:\\workspace\\app.ts:12:4\n    at https://example.invalid:8080/app.js:8:2\n    at node:internal/process/task_queues:105:5\n    at run (/app/node_modules/queue/index.js:7:3)\nCaused by: result was not supplied\n    at unresolved (native)`;
  return <div className="hkl-example-stack"><div className="hk-data-toolbar"><Checkbox label="Hold trace disclosure" checked={hold} onChange={event => setHold(event.target.checked)} /><Checkbox label="Show internal frames" checked={internals} onChange={event => setInternals(event.target.checked)} /><Checkbox label="Empty trace" checked={empty} onChange={event => setEmpty(event.target.checked)} /><Button size="small" onClick={() => { setAlternate(value => !value); setSelection(""); }}>Change sample trace</Button></div><StackTrace trace={trace} aria-label="Example stack trace" open={open} onOpenChange={next => { if (!hold) setOpen(next); }} disabled={state === "disabled"} onFilePathClick={(file, line, column) => setSelection(`${file}:${line}:${column}`)}><StackTraceHeader><StackTraceError><StackTraceErrorType /><StackTraceErrorMessage /></StackTraceError><StackTraceActions><StackTraceCopyButton /><StackTraceExpandButton /></StackTraceActions></StackTraceHeader><StackTraceContent maxHeight={280}><StackTraceFrames showInternalFrames={internals} /></StackTraceContent></StackTrace><p role="status">{selection ? `Selected ${selection} — host callback only; no file opened.` : "No frame selected."}</p></div>;
}
