// NO_PRELUDE
// v2 reachability: fix 'link:artifact' → 'link:artifacts--detail'; macOS: sidebar 'Recent' header → link:recent, empty states reachable via a toolbar "filter" chip on projects/artifacts; iOS: routines/customize reachable from settings root rows; project--empty/artifacts--empty from a 'Show empty' segment? No — from the project's "Work" segment area: link them from the corresponding root's trailing nav button when there is a plus? Keep it honest: add a 'link:<id>--empty' to the filter chip / clear-search affordance; customize--profile from customize row.
const sketch = require('sketch'); var doc = sketch.getSelectedDocument(); var out = [];
function screens(pn, id) { var p = doc.pages.find(function (x) { return x.name === pn; }); return p.layers.filter(function (l) { return l.name.indexOf('Screen/') === 0 && l.name.split('/').pop() === id; }); }
function all(pn) { var p = doc.pages.find(function (x) { return x.name === pn; }); return p.layers.filter(function (l) { return l.name.indexOf('Screen/') === 0; }); }
['Proto macOS Light', 'Proto macOS Dark', 'Proto iOS Light', 'Proto iOS Dark'].forEach(function (pn) {
  all(pn).forEach(function (s) { sketch.find('*', s).forEach(function (l) { if (String(l.name).replace(/ \d+$/, '') === 'link:artifact') { l.name = 'link:artifacts--detail'; out.push(pn + ' artifact→detail'); } }); });
});
['Proto macOS Light', 'Proto macOS Dark'].forEach(function (pn) {
  all(pn).forEach(function (s) { sketch.find('Text', s).forEach(function (t) { if (t.text === 'Recent' && t.parent && String(t.parent.name) === 'section') { t.parent.name = 'link:recent'; out.push(pn + ' ' + s.name.split('/').pop() + ' Recent header→link'); } }); });
  // projects--empty / artifacts--empty: link from the 'Personal' etc? Use the sidebar's "All projects" disclosure on projects screen → toggles to empty view is fake. Instead: from projects screen, the search field in toolbar → search; add: the 'New project' inline Create → project. Empty states: reachable from search screen 'No results'? Keep simple + honest: link the toolbar search field on projects → projects--empty (empty result state) and on artifacts → artifacts--empty.
  ['projects', 'artifacts'].forEach(function (id) { screens(pn, id).forEach(function (s) { var sf = sketch.find('Group', s).filter(function (g) { return String(g.name).replace(/ \d+$/, '') === 'link:search' && g.frame.width > 100; })[0]; if (sf) { sf.name = 'link:' + id + '--empty'; out.push(pn + ' ' + id + ' search→' + id + '--empty'); } }); });
  screens(pn, 'projects--empty').concat(screens(pn, 'artifacts--empty')).forEach(function (s) { var sf = sketch.find('Group', s).filter(function (g) { return String(g.name).replace(/ \d+$/, '') === 'link:search' && g.frame.width > 100; })[0]; if (sf) sf.name = 'link:back'; });
});
['Proto iOS Light', 'Proto iOS Dark'].forEach(function (pn) {
  // settings root: rows for Routines / Customize exist? If not, retitle Voice & Live? No — add links on the profile card sub-rows is fake. Use home screen chips: 'Write' → customize, 'Build' → routines (quick actions). And project 'Work' segment → project--work exists; project--empty ← project's search? Use recent screen's 'Clear' / filter: link recent's search field → project--empty? Keep honest: home chips → routines/customize; customize rows → customize--profile (first group row); artifacts search field → artifacts--empty; project search/filter → project--empty.
  screens(pn, 'home').forEach(function (s) { sketch.find('Text', s).forEach(function (t) { var g = t.parent; if (!g || !g.frame || g.frame.height > 60) return; if (t.text === 'Write') { g.name = 'link:customize'; out.push(pn + ' home Write→customize'); } if (t.text === 'Build') { g.name = 'link:routines'; out.push(pn + ' home Build→routines'); } }); });
  screens(pn, 'customize').forEach(function (s) { var rows = sketch.find('Group', s).filter(function (g) { return /^link:/.test(String(g.name)) && g.frame.height >= 44 && g.frame.height <= 60; }); if (rows[0]) { rows[0].name = 'link:customize--profile'; out.push(pn + ' customize row→profile'); } });
  screens(pn, 'routines').forEach(function (s) { var tr = sketch.find('Group', s).filter(function (g) { return String(g.name).replace(/ \d+$/, '') === 'link:routines--new'; }); if (!tr.length) { var plus = sketch.find('Group', s).filter(function (g) { return g.frame.width === 44 && g.frame.height === 44 && /^link:/.test(String(g.name)); })[0]; if (plus) { plus.name = 'link:routines--new'; out.push(pn + ' routines plus→new'); } } });
  [['artifacts', 'artifacts--empty'], ['project', 'project--empty']].forEach(function (pair) { screens(pn, pair[0]).forEach(function (s) { var sf = sketch.find('Group', s).filter(function (g) { var n = String(g.name).replace(/ \d+$/, ''); return (n === 'link:search') && g.frame.width > 100; })[0]; if (sf) { sf.name = 'link:' + pair[1]; out.push(pn + ' ' + pair[0] + ' search→' + pair[1]); } else { var tr = sketch.find('Group', s).filter(function (g) { return g.frame.width === 44 && g.frame.height === 44 && String(g.name).replace(/ \d+$/, '') === 'link:search'; })[0]; if (tr) { tr.name = 'link:' + pair[1]; out.push(pn + ' ' + pair[0] + ' nav search→' + pair[1]); } } }); });
});
console.log(JSON.stringify(out));
