var page = H.page('Proto scratch'); page.layers.forEach(function (l) { l.remove(); });
var app = 'Light/Clean';
var s = H.screen({ page: page, platform: 'macos', app: app, id: 'smoke-conversation', w: 1440, h: 900, x: 0, y: 0 });
var w = H.macWindow(s, app, { active: 'conversation', title: 'Move the billing webhook handler', subtitle: 'Personal · 14 turns', tools: [['link:conversation--menu', 'ellipsis'], ['share', 'square_and_arrow_up']], inspector: 'Work', inspectorToggle: 'conversation' });
var m = w.main; m.stackLayout.alignItems = sketch.StackLayout.AlignItems.Center; m.stackLayout.padding = { top: 24, right: 0, bottom: 24, left: 0 };
var thread = H.frame({ name: 'thread', parent: m, dir: 'col', gap: 20, pad: 0, w: 720, align: sketch.StackLayout.AlignItems.Start, justify: sketch.StackLayout.JustifyContent.End }); thread.verticalSizing = sketch.FlexSizing.Fill;
function user(t) { var r = H.frame({ name: 'user', parent: thread, dir: 'row', pad: 0, w: 720, justify: sketch.StackLayout.JustifyContent.End }); var b = H.frame({ name: 'bubble', parent: r, pad: { top: 10, right: 14, bottom: 10, left: 14 }, radius: 16, fill: H.sw(app, 'accent-soft') }); H.text({ parent: b, text: t, size: 14, weight: 5, color: H.sw(app, 'ink'), w: 420 }); b.stackLayout.apply(); r.stackLayout.apply(); }
function ai(t) { var r = H.frame({ name: 'assistant', parent: thread, dir: 'row', gap: 12, pad: 0, w: 720, align: sketch.StackLayout.AlignItems.Start }); var av = H.frame({ name: 'mark', parent: r, pad: 0, w: 24, h: 24, radius: 12, fill: H.sw(app, 'accent-soft'), justify: sketch.StackLayout.JustifyContent.Center }); H.sf(av, 'sparkles', { size: 12, weight: 8, color: H.hex(app, 'accent') }); av.stackLayout.apply(); H.text({ parent: r, text: t, size: 14, weight: 5, color: H.sw(app, 'ink'), w: 640 }); H.order(r); }
user('Move the billing webhook handler out of the API package into its own service so retries stop blocking checkout.');
ai('I traced the handler: it runs inline in POST /api/billing/webhook and a Stripe retry storm on Tuesday blocked checkout for 40s. I\'ll extract it into services/billing-webhook with an idempotency table keyed on event.id, keep the route as a thin enqueue, and add a replay command.\n\nBefore I touch the schema I need one decision: should replays re-run side effects (emails), or only re-derive ledger state?');
user('Ledger only. Never resend emails.');
ai('Done — 3 files changed, 2 tests added. Running the suite now.');
var run = H.frame({ name: 'run', parent: thread, dir: 'row', gap: 10, pad: { top: 10, right: 14, bottom: 10, left: 14 }, w: 720, h: 44, radius: 10, fill: H.sw(app, 'surface'), border: H.sw(app, 'line') }); H.sf(run, 'terminal', { size: 14, weight: 7, color: H.hex(app, 'accent') }); H.text({ parent: run, text: 'npm test — 212 passed, 4 running', size: 13, weight: 6, color: H.sw(app, 'ink'), mono: true }); var sp = H.frame({ name: 'spacer', parent: run, pad: 0, h: 1 }); sp.horizontalSizing = sketch.FlexSizing.Fill; H.text({ parent: run, text: '0:42', size: 12, weight: 5, color: H.sw(app, 'tertiary'), mono: true }); H.order(run);
H.order(thread);
var comp = H.frame({ name: 'composer', parent: m, dir: 'col', gap: 8, pad: { top: 12, right: 12, bottom: 10, left: 14 }, w: 720, radius: 14, fill: H.sw(app, 'surface'), border: H.sw(app, 'line-strong'), shadow: { color: '#00000012', blur: 12, spread: 0, x: 0, y: 4 }, align: sketch.StackLayout.AlignItems.Start });
H.text({ parent: comp, text: 'Reply…', size: 14, weight: 5, color: H.sw(app, 'tertiary'), w: 690 });
var row = H.frame({ name: 'row', parent: comp, dir: 'row', gap: 4, pad: 0, w: 694 }); H.sfBtn(row, 'attach', 'plus', app, { w: 28, h: 28, size: 14 }); H.sfBtn(row, 'mention', 'link', app, { w: 28, h: 28, size: 13 }); var sp2 = H.frame({ name: 'spacer', parent: row, pad: 0, h: 1 }); sp2.horizontalSizing = sketch.FlexSizing.Fill; H.sfBtn(row, 'link:conversation--voice', 'mic', app, { w: 28, h: 28, size: 14, color: H.sw(app, 'ink') }); H.sfBtn(row, 'send', 'arrow_up', app, { w: 28, h: 28, radius: 14, size: 13, weight: 9, fill: H.sw(app, 'accent'), color: '#ffffff' }); H.order(row); H.order(comp);
// inspector content
var ib = H.frame({ name: 'inspector-body', parent: w.inspector, dir: 'col', gap: 6, pad: 16, w: 320, align: sketch.StackLayout.AlignItems.Start });
function sect(label) { var h = H.frame({ name: 'section', parent: ib, pad: { top: ib.layers.length ? 18 : 4, right: 8, bottom: 6, left: 8 }, w: 288 }); H.sft({ parent: h, text: label.toUpperCase(), size: 11, weight: 8, color: H.sw(app, 'tertiary') }); h.stackLayout.apply(); }
sect('Changed files');
[['doc', 'services/billing-webhook/index.ts', '+184'], ['doc', 'api/routes/billing.ts', '−92'], ['doc', 'db/migrations/0142_webhook_events.sql', '+31']].forEach(function (f) { var r = H.frame({ name: 'file', parent: ib, dir: 'row', gap: 8, pad: { top: 0, right: 8, bottom: 0, left: 8 }, w: 288, h: 28, radius: 6 }); H.sf(r, f[0], { size: 13, weight: 6, color: H.sw(app, 'secondary'), w: 16 }); H.text({ parent: r, text: f[1], size: 12, weight: 5, color: H.sw(app, 'ink'), mono: true, w: 200 }); var sp = H.frame({ name: 'spacer', parent: r, pad: 0, h: 1 }); sp.horizontalSizing = sketch.FlexSizing.Fill; H.text({ parent: r, text: f[2], size: 11, weight: 6, color: f[2][0] === '+' ? H.sw(app, 'positive') : H.sw(app, 'negative'), mono: true }); H.order(r); });
sect('Approvals');
var ap = H.frame({ name: 'link:conversation--approval', parent: ib, dir: 'row', gap: 10, pad: 12, w: 288, radius: 10, fill: H.alpha(H.hex(app, 'attention'), 0.16), border: H.alpha(H.hex(app, 'attention'), 0.35), align: sketch.StackLayout.AlignItems.Start }); H.sf(ap, 'exclamation_triangle', { size: 14, weight: 7, color: H.hex(app, 'attention') }); var apt = H.frame({ name: 'text', parent: ap, dir: 'col', gap: 2, pad: 0, align: sketch.StackLayout.AlignItems.Start }); H.text({ parent: apt, text: 'Run migration on staging', size: 13, weight: 6, color: H.sw(app, 'ink') }); H.text({ parent: apt, text: 'Waiting for you · 2 min', size: 12, weight: 5, color: H.sw(app, 'secondary') }); H.order(apt); H.order(ap);
sect('Session');
[['clock','Started 14:02 · 38 min'],['cube','claude-fable-5-1 · 41k tokens'],['folder','~/Developer/products/weave-cloud']].forEach(function (k) { var r = H.frame({ name: 'kv', parent: ib, dir: 'row', gap: 8, pad: { top: 0, right: 8, bottom: 0, left: 8 }, w: 288, h: 26 }); H.sf(r, k[0], { size: 12, weight: 6, color: H.sw(app, 'tertiary'), w: 16 }); H.text({ parent: r, text: k[1], size: 12, weight: 5, color: H.sw(app, 'secondary') }); H.order(r); });
H.order(ib);
w.finish();
console.log(JSON.stringify({ id: String(s.id) }));
