var APP="Dark/Clean";var ID="projects";
var ids=['projects','projects--new','project','recent','artifacts','artifacts--detail','routines','routines--new','customize','settings','settings-account','settings-devices','settings-general','settings-appearance','settings-voice','settings-notifications','settings-connections','settings-billing','settings-privacy','settings-shortcuts','settings-about','settings--sign-out','settings-billing--plan','project--empty','artifacts--empty','project--work','artifacts--code','artifacts--share','customize--profile'];
var originalFrame=H.frame; H.frame=function(o){if(!o.name)o.name='content';return originalFrame(o);};
var page=H.page('Proto iOS '+APP.split('/')[0]);
page.layers.slice().filter(l=>l.name==='Screen/ios/'+APP+'/'+ID || (l.name.indexOf('caption/')===0&&l.name.endsWith('/'+ID))).forEach(l=>l.remove());
var base=ID.split('--')[0], cat=base.replace('settings-','');
var titles={projects:'Projects',project:'Weave Cloud',recent:'Recent',artifacts:'Artifacts',routines:'Routines',customize:'Customize',settings:'Settings',account:'Account',devices:'Devices',general:'General',appearance:'Appearance',voice:'Voice & Live',notifications:'Notifications',connections:'Connections',billing:'Usage & Billing',privacy:'Data & Privacy',shortcuts:'Shortcuts',about:'About'};
var root=['projects','recent','settings'].includes(base), detail=ID==='artifacts--detail'||ID==='artifacts--code'||ID==='artifacts--share';
var r=H.iosScreen({page:page,app:APP,id:ID,x:ids.indexOf(ID)*510,y:1004,title:detail?'Webhook rollout':titles[cat]||titles[base],large:root||(['artifacts','routines'].includes(base)&&!detail),back:root?false:true,tab:root?base:false,gap:20,trailing:base==='projects'?[['projects--new','plus']]:base==='routines'?[['routines--new','plus']]:detail?[['artifacts--share','square_and_arrow_up']]:[]});var b=r.body;
function group(rows,o,p){return H.iosGroup(p||b,APP,rows,o||{});}
function txt(s,size,p,w){return H.sft({parent:p||b,text:s,size:size||15,weight:5,color:H.sw(APP,'secondary'),w:w||358});}
function seg(labels,links,selected,p){var f=H.frame({parent:p||b,name:'segmented-control',dir:'row',pad:2,gap:2,w:358,h:32,radius:9,fill:H.alpha(H.hex(APP,'ink'),.08)});labels.forEach((s,i)=>{var q=H.frame({parent:f,name:'link:'+links[i],pad:0,w:(354-(labels.length-1)*2)/labels.length,h:28,radius:7,fill:i===selected?H.sw(APP,'surface'):null,justify:sketch.StackLayout.JustifyContent.Center});H.sft({parent:q,text:s,size:13,weight:i===selected?7:5,color:H.sw(APP,'ink')});q.stackLayout.apply();});H.order(f);}
function pill(label,link,p){var q=H.frame({parent:p||b,name:'link:'+link,w:358,h:50,pad:0,radius:25,fill:H.sw(APP,'accent'),justify:sketch.StackLayout.JustifyContent.Center});H.sft({parent:q,text:label,size:17,weight:7,color:'#ffffff'});q.stackLayout.apply();}
function empty(title,body,link,label){var q=H.frame({parent:b,name:'empty-state',dir:'col',pad:{top:70,right:16,bottom:30,left:16},gap:16,w:358,align:sketch.StackLayout.AlignItems.Center});H.sf(q,'sparkles',{size:44,color:H.sw(APP,'accent')});H.sft({parent:q,text:title,size:22,weight:7,color:H.sw(APP,'ink'),w:326,align:sketch.Text.Alignment.center});H.sft({parent:q,text:body,size:15,weight:5,color:H.sw(APP,'secondary'),w:326,align:sketch.Text.Alignment.center});H.order(q);pill(label,link);}
var settingsRows=[['devices','display','#5e5ce6','Devices'],['general','gear','#8e8e93','General'],['appearance','sun','#0a84ff','Appearance'],['voice','mic','#ff375f','Voice & Live'],['notifications','bell','#ff453a','Notifications'],['connections','link','#30b858','Connections'],['billing','chart_bar','#ef9200','Usage & Billing'],['privacy','lock','#36a8cd','Data & Privacy'],['shortcuts','command','#af52de','Shortcuts'],['about','info_circle','#8e8e93','About']];
if(base==='settings'){
 b.stackLayout.gap=12;
 var prof=H.frame({name:'link:settings-account',parent:b,dir:'row',gap:12,pad:12,w:358,h:68,radius:12,fill:H.sw(APP,'surface')});var av=H.frame({name:'avatar',parent:prof,pad:0,w:44,h:44,radius:22,fill:H.sw(APP,'accent'),justify:sketch.StackLayout.JustifyContent.Center});H.sft({parent:av,text:'AB',size:17,weight:7,color:'#ffffff'});av.stackLayout.apply();var pt=H.frame({parent:prof,dir:'col',gap:2,pad:0});H.sft({parent:pt,text:'Abhi Bansal',size:20,weight:6,color:H.sw(APP,'ink')});H.sft({parent:pt,text:'Pro · Straits Lab',size:13,weight:5,color:H.sw(APP,'tertiary')});H.order(pt);var sp=H.frame({parent:prof,pad:0,h:1});sp.horizontalSizing=sketch.FlexSizing.Fill;H.sf(prof,'chevron_right',{size:14,color:H.sw(APP,'tertiary')});H.order(prof);
 [settingsRows.slice(0,5),settingsRows.slice(5)].forEach(rows=>group(rows.map(a=>({link:'settings-'+a[0],glyph:a[1],tint:a[2],title:a[3],h:33}))));group([{title:'Sign Out',link:'settings--sign-out',destructive:true,chevron:false,h:40}]);
}else if(base==='projects'){
 group([{title:'Weave Cloud',sub:'12 conversations · 3 running',glyph:'folder',tint:'#ed941d',link:'project',h:68},{title:'Personal',sub:'8 conversations · Updated today',glyph:'folder',tint:'#0a84ff',link:'project',h:68},{title:'Straits Lab',sub:'24 conversations · 1 running',glyph:'folder',tint:'#8e5de8',link:'project',h:68}],{header:'Pinned'});group([{title:'Aheli Operations',sub:'16 conversations · Updated yesterday',glyph:'folder',tint:'#28a87b',link:'project',h:68},{title:'Research',sub:'7 conversations · Updated Monday',glyph:'folder',tint:'#e7667c',link:'project',h:68}],{header:'All projects',footer:'Project memory keeps decisions and files together.'});
}else if(base==='project'){
 seg(['Conversations','Work'],['project','project--work'],ID==='project--work'?1:0);
 if(ID==='project--empty')empty('A fresh place to think','Start a conversation to give this project its first decision.','new-conversation','Start conversation');
 else if(ID==='project--work')group([{title:'Billing webhook migration',sub:'Running · 4 of 6 steps',glyph:'bolt',tint:'#ed941d',link:'activity--work',h:68},{title:'iOS settings audit',sub:'Waiting for approval · 2 min ago',glyph:'hourglass',tint:'#8e5de8',link:'activity--work',h:68},{title:'API regression tests',sub:'Completed · 148 tests passed',glyph:'checkmark',tint:'#28a87b',link:'activity--work',h:68}],{header:'Today',footer:'Work continues when you leave this screen.'});
 else {group([{title:'Move the billing webhook',sub:'Handler extracted · 3 min ago',link:'conversation',h:68},{title:'Review the iOS settings flow',sub:'11 categories mapped · 24 min ago',link:'conversation',h:68},{title:'Cut the Mac build size',sub:'Framework audit · 1 hour ago',link:'conversation',h:68}],{header:'Today'});group([{title:'Draft the Q3 investor update',sub:'Revenue narrative ready · Yesterday',link:'conversation',h:68},{title:'Verify production cutover',sub:'Health checks passed · Monday',link:'conversation',h:68}],{header:'Earlier'});}
}else if(base==='recent'){
 group([{title:'Move the billing webhook',sub:'Weave Cloud · 9:38 AM',link:'conversation',h:68},{title:'Review the iOS settings flow',sub:'Weave Cloud · 9:17 AM',link:'conversation',h:68},{title:'Draft the Q3 investor update',sub:'Straits Lab · 8:42 AM',link:'conversation',h:68}],{header:'Today'});group([{title:'Cut the Mac build size',sub:'Weave Cloud · 4:28 PM',link:'conversation',h:68},{title:'Supplier payment review',sub:'Aheli Operations · 2:10 PM',link:'conversation',h:68}],{header:'Yesterday'});
 var swipe=H.frame({parent:b,name:'swipe-revealed',dir:'row',gap:0,pad:0,w:358,h:56,radius:12,fill:H.sw(APP,'surface'),clip:true});var lab=H.frame({parent:swipe,pad:16,w:280,h:56});H.sft({parent:lab,text:'Weekly research digest',size:17,weight:5,color:H.sw(APP,'ink')});lab.stackLayout.apply();var del=H.frame({parent:swipe,name:'link:conversation--delete',w:78,h:56,pad:0,fill:H.sw(APP,'negative'),justify:sketch.StackLayout.JustifyContent.Center});H.sf(del,'trash',{size:20,color:'#ffffff'});del.stackLayout.apply();H.order(swipe);
}else if(base==='artifacts'){
 if(ID==='artifacts--empty')empty('Your work, collected','Save a document, chart or code file from any conversation.','new-conversation','Create something');
 else if(detail){seg(['Preview','Code'],['artifacts--detail','artifacts--code'],ID==='artifacts--code'?1:0);group([{title:'Webhook rollout',sub:'Markdown · 4.2 KB · Today, 9:38 AM',glyph:'doc',tint:'#ed941d',chevron:false,h:68}]);var paper=H.frame({parent:b,name:'document-preview',dir:'col',gap:16,pad:20,w:358,radius:12,fill:H.sw(APP,'surface'),align:sketch.StackLayout.AlignItems.Start});H.sft({parent:paper,text:ID==='artifacts--code'?'webhook-rollout.md':'Billing webhook rollout',size:22,weight:7,color:H.sw(APP,'ink'),w:318});txt(ID==='artifacts--code'?'# Billing webhook rollout\n\n## Release checklist\n- [x] Extract handler\n- [x] Add signature validation\n- [x] Run 148 regression tests\n- [ ] Deploy canary\n\nPOST /api/billing/webhook\nIdempotency: event.id\nRetries: exponential backoff':'The billing handler now lives in the payments package, with signature validation at the edge.\n\nRelease checklist\n\n1. Extract handler — complete\n2. Validate signatures — complete\n3. Run 148 tests — passed\n4. Deploy canary — awaiting approval\n\nRollback: restore the previous API image and replay queued events.',15,paper,318);H.order(paper);}
 else {seg(['All','Documents','Code'],['artifacts','artifacts','artifacts'],0);var cards=[['Webhook rollout','Markdown · 3 min ago','doc','#ed941d'],['Revenue trend','Chart · 24 min ago','chart_bar','#28a87b'],['Invoice matcher','TypeScript · 1 hour ago','chevron_left_right','#8e5de8'],['Q3 investor update','Document · Yesterday','doc_on_doc','#0a84ff'],['Mobile navigation','Design · Yesterday','rectangle_3_group','#e7667c'],['Release checklist','Markdown · Monday','list_bullet','#28a87b']];for(var i=0;i<3;i++){var row=H.frame({parent:b,dir:'row',gap:14,pad:0,w:358});cards.slice(i*2,i*2+2).forEach(a=>{var card=H.frame({parent:row,name:'link:artifacts--detail',dir:'col',gap:8,pad:10,w:172,radius:12,fill:H.sw(APP,'surface'),align:sketch.StackLayout.AlignItems.Start});var thumb=H.frame({parent:card,w:152,h:82,pad:0,radius:8,fill:H.alpha(a[3],.12),justify:sketch.StackLayout.JustifyContent.Center});H.sf(thumb,a[2],{size:32,color:a[3]});thumb.stackLayout.apply();H.sft({parent:card,text:a[0],size:15,weight:7,color:H.sw(APP,'ink'),w:152});H.sft({parent:card,text:a[1],size:11,weight:5,color:H.sw(APP,'tertiary'),w:152});H.order(card);});H.order(row);}}
}else if(base==='routines'){
 group([{title:'Morning briefing',sub:'Every day · 8:00 AM',detail:'●',glyph:'clock',tint:'#ed941d',link:'routines--new',h:72},{title:'Weekly project review',sub:'Fridays · 5:00 PM',detail:'●',glyph:'clock',tint:'#28a87b',link:'routines--new',h:72},{title:'Invoice reminders',sub:'Weekdays · 10:00 AM',detail:'●',glyph:'clock',tint:'#0a84ff',link:'routines--new',h:72}],{header:'Scheduled',footer:'Times use Singapore (GMT+8). Results appear in Activity.'});group([{title:'Research digest',sub:'Mondays · 9:00 AM',detail:'Paused',glyph:'pause',tint:'#8e8e93',link:'routines--new',h:72}],{header:'Paused'});
}else if(base==='customize'){
 if(ID==='customize--profile'){group([{title:'Name',detail:'General'},{title:'Tone',detail:'Direct'},{title:'Response length',detail:'Balanced'}],{header:'Personality',footer:'General is your default profile for new conversations.'});group([{title:'Remember preferences',toggle:true},{title:'Use project context',toggle:true},{title:'Confirm external actions',toggle:true}],{header:'Behavior'});}
 else {group([{title:'General',sub:'Selected profile',link:'customize--profile',glyph:'checkmark_circle_fill',tint:'#ed941d'},{title:'Engineering',link:'customize--profile',glyph:'terminal',tint:'#0a84ff'},{title:'Writing',link:'customize--profile',glyph:'pencil',tint:'#8e5de8'}],{header:'Profiles'});group([{title:'Voice',detail:'Juniper',link:'settings-voice'},{title:'Personality',detail:'Direct',link:'customize--profile'}],{header:'Make it yours'});group([{title:'Web research',toggle:true},{title:'Code execution',toggle:true},{title:'Calendar access',toggle:false}],{header:'Tools',footer:'Weave asks before a tool changes anything outside your workspace.'});}
}else{
 var configs={
 account:[[['Name','Abhi Bansal'],['Email','abhi@straitslab.com'],['Workspace','Straits Lab']],[['Sync across devices',true],['Require Face ID',true]],'Your conversations sync securely with your Straits Lab account.'],
 devices:[[['This iPhone','Active now'],['MacBook Pro','Last seen 9:36 AM'],['Active sessions','2 devices']],[['Notify on new sign-in',true],['Approve new devices',true]],'Only approved devices can access your project memory.'],
 general:[[['Language','English'],['Region','Singapore'],['Start screen','Home']],[['Restore conversations',true],['Haptic feedback',true],['Open links in browser',false]],'These preferences apply to Weave on this iPhone.'],
 appearance:[[['Text size','Default'],['App icon','Weave'],['Contrast','Standard']],[['Follow system',true],['Reduce motion',false],['Show project colors',true]],'System appearance switches automatically with your iPhone.'],
 voice:[[['Voice','Juniper'],['Language','English (SG)'],['Speaking rate','1.0×']],[['Auto-play replies',false],['Interrupt while speaking',true],['Live transcription',true]],'Audio is processed only during an active voice conversation.'],
 notifications:[[['Quiet hours','10 PM–8 AM'],['Delivery','Immediate'],['Preview','When unlocked']],[['Work completed',true],['Approval requests',true],['Routine results',true],['Product updates',false]],'Time-sensitive approval requests can bypass quiet hours.'],
 connections:[[['GitHub','Connected'],['Google Drive','Connected'],['Calendar','Connected'],['Linear','Connected']],[['Ask before sharing files',true],['Limit to this workspace',true]],'Connected services receive only the information a task needs.'],
 billing:[[['Usage','41,200 of 500,000 tokens'],['Plan','Pro · S$32/mo · renews 14 Oct 2026'],['Payment method','Visa ending 4242']],[['Usage alerts',true],['Email receipts',true]],'Usage resets on 14 Oct 2026. Prices are in Singapore dollars.'],
 privacy:[[['History retention','90 days'],['Storage on device','248 MB'],['Last export','12 Sep 2026']],[['Improve Weave',false],['Share diagnostics',false],['Encrypt project memory',true]],'Your conversations are not used to train models without permission.'],
 shortcuts:[[['New conversation','Action Button'],['Start voice','Siri'],['Search Weave','Spotlight']],[['Show in Spotlight',true],['Allow Siri requests',true],['Quick actions',true]],'Say “Ask Weave” to start a hands-free conversation.'],
 about:[[['Version','1.4.0 (148)'],['Built by','Straits Lab'],['Platform','iOS 27']],[['Automatic updates',true],['Send crash reports',false]],'Weave helps you turn conversations into work you can trust.']};
 var c=configs[cat];if(cat==='appearance')seg(['System','Light','Dark'],['settings-appearance','settings-appearance','settings-appearance'],0);
 group(c[0].map(a=>({title:a[0],sub:a[1],h:68,link:cat==='billing'&&a[0]==='Plan'?'settings-billing--plan':undefined,glyph:a[0]==='Plan'?'star':undefined,tint:'#ed941d'})),{header:cat==='billing'?'Your subscription':'Preferences'});
 group(c[1].map(a=>({title:a[0],toggle:a[1]})),{header:'Options',footer:c[2]});
 if(cat==='account')group([{title:'Sign Out',destructive:true,link:'settings--sign-out',chevron:false}]);if(cat==='about')group([{title:'Privacy Policy',link:'settings-privacy'},{title:'Open-source licenses',detail:'View',link:'settings-about'}]);
}
r.finish();
if(ID==='projects--new'||ID==='routines--new'){var isP=base==='projects';var sh=H.iosSheet(r.screen,APP,{title:isP?'New Project':'New Routine',done:'Create',doneLink:isP?'project':'routines',h:520});group(isP?[{title:'Name',detail:'Q4 planning'},{title:'Working directory',sub:'~/Developer/q4-planning',h:68}]:[{title:'Name',detail:'Morning briefing'},{title:'Schedule',detail:'Daily · 8:00 AM'},{title:'Time zone',detail:'Singapore'}],{header:'Details'},sh.body);group(isP?[{title:'Remember decisions',toggle:true},{title:'Sync project memory',toggle:true}]:[{title:'Project',detail:'Weave Cloud'},{title:'Notify when complete',toggle:true}],{footer:isP?'Keep related conversations, files and decisions in one place.':'Summarize open work, pending approvals and today’s calendar.'},sh.body);sh.finish();}
if(ID==='settings-billing--plan'){var sh=H.iosSheet(r.screen,APP,{title:'Choose Plan',h:548});seg(['Monthly','Annual'],['settings-billing--plan','settings-billing--plan'],0,sh.body);group([{title:'Free',sub:'50,000 tokens / month',detail:'S$0',h:68},{title:'Pro',sub:'500,000 tokens / month',detail:'S$32',glyph:'checkmark_circle_fill',tint:'#ed941d',h:68},{title:'Team',sub:'Shared workspace · 2 million tokens',detail:'S$96',h:68}],{footer:'Pro is your current plan. Changes apply at your next renewal on 14 Oct 2026.'},sh.body);pill('Change plan','settings-billing',sh.body);sh.finish();}
if(ID==='artifacts--share'){var sh=H.iosSheet(r.screen,APP,{title:'Share',cancelLabel:'Done',h:470});group([{title:'Webhook rollout',sub:'Markdown document · 4.2 KB',glyph:'doc',tint:'#ed941d',h:68}],{},sh.body);var icons=H.frame({parent:sh.body,dir:'row',gap:12,pad:0,w:358,h:74});[['AirDrop','wifi','#0a84ff'],['Messages','bubble','#28a87b'],['Mail','envelope','#0a84ff'],['Notes','book','#ed941d']].forEach(a=>{var q=H.frame({parent:icons,name:'link:back',dir:'col',gap:8,pad:0,w:80,h:74,align:sketch.StackLayout.AlignItems.Center});H.sf(q,a[1],{size:28,color:a[2]});H.sft({parent:q,text:a[0],size:12,weight:5,color:H.sw(APP,'ink')});H.order(q);});H.order(icons);group([{title:'Copy Link',glyph:'link',link:'back',chevron:false},{title:'Save to Files',glyph:'folder',link:'back',chevron:false}],{},sh.body);sh.finish();}
if(ID==='settings--sign-out'){H.macScrim(r.screen,APP);var act=H.frame({parent:r.screen,name:'action-sheet',dir:'col',gap:8,pad:0,w:358,align:sketch.StackLayout.AlignItems.Start});var panel=H.frame({parent:act,dir:'col',gap:0,pad:0,w:358,radius:14,fill:H.sw(APP,'surface'),clip:true});var msg=H.frame({parent:panel,pad:20,w:358,h:82});H.sft({parent:msg,text:'Sign out of Weave on this iPhone?',size:15,weight:5,color:H.sw(APP,'secondary'),w:318,align:sketch.Text.Alignment.center});msg.stackLayout.apply();var btn=H.frame({parent:panel,name:'link:signin',pad:0,w:358,h:56,justify:sketch.StackLayout.JustifyContent.Center});H.sft({parent:btn,text:'Sign Out',size:20,weight:5,color:H.sw(APP,'negative')});btn.stackLayout.apply();H.order(panel);var cancel=H.frame({parent:act,name:'link:back',pad:0,w:358,h:56,radius:14,fill:H.sw(APP,'surface'),justify:sketch.StackLayout.JustifyContent.Center});H.sft({parent:cancel,text:'Cancel',size:20,weight:7,color:H.sw(APP,'accent')});cancel.stackLayout.apply();H.order(act);act.frame.x=16;act.frame.y=608;act.moveToFront();}
function clean(l){if(l.name.indexOf('link:')===0)l.name=l.name.replace(/ \d+$/,'');if(l.layers)l.layers.forEach(clean);}clean(r.screen);r.screen.frame.x=ids.indexOf(ID)*510;r.screen.frame.y=1004;
console.log(JSON.stringify({id:ID,app:APP,frame:String(r.screen.id)}));