// Lane-local repair generators. Preserve screen IDs, positions and existing navigation.
var APP;
function all(l){var a=[l];(l.layers||[]).forEach(k=>a=a.concat(all(k)));return a;}
function named(l,n){return all(l).find(k=>k.name===n);}
function texts(l){return all(l).filter(k=>k.type==='Text');}
function replace(l,a,b){texts(l).filter(t=>t.text===a).forEach(t=>t.text=b);}
function clear(l){l.layers.slice().forEach(k=>k.remove());}
function col(p,n,w,g,pad,fill,h){var f=H.frame({parent:p,name:n,dir:'col',w:w,h:h,gap:g===undefined?16:g,pad:pad||0,fill:fill?H.sw(APP,fill):null});f.stackLayout.alignItems=0;return f;}
function row(p,n,w,g,pad,fill,h){return H.frame({parent:p,name:n,dir:'row',w:w,h:h,gap:g===undefined?8:g,pad:pad||0,fill:fill?H.sw(APP,fill):null});}
function tx(p,t,size,role,w,weight){return H.text({parent:p,text:t,size:size||14,color:H.sw(APP,role||'ink'),w:w,weight:weight||5});}
function space(p,vert){var f=H.frame({parent:p,name:'flex-space',w:1,h:1});f[vert?'verticalSizing':'horizontalSizing']=sketch.FlexSizing.Fill;return f;}
function btn(p,t,id,kind,w,h){var b=row(p,'link:'+id,w,8,{left:12,right:12,top:0,bottom:0},kind==='primary'?'ink':'surface',h||36);b.style.corners.radii=[8,8,8,8];b.style.borders=[{color:H.sw(APP,'line'),thickness:1,position:sketch.Style.BorderPosition.Inside}];b.stackLayout.justifyContent=1;tx(b,t,13,kind==='primary'?'inverse':kind==='danger'?'negative':'ink',undefined,6);H.order(b);return b;}
function ib(p,icon,id){var b=row(p,'link:'+id,32,0,0,null,32);b.stackLayout.justifyContent=1;H.icon({parent:b,d:H.paths[icon],size:18,color:H.hex(APP,'secondary')});H.order(b);return b;}
function card(p,n,w,g,pad){var c=col(p,n,w,g===undefined?16:g,pad===undefined?20:pad,'surface');c.style.corners.radii=[12,12,12,12];c.style.borders=[{color:H.sw(APP,'line'),thickness:1,position:sketch.Style.BorderPosition.Inside}];return c;}
function mono(p,t,w){return H.text({parent:p,text:t,size:12,mono:true,color:H.sw(APP,'secondary'),w:w});}
function utility(s){all(s).filter(l=>l.name==='link:search'&&l.type==='Group').forEach(b=>{b.style.fills=[{color:H.sw(APP,'surface'),enabled:true}];b.style.borders=[{color:H.sw(APP,'line'),thickness:1,position:sketch.Style.BorderPosition.Inside}];texts(b).forEach(t=>t.style.textColor=H.sw(APP,'ink'));});var f=named(s,'sidebar');var foot=f&&named(f,'link:settings');if(foot){foot.stackLayout.gap=6;foot.stackLayout.apply();}}
function normalized(s){all(s).forEach(l=>{if(/^link:.* \d+$/.test(l.name))l.name=l.name.replace(/ \d+$/,'');});}
function final(s){utility(s);H.relayout(s);normalized(s);H.out({screen:s.name,id:s.id,frame:s.frame,links:all(s).filter(l=>l.name.startsWith('link:')).map(l=>l.name)});}
function edit(id,fn){['Light','Dark'].forEach(a=>{APP=a+'/Clean';var s=H.page('Proto macOS '+a).layers.find(l=>l.name==='Screen/macos/'+APP+'/'+id);if(!s)throw Error('Missing '+id);var x=s.frame.x,y=s.frame.y;fn(s);final(s);s.frame.x=x;s.frame.y=y;});}

var TARGET="search";
edit(TARGET,function(s){
if(TARGET==='conversation--approval'){var c=named(s,'approval-dialog');clear(c);c.frame.width=600;c.stackLayout.gap=16;c.stackLayout.padding=28;tx(c,'Approval required',12,'accent',544,7);tx(c,'Run webhook tests',23,'ink',544,7);tx(c,'Review the exact command and working directory before allowing execution.',14,'secondary',544);var cmd=card(c,'exact-command',544,10,16);mono(cmd,'npm test',512);tx(cmd,'Working directory',11,'tertiary');mono(cmd,'/Users/founder/Projects/personal',512);tx(cmd,'Project: Personal · Workspace sprite',12,'secondary');H.order(cmd);btn(c,'Always allow `npm test` in Personal','conversation',null,544);tx(c,'Applies only to this command in Personal, not other terminal commands.',12,'secondary',544);var r=row(c,'approval-actions',544);btn(r,'Deny','back');space(r);btn(r,'Allow once','conversation','primary');H.order(r);H.order(c);c.frame.x=420;c.frame.y=230;}
if(TARGET==='conversation--menu'){s.layers.slice().filter(l=>(l.type==='ShapePath'&&l.frame.width===1440)||l.type==='SymbolInstance'||(l.type==='Group'&&l.name.startsWith('link:')&&l.frame.x>1000)).forEach(l=>l.remove());var menu=card(s,'conversation-menu',252,4,8);[['Rename','conversation'],['Duplicate','conversation'],['Move to project','project'],['Export','artifacts']].forEach(a=>btn(menu,a[0],a[1],null,236));H.rect({parent:menu,name:'destructive-divider',w:236,h:1,fill:H.sw(APP,'line')});btn(menu,'Delete conversation','conversation--delete','danger',236);H.order(menu);var trigger=named(named(s,'header'),'link:conversation--menu');menu.frame.x=1416-252;menu.frame.y=trigger.frame.y+trigger.frame.height+4;}
if(TARGET==='search'){var c=named(s,'CommandPalette/ledger');clear(c);c.frame.width=700;var query=row(c,'query',676,12,12,null,48);H.icon({parent:query,d:H.paths.search,size:20,color:H.hex(APP,'secondary')});tx(query,'ledger',17,'ink');space(query);btn(query,'esc','back');H.order(query);var scopes=row(c,'scope-filters',676,8,4);['All','Projects','Conversations','Work','Routines'].forEach(t=>btn(scopes,t,'search',t==='All'?'primary':null));H.order(scopes);[['Projects','Ledger migration','project'],['Conversations','Move the billing webhook handler onto the new ledger client','conversation'],['Work','Prepare the release · Verify ledger candidate','activity--work'],['Routines','Weekly ledger digest · Mondays, 9:00 AM SGT','routines']].forEach(a=>{tx(c,a[0],11,'tertiary',676,6);var r=row(c,'link:'+a[2],676,12,12,a[2]==='conversation'?'hover':null,48);tx(r,a[1],13,'ink',628,6);H.order(r);});tx(c,'Reasoning and raw logs are not searched',12,'secondary',676);var foot=row(c,'hints',676,12,12);tx(foot,'↑↓ Navigate     ↵ Open',12,'secondary');space(foot);btn(foot,'Close','back');H.order(foot);H.order(c);c.frame.x=370;c.frame.y=170;}
});