// Lane-local repair generators. Preserve screen IDs, positions and existing navigation.
var APP;
function all(l){var a=[l];(l.layers||[]).forEach(k=>a=a.concat(all(k)));return a;}
function named(l,n){return all(l).find(k=>k.name===n);}
function texts(l){return all(l).filter(k=>k.type==='Text');}
function replace(l,a,b){texts(l).filter(t=>t.text===a).forEach(t=>t.text=b);}
function clear(l){l.layers.slice().forEach(k=>k.remove());}
function col(p,n,w,g,pad,fill,h){var f=H.frame({parent:p,name:n,dir:'col',w:w,h:h,gap:g===undefined?16:g,pad:pad||0,fill:fill?H.sw(APP,fill):null});f.stackLayout.alignItems=0;return f;}
function row(p,n,w,g,pad,fill,h){return H.frame({parent:p,name:n,dir:'row',w:w,h:h,gap:g===undefined?8:g,pad:pad||0,fill:fill?H.sw(APP,fill):null});}
function tx(p,t,size,role,w,weight){return H.text({parent:p,text:t,size:size||14,color:H.sw(APP,role||'ink'),w:w,weight:weight||5});}
function space(p,vert){var f=H.frame({parent:p,name:'flex-space',w:1,h:1});f[vert?'verticalSizing':'horizontalSizing']=sketch.FlexSizing.Fill;return f;}
function btn(p,t,id,kind,w,h){var b=row(p,'link:'+id,w,8,{left:12,right:12,top:0,bottom:0},kind==='primary'?'ink':'surface',h||36);b.style.corners.radii=[8,8,8,8];b.style.borders=[{color:H.sw(APP,'line'),thickness:1,position:sketch.Style.BorderPosition.Inside}];b.stackLayout.justifyContent=1;tx(b,t,13,kind==='primary'?'inverse':kind==='danger'?'negative':'ink',undefined,6);H.order(b);return b;}
function ib(p,icon,id){var b=row(p,'link:'+id,32,0,0,null,32);b.stackLayout.justifyContent=1;H.icon({parent:b,d:H.paths[icon],size:18,color:H.hex(APP,'secondary')});H.order(b);return b;}
function card(p,n,w,g,pad){var c=col(p,n,w,g===undefined?16:g,pad===undefined?20:pad,'surface');c.style.corners.radii=[12,12,12,12];c.style.borders=[{color:H.sw(APP,'line'),thickness:1,position:sketch.Style.BorderPosition.Inside}];return c;}
function mono(p,t,w){return H.text({parent:p,text:t,size:12,mono:true,color:H.sw(APP,'secondary'),w:w});}
function utility(s){all(s).filter(l=>l.name==='link:search'&&l.type==='Group').forEach(b=>{b.style.fills=[{color:H.sw(APP,'surface'),enabled:true}];b.style.borders=[{color:H.sw(APP,'line'),thickness:1,position:sketch.Style.BorderPosition.Inside}];texts(b).forEach(t=>t.style.textColor=H.sw(APP,'ink'));});var f=named(s,'sidebar');var foot=f&&named(f,'link:settings');if(foot){foot.stackLayout.gap=6;foot.stackLayout.apply();}}
function normalized(s){all(s).forEach(l=>{if(/^link:.* \d+$/.test(l.name))l.name=l.name.replace(/ \d+$/,'');});}
function final(s){utility(s);H.relayout(s);normalized(s);H.out({screen:s.name,id:s.id,frame:s.frame,links:all(s).filter(l=>l.name.startsWith('link:')).map(l=>l.name)});}
function edit(id,fn){['Light','Dark'].forEach(a=>{APP=a+'/Clean';var s=H.page('Proto macOS '+a).layers.find(l=>l.name==='Screen/macos/'+APP+'/'+id);if(!s)throw Error('Missing '+id);var x=s.frame.x,y=s.frame.y;fn(s);final(s);s.frame.x=x;s.frame.y=y;});}

var TARGET="project";
edit(TARGET,function(s){var m=named(s,'main');
if(TARGET==='projects'){replace(m,'Project name','Release planning');var b=named(named(m,'create-project'),'link:project');b.style.fills=[{color:H.sw(APP,'ink'),enabled:true}];texts(b).forEach(t=>t.style.textColor=H.sw(APP,'inverse'));}
if(TARGET==='projects--empty'){named(m,'create-project').remove();var sb=named(s,'sidebar');sb.layers.slice().filter(l=>l.name==='link:project'||l.name==='link:conversation'||texts(l).some(t=>t.text==='PINNED PROJECTS')).forEach(l=>l.remove());}
if(TARGET==='project'){clear(m);m.stackLayout.gap=24;var header=row(m,'project-header',1136);var hc=col(header,'heading',1000,8);tx(hc,'Projects › Personal',12,'secondary');tx(hc,'Personal',26,'ink',undefined,7);tx(hc,'Your everyday thinking, plans and small wins.',14,'secondary');H.order(hc);space(header);ib(header,'panelLeft','project');H.order(header);var tabs=row(m,'project-tabs',1136,8);['Conversations','Work','Instructions','Memory','Sources','Working locations'].forEach(t=>btn(tabs,t,t==='Work'?'activity--work':'project',t==='Conversations'?'primary':null));H.order(tabs);var layout=row(m,'project-content',1136,24);layout.stackLayout.alignItems=0;var list=col(layout,'conversations',800,16);tx(list,'RECENT CONVERSATIONS',11,'tertiary');[['Move the billing webhook handler onto the new ledger client','Today · Preserve retries and signature verification'],['Plan the next small step','Yesterday · A calmer flow, one real task at a time']].forEach(a=>{var c=card(list,'link:conversation',800,8,20);tx(c,a[0],15,'ink',760,6);tx(c,a[1],12,'secondary');H.order(c);});var c=card(list,'composer',800);tx(c,'Start a conversation in Personal',14,'secondary');var r=row(c,'composer-actions',760);ib(r,'plus','project');space(r);btn(r,'Send ↑','conversation','primary');H.order(r);H.order(c);H.order(list);var ins=card(layout,'project-inspector',312,24,20);[['Instructions','Add guidance for conversations in Personal.'],['Memory','No saved memories yet.'],['Sources','No sources connected.'],['Working locations','Workspace sprite · This Mac\nManage locations in Devices.']].forEach(a=>{var sec=col(ins,'link:project',272,8);tx(sec,a[0],14,'ink',272,7);tx(sec,a[1],13,'secondary',272);H.order(sec);});btn(ins,'Manage devices','settings-devices');H.order(ins);H.order(layout);H.order(m);}
if(TARGET==='routines'||TARGET==='routines--new'){replace(m,'Every 1d · 9:00 AM','Daily · 9:00 AM SGT');replace(m,'Every week · Monday','Monday · 9:00 AM SGT');texts(m).filter(t=>t.text==='No project · Scheduled').forEach((t,i)=>t.text=i===0?'Personal · Workspace sprite':'No project · Workspace sprite');replace(m,"Runs appear under a project's Work only when they start real work",'Timezone: Asia/Singapore (UTC+08). Runs land in the selected project’s Work; unrouted runs stay in Activity.');}
if(TARGET==='routines--new'){var p=named(s,'overlay:routines--new');replace(p,'Every day at 9:00 AM   ⌄','Every day at 9:00 AM SGT   ⌄');p.stackLayout.gap=12;var foot=named(p,'dialog-footer');var prior=p.layers.slice().reverse();var route=col(p,'routing',512,8);tx(route,'Project & execution',12,'secondary');btn(route,'Personal · Workspace sprite  ⌄','project',null,512);tx(route,'Asia/Singapore (UTC+08) · Results appear in Personal → Work.',12,'secondary',512);H.order(route);var order=prior.filter(l=>l!==foot).concat([route,foot]);order.forEach((l,i)=>l.index=order.length-1-i);p.stackLayout.apply();p.frame.y=100;}
if(TARGET==='customize--profile'){var p=named(s,'overlay:customize--profile');p.layers.filter(l=>l.name.startsWith('link:customize--profile')).forEach(r=>{var label=texts(r)[0].text;clear(r);tx(r,label,14);space(r);var sw=H.inst('Switch/'+APP+'/base/on',r);sw.name='link:customize--profile';H.order(r);});}
if(TARGET==='artifacts--detail'){var p=named(s,'overlay:artifacts--detail');named(p,'artifact-actions').remove();var inst=p.layers.find(l=>l.type==='SymbolInstance');inst.overrides.filter(o=>o.property==='stringValue'&&String(o.value).includes('Synthetic')).forEach(o=>o.value='Research brief · Personal');var local=inst.detach();texts(local).filter(t=>t.text.includes('Synthetic')).forEach(t=>t.text='Research brief · Personal');texts(local).forEach(t=>{if(['Preview','Code','Copy','Download'].includes(t.text))t.parent.name='link:artifacts--detail';});}
});