#!/usr/bin/env node
// Generates every platform's design values from tokens/harso.tokens.json (the one source):
//   src/theme.css                        the token regions between the tokens:begin / tokens:end markers (the rest of
//                                        the file stays hand-written);
//   tokens/generated/HarsoTokens.swift   SwiftUI: light/dark dynamic colours per role, tints, type/space/radius;
//   tokens/generated/HarsoTokens.kt      Jetpack Compose: light/dark colours per palette, tints, dimensions.
// Usage: node scripts/gen-tokens.mjs          write the outputs
//        node scripts/gen-tokens.mjs --check  exit 1 if any output is stale or hand-edited
// No dependency: node:fs, node:path, node:url only.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const SOURCE_PATH = resolve(ROOT, "tokens/harso.tokens.json");
export const THEME_PATH = resolve(ROOT, "src/theme.css");
export const SWIFT_PATH = resolve(ROOT, "tokens/generated/HarsoTokens.swift");
export const KOTLIN_PATH = resolve(ROOT, "tokens/generated/HarsoTokens.kt");

const APPEARANCES = ["light", "dark", "cozy", "darkCozy"];
// The CSS cascade: which earlier rules an appearance's rule sits on, in source order (cozy and dark weigh the same,
// dark comes later; dark cozy outranks both).
const SELECTORS = {
  light: ".harso-kit",
  cozy: '.harso-kit[data-palette="cozy"]',
  dark: '.harso-kit[data-mode="dark"]',
  darkCozy: '.harso-kit[data-mode="dark"][data-palette="cozy"]',
};
const INHERITS = { light: [], cozy: ["light"], dark: ["light"], darkCozy: ["light", "cozy", "dark"] };
const TINT_ROLES = ["accent", "accent-mark", "accent-soft"];
const TINT_MODES = ["light", "dark"];
// Groups the natives receive as constants: one value serves every appearance, so a per-appearance map is refused
// rather than reduced to one of its values.
const NATIVE_LENGTH_GROUPS = ["type", "space", "radius"];
const HEADER = "GENERATED by scripts/gen-tokens.mjs from tokens/harso.tokens.json. Do not edit; edit the JSON and run npm run tokens.";

const fail = message => { throw new Error(`tokens: ${message}`); };
const entries = group => Object.entries(group).filter(([key]) => !key.startsWith("$"));

// ---------------------------------------------------------------------------------------------------------------
// Reading the source

export function load(source = JSON.parse(readFileSync(SOURCE_PATH, "utf8"))) {
  if (JSON.stringify(source.appearances) !== JSON.stringify(APPEARANCES)) fail(`appearances must be ${APPEARANCES.join(", ")}`);
  const roles = new Map();
  const groups = [];
  for (const [group, body] of entries(source)) {
    if (group === "appearances" || group === "tint") continue;
    const names = [];
    for (const [name, value] of entries(body)) {
      if (roles.has(name)) fail(`--hk-${name} is defined twice`);
      const perAppearance = typeof value === "string"
        ? Object.fromEntries(APPEARANCES.map(appearance => [appearance, value]))
        : value;
      if (typeof value !== "string" && NATIVE_LENGTH_GROUPS.includes(group)) fail(`--hk-${name} is a native ${group} constant: give one value for every appearance`);
      if (typeof value !== "string" && JSON.stringify(Object.keys(value).sort()) !== JSON.stringify([...APPEARANCES].sort())) fail(`--hk-${name} must give one value or all of ${APPEARANCES.join(", ")}`);
      roles.set(name, { values: perAppearance });
      names.push(name);
    }
    groups.push({ group, description: body.$description, names });
  }
  for (const [name, { values }] of roles) for (const value of Object.values(values)) for (const [, ref] of value.matchAll(/\{([a-z0-9-]+)\}/g)) {
    if (!roles.has(ref)) fail(`--hk-${name} refers to unknown {${ref}}`);
  }
  // Every colour role must be one the natives can draw, in every appearance, before any output is written.
  for (const name of groups.find(({ group }) => group === "color")?.names ?? []) {
    for (const appearance of APPEARANCES) rgba(roles.get(name).values[appearance], roles, appearance);
  }
  const tints = entries(source.tint).map(([name, modes]) => {
    if (JSON.stringify(entries(modes ?? {}).map(([mode]) => mode)) !== JSON.stringify(TINT_MODES)) fail(`tint ${name} must set exactly ${TINT_MODES.join(", ")}`);
    for (const mode of TINT_MODES) {
      if (JSON.stringify(Object.keys(modes[mode] ?? {})) !== JSON.stringify(TINT_ROLES)) fail(`tint ${name}.${mode} must set exactly ${TINT_ROLES.join(", ")}`);
      for (const role of TINT_ROLES) rgba(modes[mode][role]);
    }
    return { name, light: modes.light, dark: modes.dark };
  });
  if (tints[0]?.name !== "grayscale") fail("the first tint is the default and must be grayscale");
  return { roles, groups, tints, tintDescription: source.tint.$description };
}

// ---------------------------------------------------------------------------------------------------------------
// Values

const css = value => {
  const faded = /^\{([a-z0-9-]+)\} \/ (\d+)%$/.exec(value);
  if (faded) return `color-mix(in srgb, var(--hk-${faded[1]}) ${faded[2]}%, transparent)`;
  return value.replace(/\{([a-z0-9-]+)\}/g, (_, ref) => `var(--hk-${ref})`);
};

// A colour value as [rgb, alpha] for the native platforms, following {role} references in the same appearance.
function rgba(value, roles, appearance, seen = []) {
  let found;
  if ((found = /^#([0-9a-f]{6})$/.exec(value))) return [parseInt(found[1], 16), 1];
  if ((found = /^rgb\((\d+) (\d+) (\d+) \/ (\.\d+|0|1)\)$/.exec(value))) {
    const [red, green, blue] = found.slice(1, 4).map(Number);
    if (Math.max(red, green, blue) > 255) fail(`${value}: each channel must be 0 to 255`);
    return [(red << 16) | (green << 8) | blue, Number(found[4])];
  }
  if ((found = /^\{([a-z0-9-]+)\}(?: \/ (\d+)%)?$/.exec(value)) && roles) {
    if (seen.includes(found[1])) fail(`reference cycle through {${found[1]}}`);
    if (found[2] !== undefined && Number(found[2]) > 100) fail(`${value}: opacity must be 0% to 100%`);
    const [rgb, alpha] = rgba(roles.get(found[1]).values[appearance], roles, appearance, [...seen, found[1]]);
    return [rgb, found[2] === undefined ? alpha : alpha * Number(found[2]) / 100];
  }
  if (!roles) return fail(`${value} is not #rrggbb or rgb(r g b / a)`);
  return fail(`${value} is not a colour this generator understands`);
}

const px = value => {
  const found = /^(\d+(?:\.\d+)?)px$/.exec(value);
  return found ? found[1] : fail(`${value} is not a px length`);
};
const em = value => {
  const found = /^(\d*\.\d+|\d+)em$/.exec(value);
  return found ? String(Number(found[1])) : fail(`${value} is not an em length`);
};
const camel = name => name.replace(/-([a-z0-9])/g, (_, next) => next.toUpperCase());
const pascal = name => camel(name).replace(/^./, first => first.toUpperCase());
const hex = rgb => rgb.toString(16).padStart(6, "0");
const alpha = value => String(Math.round(value * 1000) / 1000);

// ---------------------------------------------------------------------------------------------------------------
// CSS: each appearance's rule declares only what differs from the value the cascade already gives it.

export function cssRegions({ roles, groups }) {
  const regions = {};
  const declares = {};
  for (const appearance of ["light", "cozy", "dark", "darkCozy"]) {
    const lines = [];
    declares[appearance] = new Set();
    for (const { description, names } of groups) {
      const declared = names.filter(name => {
        const { values } = roles.get(name);
        const from = INHERITS[appearance].findLast(earlier => declares[earlier].has(name));
        return from === undefined || values[appearance] !== values[from];
      });
      for (const name of declared) declares[appearance].add(name);
      if (!declared.length) continue;
      if (appearance === "light" && description) lines.push(`  /* ${description} */`);
      for (const name of declared) lines.push(`  --hk-${name}: ${css(roles.get(name).values[appearance])};`);
    }
    regions[appearance] = lines.join("\n");
  }
  return regions;
}

const BEGIN = appearance => `/* tokens:begin ${appearance}. ${HEADER} */`;
const END = "/* tokens:end */";

export function renderTheme(tokens, theme = readFileSync(THEME_PATH, "utf8")) {
  const regions = cssRegions(tokens);
  let out = theme;
  for (const appearance of APPEARANCES) {
    const start = out.indexOf(`/* tokens:begin ${appearance}.`);
    const end = start < 0 ? -1 : out.indexOf(END, start);
    if (start < 0 || end < 0) fail(`src/theme.css has no tokens:begin ${appearance} … tokens:end region`);
    const selector = out.lastIndexOf("{", start);
    if (out.slice(out.lastIndexOf("\n", selector) + 1, selector).trim() !== SELECTORS[appearance]) fail(`the ${appearance} region must sit inside ${SELECTORS[appearance]} { … }`);
    out = `${out.slice(0, start)}${BEGIN(appearance)}\n${regions[appearance]}\n  ${out.slice(end)}`;
  }
  return out;
}

// ---------------------------------------------------------------------------------------------------------------
// Swift (SwiftUI)

const nativeColors = ({ groups }) => groups.filter(({ group }) => group === "color").flatMap(({ names }) => names);
const nativeLengths = ({ roles, groups }, group) => groups.find(entry => entry.group === group).names.map(name => [name, roles.get(name).values.light]);

function swiftColor(light, dark) {
  const part = ([rgb, a]) => `0x${hex(rgb)}${a === 1 ? "" : `, ${alpha(a)}`}`;
  return `Color(harsoLight: ${part(light)}, dark: ${part(dark)})`;
}

export function renderSwift(tokens) {
  const { roles, tints } = tokens;
  const colors = nativeColors(tokens);
  const palette = (lightKey, darkKey) => colors.map(name =>
    `            ${camel(name)}: ${swiftColor(rgba(roles.get(name).values[lightKey], roles, lightKey), rgba(roles.get(name).values[darkKey], roles, darkKey))}`).join(",\n");
  const lengths = group => nativeLengths(tokens, group).map(([name, value]) => `    public static let ${camel(name)}: CGFloat = ${px(value)}`).join("\n");
  const type = nativeLengths(tokens, "type").map(([name, value]) => name === "caps-tracking"
    ? `    /// Letter spacing for caps labels, in em (multiply by the font size).\n    public static let ${camel(name)}: CGFloat = ${em(value)}`
    : `    public static let ${camel(name)}: CGFloat = ${px(value)}`).join("\n");
  return `// ${HEADER}
import SwiftUI
#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

/// The person's palette: clean (default) or cozy.
public enum HarsoPalette: String, CaseIterable, Sendable {
    case clean, cozy
}

public extension Color {
    /// Harso colour roles for one palette. Every colour follows the system's light or dark appearance by itself.
    struct Harso: Sendable {
${colors.map(name => `        public let ${camel(name)}: Color`).join("\n")}

        public static let clean = Harso(
${palette("light", "dark")}
        )

        public static let cozy = Harso(
${palette("cozy", "darkCozy")}
        )

        public static func palette(_ palette: HarsoPalette) -> Harso {
            switch palette {
            case .clean: clean
            case .cozy: cozy
            }
        }

        /// The same roles with the person's tint: a tint replaces only accent, accentMark and accentSoft.
        public func tinted(_ tint: HarsoTint) -> Harso {
            Harso(
${colors.map(name => `                ${camel(name)}: ${TINT_ROLES.includes(name) ? `tint.${camel(name)}` : camel(name)}`).join(",\n")}
            )
        }
    }

    /// The default palette's roles.
    static let harso = Harso.clean
}

/// ${tokens.tintDescription}
public enum HarsoTint: String, CaseIterable, Sendable {
    case ${tints.map(({ name }) => name).join(", ")}

    public static let \`default\`: HarsoTint = .${tints[0].name}

${TINT_ROLES.map(role => `    public var ${camel(role)}: Color {
        switch self {
${tints.map(tint => `        case .${tint.name}: ${swiftColor(rgba(tint.light[role]), rgba(tint.dark[role]))}`).join("\n")}
        }
    }`).join("\n\n")}
}

/// Boundaryless v3 type scale, in points.
public enum HarsoType {
${type}
}

/// Spacing steps, in points.
public enum HarsoSpace {
${lengths("space")}
}

/// Corner radii, in points.
public enum HarsoRadius {
${lengths("radius")}
}

extension Color {
    /// A colour that is \`light\` in the light appearance and \`dark\` in the dark one (sRGB, 0xRRGGBB).
    init(harsoLight light: UInt32, _ lightAlpha: Double = 1, dark: UInt32, _ darkAlpha: Double = 1) {
        #if canImport(UIKit)
        self.init(uiColor: UIColor { traits in
            traits.userInterfaceStyle == .dark ? UIColor(harso: dark, darkAlpha) : UIColor(harso: light, lightAlpha)
        })
        #elseif canImport(AppKit)
        self.init(nsColor: NSColor(name: nil) { appearance in
            appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua ? NSColor(harso: dark, darkAlpha) : NSColor(harso: light, lightAlpha)
        })
        #endif
    }
}

#if canImport(UIKit)
private extension UIColor {
    convenience init(harso rgb: UInt32, _ alpha: Double) {
        self.init(red: CGFloat((rgb >> 16) & 0xff) / 255, green: CGFloat((rgb >> 8) & 0xff) / 255, blue: CGFloat(rgb & 0xff) / 255, alpha: CGFloat(alpha))
    }
}
#elseif canImport(AppKit)
private extension NSColor {
    convenience init(harso rgb: UInt32, _ alpha: Double) {
        self.init(srgbRed: CGFloat((rgb >> 16) & 0xff) / 255, green: CGFloat((rgb >> 8) & 0xff) / 255, blue: CGFloat(rgb & 0xff) / 255, alpha: CGFloat(alpha))
    }
}
#endif
`;
}

// ---------------------------------------------------------------------------------------------------------------
// Kotlin (Jetpack Compose)

const kotlinColor = ([rgb, a]) => `Color(0x${Math.round(a * 255).toString(16).padStart(2, "0").toUpperCase()}${hex(rgb).toUpperCase()})`;

export function renderKotlin(tokens) {
  const { roles, tints } = tokens;
  const colors = nativeColors(tokens);
  const palette = (name, appearance) => `val ${name} = HarsoColors(
${colors.map(role => `    ${camel(role)} = ${kotlinColor(rgba(roles.get(role).values[appearance], roles, appearance))}`).join(",\n")},
)`;
  const lengths = (group, unit) => nativeLengths(tokens, group).map(([name, value]) => `    val ${pascal(name)} = ${px(value)}.${unit}`).join("\n");
  const type = nativeLengths(tokens, "type").map(([name, value]) => name === "caps-tracking"
    ? `    /** Letter spacing for caps labels. */\n    val ${pascal(name)} = ${em(value)}.em`
    : `    val ${pascal(name)} = ${px(value)}.sp`).join("\n");
  const accent = modes => `HarsoAccent(${TINT_ROLES.map(role => `${kotlinColor(rgba(modes[role]))}`).join(", ")})`;
  return `// ${HEADER}
package com.straitslab.harso.ui.tokens

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

/** Harso colour roles for one appearance (light or dark) of one palette (clean or cozy). */
@Immutable
data class HarsoColors(
${colors.map(name => `    val ${camel(name)}: Color`).join(",\n")},
) {
    /** The same roles with the person's tint: a tint replaces only accent, accentMark and accentSoft. */
    fun tinted(accent: HarsoAccent): HarsoColors = copy(accent = accent.accent, accentMark = accent.accentMark, accentSoft = accent.accentSoft)
}

${palette("HarsoLightColors", "light")}

${palette("HarsoDarkColors", "dark")}

${palette("HarsoCozyLightColors", "cozy")}

${palette("HarsoCozyDarkColors", "darkCozy")}

fun harsoColors(dark: Boolean, cozy: Boolean = false): HarsoColors = when {
    cozy && dark -> HarsoCozyDarkColors
    cozy -> HarsoCozyLightColors
    dark -> HarsoDarkColors
    else -> HarsoLightColors
}

@Immutable
data class HarsoAccent(val accent: Color, val accentMark: Color, val accentSoft: Color)

/** ${tokens.tintDescription} */
enum class HarsoTint(val light: HarsoAccent, val dark: HarsoAccent) {
${tints.map(tint => `    ${pascal(tint.name)}(${accent(tint.light)}, ${accent(tint.dark)}),`).join("\n")}
    ;

    fun accent(dark: Boolean): HarsoAccent = if (dark) this.dark else light

    companion object {
        val Default = ${pascal(tints[0].name)}
    }
}

/** Boundaryless v3 type scale. */
object HarsoType {
${type}
}

/** Spacing steps. */
object HarsoSpace {
${lengths("space", "dp")}
}

/** Corner radii. */
object HarsoRadius {
${lengths("radius", "dp")}
}
`;
}

// ---------------------------------------------------------------------------------------------------------------

export function outputs(tokens = load(), theme) {
  return [
    [THEME_PATH, renderTheme(tokens, theme)],
    [SWIFT_PATH, renderSwift(tokens)],
    [KOTLIN_PATH, renderKotlin(tokens)],
  ];
}

const read = path => { try { return readFileSync(path, "utf8"); } catch { return null; } };

/** Generated files whose content on disk differs from what the JSON generates (relative paths). */
export const staleOutputs = () => outputs().filter(([path, content]) => read(path) !== content).map(([path]) => relative(ROOT, path));

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes("--check")) {
    const stale = staleOutputs();
    if (stale.length) {
      console.error(`tokens: stale or hand-edited: ${stale.join(", ")}. Edit tokens/harso.tokens.json and run npm run tokens.`);
      process.exit(1);
    }
    console.log("tokens: generated files match tokens/harso.tokens.json");
  } else {
    for (const [path, content] of outputs()) {
      if (read(path) === content) continue;
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, content);
      console.log(`wrote ${relative(ROOT, path)}`);
    }
  }
}
