import json,pathlib,subprocess,os,re
P=pathlib.Path('/tmp/harso-sk/proto/lanes/mac-settings')
common=(P/'common.js').read_text()
data={
'account':("Your sign-in and this Mac’s session.",'''var c=card(q.p,'Account');row(c,'Email','Managed by your sign-in. · Account-wide · Managed','text','founder@example.com');row(c,'Sign out','Signs out only this Mac. · This Mac · Ready','button','Sign out','settings--sign-out');row(c,'Active sessions','Review and revoke other signed-in sessions.','badge','Unavailable');endcard(c);T(q.p,'Active sessions and device revocation live in Devices.\u2028Export and deletion live in Data & Privacy.',12,'secondary',808);var links=F({name:'related settings',parent:q.p,dir:'row',gap:10});button(links,'Devices','settings-devices');button(links,'Data & Privacy','settings-privacy');H.order(links);'''),
'devices':('Manage this Mac’s access and where your agents run.', '''var c=card(q.p,'This Mac');row(c,'This Mac','MacBook Pro · Current device','badge','Enrolled');['Accessibility','Screen Recording','Automation','Full Disk Access'].forEach((v,i)=>row(c,v,'','badge',i===3?'Not granted':'Allowed'));endcard(c);var d=card(q.p,'Device controls');row(d,'Emergency stop','Stop all local agent actions immediately.','danger','Emergency stop');row(d,'Revoke or rotate','Manage device enrollment credentials.','button','Revoke or rotate');row(d,'Device targeting','','select','This Mac');endcard(d);'''),
'general':('Make Weave work the way you do.', '''var c=card(q.p,'Messages');row(c,'Send messages','Choose the key that sends your message.','segments',['Enter','⌘Enter']);endcard(c);section(q.p,'Startup and window');var d=card(q.p,'Startup and window');row(d,'Launch at login','Open Weave when you sign in to this Mac.','switch',true);row(d,'Keep running when window closes','','switch',true);row(d,'Show in menu bar','','switch',false);row(d,'Default landing','','select','New conversation');endcard(d);'''),
'appearance':('Tune your workspace’s look and feel.', '''var c=card(q.p,'Theme');row(c,'Theme','Follow macOS or choose an appearance.','segments',['System','Light','Dark']);row(c,'Reduced motion','Minimize animations and transitions.','switch',false);endcard(c);section(q.p,'Reading and layout');var d=card(q.p,'Reading and layout');row(d,'Text size','','select','Default');row(d,'Density','','select','Clean');row(d,'Contrast','','select','Standard');endcard(d);'''),
'voice':('Speak naturally, and choose how Weave responds.', '''var c=card(q.p,'Microphone');row(c,'Microphone permission','Access needs attention on this Mac.','button','Repair');endcard(c);section(q.p,'Audio devices');var d=card(q.p,'Audio devices');row(d,'Input','','select','MacBook Pro Microphone');row(d,'Output','','select','MacBook Pro Speakers');row(d,'Voice','','select','Default');row(d,'Language','','select','English');row(d,'Live voice','Allow hands-free conversations.','switch',true);endcard(d);'''),
'notifications':('Stay informed without breaking your focus.', '''var c=card(q.p,'Notifications');row(c,'Desktop notifications','Notifications are allowed on this Mac.','switch',true);row(c,'Agent needs approval','Get notified when an action needs you.','switch',true);row(c,'Task completed','','switch',true);row(c,'Routine updates','','switch',false);row(c,'Play notification sounds','','switch',false);endcard(c);section(q.p,'Focus');var d=card(q.p,'Focus');row(d,'Respect macOS Focus','Silence notifications while Focus is on.','switch',true);endcard(d);'''),
'connections':('Connect the tools your work lives in.', '''var c=card(q.p,'Linear');row(c,'Linear','Workspace connected · Read access enabled','badge','Connected');row(c,'Allow write actions','Let agents create and update Linear issues.','switch',true);row(c,'Disconnect Linear','Remove access for this workspace.','button','Disconnect');endcard(c);var d=card(q.p,'GitHub');row(d,'GitHub','Connect repositories, issues, and pull requests.','button','Connect');endcard(d);T(q.p,'You remain in control. Write actions require your consent.',12,'secondary');'''),
'billing':('Your plan, billing, and agent usage in one place.', '''var c=card(q.p,'Plan');row(c,'Plan','Founder · active','button','Choose plan','settings-billing--plan');row(c,'Billing cycle','','segments',['Monthly US$300','Annual US$3,000'],'settings-billing--plan');row(c,'Manage billing','','button','Billing portal ↗','settings-billing');endcard(c);section(q.p,'Agent usage');H.inst('AgentLimitsCard/'+APP+'/default',q.p);'''),
'privacy':('Control your data and account security.', '''var c=card(q.p,'Your data');row(c,'Export data','Download a copy of your conversations and account data.','button','Export data');row(c,'Delete account','Permanently delete your account and associated data.','danger','Delete account');endcard(c);section(q.p,'Security history');var d=card(q.p,'Security history');row(d,'Signed in on this Mac','Current session · macOS','badge','Successful');row(d,'Device enrolled','This Mac · Trusted device','badge','Verified');endcard(d);T(q.p,'Device permissions and session revocation are managed in Devices.',12,'secondary');button(q.p,'Manage devices','settings-devices');'''),
'shortcuts':('Move around Weave without leaving the keyboard.', '''var c=card(q.p,'Keyboard shortcuts');row(c,'Search','','kbd',[['command'],['letter','K']]);row(c,'New conversation','','kbd',[['command'],['letter','N']]);row(c,'Settings','','kbd',[['command'],['letter',',']]);row(c,'Toggle sidebar','','kbd',[['command'],['letter','B']]);row(c,'Send message','','kbd',[['return']]);row(c,'Insert a new line','','kbd',[['shift'],['return']]);row(c,'Dismiss dialog','','kbd',[['escape']]);endcard(c);T(q.p,'Message sending behavior can be changed in General.',12,'secondary');button(q.p,'Open General','settings-general');'''),
'about':('A calmer workspace for working with agents.', '''var hero=F({name:'Weave identity',parent:q.p,dir:'row',gap:16,pad:24,w:808,radius:12,fill:H.sw(APP,'panel'),align:1});H.icon({parent:hero,d:H.paths.sparkles,size:40,color:H.hex(APP,'accent')});var tx=F({name:'identity copy',parent:hero,dir:'col',gap:6});T(tx,'Weave for macOS',20);T(tx,'Development build · Version 0.1.0 (prototype)',12,'secondary');H.order(tx);H.order(hero);var c=card(q.p,'About Weave');row(c,'Software updates','Keep Weave up to date on this Mac.','button','Check for update');row(c,'Documentation','','button','Open documentation ↗');row(c,'Release notes','','button','What’s new ↗');row(c,'Terms & privacy','','button','View policies ↗');endcard(c);T(q.p,'Version shown is illustrative prototype copy.',11,'tertiary');''')}
ids=['settings']+['settings-'+c for c in data]+['settings--sign-out','settings-billing--plan']
# Keep Devices first in navigation, but Account is an explicit additional screen.
(P/'inventory.json').write_text(json.dumps(ids))
for idx,id in enumerate(ids):
 cat='account' if id in ('settings','settings--sign-out') else 'billing' if id=='settings-billing--plan' else id[9:]
 sub,body=data[cat]
 overlay=''
 if '--' in id:
  overlay='''q.s.stackLayout=null;var scrim=H.rect({parent:q.s,name:'40% ink scrim',w:1440,h:900,fill:H.alpha(H.hex(APP,'ink'),0.4)});var modal=F({name:'Dialog',parent:q.s,dir:'col',gap:20,pad:28,w:480,radius:16,fill:H.sw(APP,'surface'),border:H.sw(APP,'line'),shadow:{color:'#00000033',blur:40,x:0,y:16,spread:0}});'''
  if id=='settings--sign-out':overlay+="T(modal,'Sign out of this Mac?',22);T(modal,'Your other devices will stay signed in. You can sign back in at any time.',13,'secondary',424);var acts=F({name:'actions',parent:modal,dir:'row',gap:8,w:424,justify:2,align:1});button(acts,'Cancel','back');button(acts,'Sign out','signin','danger');H.order(acts);"
  else:overlay+="T(modal,'Choose your plan',22);T(modal,'Founder · Full access to your agent workspace.',13,'secondary',424);button(modal,'Monthly · US$300 / month','settings-billing','primary');button(modal,'Annual · US$3,000 / year','settings-billing');T(modal,'Choose monthly or annual billing. Manage or cancel in the billing portal.',12,'secondary',424);button(modal,'Cancel','back');"
  overlay+="H.order(modal);modal.frame.x=480;modal.frame.y=(900-modal.frame.height)/2;"
 generator=common+'\nvar ID='+json.dumps(id)+';var INDEX='+str(idx)+';var CAT='+json.dumps(cat)+';var SUB='+json.dumps(sub)+';var q=shell();\n'+body+'\nfinish(q);\n'+overlay
 (P/(id+'.js')).write_text(generator)
 for app in ['Light/Clean','Dark/Clean']:
  run=P/('run-'+id+'-'+app.split('/')[0]+'.js');run.write_text('var APP='+json.dumps(app)+';\n'+generator)
  env=os.environ.copy();env['SK_PRELUDE']='/tmp/harso-sk/proto/prelude.js'
  res=subprocess.run(['python3','/tmp/harso-sk/sk.py','run_code',json.dumps({'code_file':str(run)})],env=env,text=True,capture_output=True)
  with (P/'build.log').open('a') as f:f.write(res.stdout+res.stderr)
  print(id,app,res.returncode,res.stdout[:220],flush=True)
  if res.returncode:raise SystemExit(1)
