// Shared native Settings builder. Called by per-screen APP wrappers.
var CATS=[['devices','Devices','display','#5856d6'],['account','Account','person_crop_square','#007aff'],['general','General','gear','#8e8e93'],['appearance','Appearance','sun','#007aff'],['voice','Voice & Live','mic','#ff2d55'],['notifications','Notifications','bell','#ff3b30'],['connections','Connections','link','#34a853'],['billing','Usage & Billing','chart_bar','#ff9500'],['privacy','Data & Privacy','lock','#32ade6'],['shortcuts','Shortcuts','command','#af52de'],['about','About','info_circle','#8e8e93']];
var IDS=['settings','settings-account','settings-devices','settings-general','settings-appearance','settings-voice','settings-notifications','settings-connections','settings-billing','settings-privacy','settings-shortcuts','settings-about','settings--sign-out','settings-billing--plan'];
function buildSettings(APP,ID,phase){
 var page=H.page('Proto macOS '+APP.split('/')[0]), name='Screen/macos/'+APP+'/'+ID;
 var cat=ID==='settings'?'general':ID==='settings--sign-out'?'account':ID.replace('settings-','').split('--')[0];
 var meta=CATS.find(function(c){return c[0]===cat;});
 var own='settings-'+cat;
 function F(o){var f=H.frame(o); if(o.dir==='col') f.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start; return f;}
 function T(p,t,o){o=o||{};return H.sft({parent:p,text:t,size:o.size||13,weight:o.weight||5,color:o.color||H.sw(APP,'ink'),w:o.w,align:o.align});}
 function space(p){var v=F({name:'flex',parent:p,pad:0,h:1});v.horizontalSizing=sketch.FlexSizing.Fill;return v;}
 function button(p,text,link,kind){var b=F({name:'link:'+(link||own),parent:p,pad:{top:0,right:12,bottom:0,left:12},gap:6,h:24,radius:5,fill:H.sw(APP,kind==='primary'?'accent':'surface'),border:kind==='primary'?null:H.sw(APP,'line-strong')});T(b,text,{weight:6,color:kind==='primary'?'#ffffff':H.sw(APP,kind==='danger'?'negative':'ink')});H.order(b);return b;}
 function toggle(p,on){var b=F({name:'link:'+own,parent:p,pad:2,w:26,h:15,radius:8,fill:on?H.sw(APP,'accent'):H.alpha(H.hex(APP,'ink'),0.18),justify:on?sketch.StackLayout.JustifyContent.End:sketch.StackLayout.JustifyContent.Start});b.style.borders=[{color:on?H.alpha(H.hex(APP,'accent'),0.5):H.alpha(H.hex(APP,'ink'),0.12),thickness:0.5,enabled:true,position:sketch.Style.BorderPosition.Inside}];var knob=H.rect({parent:b,w:11,h:11,oval:true,fill:'#ffffff'});knob.style.shadows=[{color:'#00000038',blur:1.5,x:0,y:0.5,spread:0}];H.order(b);}
 function control(p,r){var type=r[2]||'value', val=r[1];if(type==='toggle'){toggle(p,val); if(r[3])T(p,r[3],{color:H.sw(APP,'secondary'),size:12});}
 else if(type==='popup'){var b=F({name:'link:'+own,parent:p,pad:{top:0,right:6,bottom:0,left:8},w:120,h:24,radius:5,gap:4,fill:H.sw(APP,'surface'),border:H.sw(APP,'line-strong')});T(b,val,{size:13});space(b);H.sf(b,'arrow_up_arrow_down',{size:11,color:H.sw(APP,'secondary')});H.order(b);if(r[3])T(p,r[3],{color:H.sw(APP,'secondary'),size:12});}
 else if(type==='segment'){var seg=F({name:'segmented-control',parent:p,pad:2,gap:2,h:26,radius:6,fill:H.alpha(H.hex(APP,'ink'),0.07)});val.forEach(function(v,i){var b=F({name:'link:'+own,parent:seg,pad:{top:0,right:14,bottom:0,left:14},h:22,radius:4,fill:i===0?H.sw(APP,'surface'):null,border:i===0?H.sw(APP,'line'):null});T(b,v,{weight:i===0?6:5});H.order(b);});H.order(seg);}
 else if(type==='button')button(p,val,r[3],r[4]);
 else if(type==='field'){var f=F({name:'link:'+own,parent:p,pad:{top:0,right:8,bottom:0,left:8},h:24,w:260,radius:4,fill:H.sw(APP,'canvas'),border:H.sw(APP,'line-strong')});T(f,val);H.order(f);}
 else if(type==='stepper'){button(p,val);var st=F({name:'link:'+own,parent:p,dir:'col',pad:2,w:20,h:24,radius:4,fill:H.sw(APP,'surface'),border:H.sw(APP,'line-strong')});H.sf(st,'chevron_up',{size:8,color:H.sw(APP,'ink')});H.sf(st,'chevron_down',{size:8,color:H.sw(APP,'ink')});H.order(st);}
 else if(type==='status'){H.sf(p,'checkmark_circle_fill',{size:13,color:H.sw(APP,'positive')});T(p,val);if(r[3]){button(p,r[3],r[4]);}}
 else if(type==='keys'){val.forEach(function(k){var key=F({name:'key',parent:p,pad:0,w:k==='Space'?52:28,h:24,radius:4,fill:H.sw(APP,'canvas'),border:H.sw(APP,'line-strong'),justify:sketch.StackLayout.JustifyContent.Center});if(k==='command')H.sf(key,k,{size:13,color:H.sw(APP,'secondary')});else T(key,k,{size:12});H.order(key);});}
 else {T(p,val,{color:H.sw(APP,'secondary')});if(r[3]){button(p,r[3],r[4],r[5]);}}
 H.order(p);}
 var s=page.layers.find(function(l){return l.name===name;});
 if(phase==='shell'){
 page.layers.slice().forEach(function(l){if(l.name===name||(/^caption\//.test(l.name)&&l.name.split('/').pop()===ID))l.remove();});
 s=H.screen({page:page.name,platform:'macos',app:APP,id:ID,w:1440,h:900,x:IDS.indexOf(ID)*1560,y:2120});
 var w=H.macWindow(s,APP,{active:'settings',title:meta[1],search:true});
 // Search is local to Settings, not global conversations.
 var sf=w.toolbar.layers.find(function(l){return l.name==='link:search';});sf.name='link:settings';sf.layers.forEach(function(l){if(l.type==='Text'&&l.text==='Search')l.text='Search settings';});
 w.main.stackLayout.padding=28;w.main.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;
 var split=F({name:'settings-split',parent:w.main,dir:'row',gap:28,pad:0,w:1128,h:792});split.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;
 var nav=F({name:'categories',parent:split,dir:'col',gap:2,pad:0,w:220,h:792});
 var hd=F({name:'category-heading',parent:nav,pad:{top:0,right:8,bottom:10,left:8},h:34});T(hd,'SETTINGS',{size:11,weight:8,color:H.sw(APP,'tertiary')});H.order(hd);
 CATS.forEach(function(c){var sel=c[0]===cat;var row=F({name:'link:settings-'+c[0],parent:nav,dir:'row',gap:8,pad:{top:0,right:8,bottom:0,left:8},w:220,h:28,radius:6,fill:sel?H.sw(APP,'accent'):null});var ic=F({name:'category-icon',parent:row,w:20,h:20,radius:5,pad:0,fill:c[3],justify:sketch.StackLayout.JustifyContent.Center});H.sf(ic,c[2],{size:12,weight:6,color:'#ffffff'});H.order(ic);T(row,c[1],{color:sel?'#ffffff':H.sw(APP,'ink')});H.order(row);});H.order(nav);
 var detail=F({name:'settings-detail',parent:split,dir:'col',gap:20,pad:{top:0,right:28,bottom:0,left:28},w:880,h:792});
 H.order(split);w.finish();s.frame.x=IDS.indexOf(ID)*1560;s.frame.y=2120;
 console.log(JSON.stringify({id:ID,app:APP,frame:s.id,phase:phase}));return;
 }
 if(!s)throw new Error('Missing exact screen '+name);var detail=s.layers.find(function(l){return l.name==='content-col';}).layers.find(function(l){return l.name==='main';}).layers.find(function(l){return l.name==='settings-split';}).layers.find(function(l){return l.name==='settings-detail';});
 function group(title,rows,footer){var section=F({name:'section:'+title,parent:detail,dir:'col',gap:8,pad:0,w:824});T(section,title.toUpperCase(),{size:11,weight:8,color:H.sw(APP,'secondary')});var g=F({name:'GroupBox:'+title,parent:section,dir:'col',gap:8,pad:12,w:824,radius:10,fill:H.sw(APP,'surface'),border:H.sw(APP,'line')});rows.forEach(function(r){var row=F({name:'form:'+r[0],parent:g,dir:'row',gap:16,pad:0,w:800,h:28});T(row,r[0],{w:200,align:sketch.Text.Alignment.right});var cp=F({name:'control',parent:row,dir:'row',gap:8,pad:0,w:584,h:28});control(cp,r);H.order(row);});H.order(g);if(footer)T(section,footer,{size:12,color:H.sw(APP,'secondary'),w:812});H.order(section);}
 if(phase==='detail'){
 detail.layers.slice().forEach(function(l){l.remove();});
 var header=F({name:'detail-heading',parent:detail,dir:'row',gap:14,pad:{top:0,right:0,bottom:4,left:0},w:824,h:72});var ic=F({name:'category-mark',parent:header,w:48,h:48,pad:0,radius:12,fill:meta[3],justify:sketch.StackLayout.JustifyContent.Center});H.sf(ic,meta[2],{size:27,color:'#ffffff'});H.order(ic);var tt=F({name:'heading-copy',parent:header,dir:'col',gap:4,pad:0});T(tt,meta[1],{size:22,weight:7});var desc={general:'Make Weave work the way you do.',account:'Your identity, workspace and signed-in devices.',devices:'Manage the Macs and iPhone connected to your account.',appearance:'Choose how Weave looks on this Mac.',voice:'Natural conversations, on your terms.',notifications:'Choose when Weave asks for your attention.',connections:'Bring your tools into the conversation.',billing:'Your plan and usage, all in one place.',privacy:'You control your conversations and your data.',shortcuts:'Keep your hands on the keyboard.',about:'A thoughtful workspace for working with AI.'};T(tt,desc[cat],{color:H.sw(APP,'secondary')});H.order(tt);H.order(header);
 if(cat==='general'){group('Messages',[['Send messages',['Enter','⌘ Enter'],'segment'],['Default landing','Recent','popup'],['Ask before running commands',true,'toggle','Recommended']],'Use Shift–Return to add a new line without sending.');group('Startup & window',[['Open at login',true,'toggle'],['Restore previous windows',true,'toggle'],['Show in menu bar',true,'toggle'],['Keep running when closed',false,'toggle']]);group('Workspace',[['Default workspace','Personal','popup'],['New conversation name','Automatic','popup'],['Check for updates',true,'toggle','Install security updates automatically']]);}
 if(cat==='account'){group('Personal information',[['Name','Abhi Bansal','field'],['Email','abhi@straitslab.com'],['Workspace','Straits Lab · Owner'],['Plan','Pro · Active',null,'Manage plan','settings-billing']]);group('Active sessions',[['MacBook Pro 16"','This Mac · Active now','status'],['iPhone 17 Pro','Singapore · 12 min ago'],['Mac mini','Singapore · Today, 09:14']],'Your account is signed in on 3 devices.');group('Account security',[['Sign-in method','Apple Account'],['Two-factor authentication','Enabled','status'],['This Mac','Sign out…','button','settings--sign-out','danger']],'Signing out stops local agents on this Mac. Your conversations remain in your account.');}
 if(cat==='devices'){group('This Mac',[['MacBook Pro 16"','Enrolled · Online','status'],['Device targeting','This Mac','popup'],['Last seen','Today, 15 Sep 2026 at 14:42']]);group('Permissions',[['Accessibility','Allowed','status'],['Screen Recording','Allowed','status'],['Automation','Allowed','status'],['Full Disk Access','Allowed','status']],'Permissions are managed in System Settings → Privacy & Security.');group('Enrolled devices',[['MacBook Pro 16"','This Mac · macOS 27'],['iPhone 17 Pro','iOS 27 · Online'],['Mac mini','macOS 27 · Online']]);group('Device security',[['Device credentials','Rotate key…','button'],['Agent control','Emergency stop','button',own,'danger']],'Emergency stop immediately ends all agent actions on this Mac.');}
 if(cat==='appearance'){group('Appearance',[['Theme',['System','Light','Dark'],'segment'],['Accent colour','Weave Blue','popup'],['Sidebar icons',true,'toggle','Show category colours']],'System follows the appearance selected in macOS.');group('Reading',[['Text size','13 pt','stepper'],['Content density','Comfortable','popup'],['Code font','SF Mono','popup'],['Show line numbers',true,'toggle']]);group('Accessibility',[['Reduce motion',false,'toggle'],['Increase contrast',false,'toggle'],['Reduce transparency',false,'toggle']],'Accessibility preferences apply to this Mac.');}
 if(cat==='voice'){group('Audio devices',[['Microphone access','Allowed','status','Repair…'],['Input device','Built-in Mic','popup','MacBook Pro 16"'],['Output device','Speakers','popup','System default'],['Automatic input level',true,'toggle']]);group('Voice & language',[['Voice','Sage','popup'],['Language','English (SG)','popup'],['Speaking rate','1.0×','stepper'],['Spoken responses',true,'toggle']]);group('Live conversations',[['Interrupt to speak',true,'toggle'],['Show live transcript',true,'toggle'],['Keep audio recordings',false,'toggle']],'Audio is processed only while a voice conversation is active.');}
 if(cat==='notifications'){group('Allow notifications',[['Notifications',true,'toggle'],['Alert style',['Banners','Alerts','None'],'segment'],['Play notification sound',true,'toggle'],['Badge app icon',true,'toggle']]);group('Notify me about',[['Approval requests',true,'toggle'],['Completed tasks',true,'toggle'],['Failed runs',true,'toggle'],['Routine summaries',false,'toggle']]);group('Delivery',[['Show previews','When unlocked','popup'],['Respect Focus',true,'toggle'],['Quiet hours','22:00 – 08:00']],'Critical approval requests remain available in Activity.');}
 if(cat==='connections'){group('Linear',[['Connection','Connected · Straits Lab','status'],['Access','Issues, projects and comments'],['Allow write actions',true,'toggle','Ask before creating or editing issues'],['Account','abhi@straitslab.com',null,'Disconnect',own,'danger']]);group('GitHub',[['Connection','Not connected'],['Repository access','Only repositories you select'],['Connect account','Connect GitHub…','button',own,'primary']],'Connect GitHub to review pull requests and track changes in your projects.');group('Connection security',[['Require approval',true,'toggle','Before any external write'],['Credentials','Encrypted in macOS Keychain'],['Last permission review','15 Sep 2026, 09:30']]);}
 if(cat==='billing'){group('Weave Pro',[['Current plan','Pro · Active','status','Choose plan…','settings-billing--plan'],['Price','S$32 / month'],['Next renewal','14 Oct 2026'],['Payment method','Visa ending in 4242',null,'Billing portal',own]]);group('September usage',[['Tokens this month','41,200 of 500,000'],['Voice minutes','18 of 300 minutes'],['Connected devices','3 of 5 devices']],'Usage resets on 1 Oct 2026. Your plan stays active until you change it.');var meter=F({name:'token-meter',parent:detail,dir:'col',gap:8,pad:16,w:824,radius:10,fill:H.sw(APP,'surface'),border:H.sw(APP,'line')});T(meter,'Token allowance · 8.24% used',{weight:6});var track=F({name:'progress-track',parent:meter,pad:0,w:792,h:6,radius:3,fill:H.sw(APP,'line')});H.rect({parent:track,w:65.2608,h:6,radius:3,fill:H.sw(APP,'accent')});H.order(track);T(meter,'458,800 tokens remaining this month',{size:12,color:H.sw(APP,'secondary')});H.order(meter);group('Spending controls',[['Usage alerts',true,'toggle','At 80% of the monthly allowance'],['Additional usage',false,'toggle','No unexpected charges']]);}
 if(cat==='privacy'){group('Your data',[['Conversation sync',true,'toggle'],['Include in model training',false,'toggle'],['Retention','90 days','popup'],['Download a copy','Export data…','button']],'Exports include conversations, artifacts and your project settings.');group('Privacy & security',[['Local credentials','Encrypted in macOS Keychain'],['Analytics',false,'toggle','Share anonymous product diagnostics'],['Security history','Last sign-in: this Mac, today at 09:14'],['Review activity','Security history…','button']]);group('Delete account',[['Account','Delete account…','button',own,'danger']],'Permanently deletes your conversations and account after a 30-day recovery period.');}
 if(cat==='shortcuts'){group('Navigation',[['New conversation',['command','N'],'keys'],['Search conversations',['command','K'],'keys'],['Open Settings',['command',','],'keys'],['Toggle sidebar',['⌥','command','S'],'keys'],['Previous conversation',['⌥','↑'],'keys'],['Next conversation',['⌥','↓'],'keys']]);group('Conversation',[['Send message',['↵'],'keys'],['Insert a new line',['⇧','↵'],'keys'],['Start voice conversation',['⌥','Space'],'keys'],['Stop active run',['Esc'],'keys'],['Attach a file',['⇧','command','A'],'keys']]);group('Preferences',[['Keyboard shortcuts',true,'toggle'],['Custom shortcuts','Restore defaults…','button']],'Shortcuts are available when the Weave window is active.');}
 if(cat==='about'){group('Weave',[['Version','1.4 (build 2026.09.15)'],['Update channel','Stable','popup'],['Software update','You’re up to date','status','Check for updates'],['Automatic updates',true,'toggle']]);group('Made for your Mac',[['Platform','macOS 27 · Apple silicon'],['Workspace','Straits Lab'],['Website','weave.cloud',null,'Visit website'],['Support','support@weave.cloud',null,'Contact support']]);group('Legal',[['Documentation','Open documentation','button'],['Privacy','Privacy policy','button'],['Terms','Terms of service','button'],['Acknowledgements','Open-source licences','button']],'© 2026 Straits Lab. Built with care in Singapore.');}
 H.order(detail);var main=detail.parent.parent;main.stackLayout.apply();s.frame.x=IDS.indexOf(ID)*1560;s.frame.y=2120;
 }
 if(phase==='overlay'){
 H.macScrim(s,APP);
 if(ID==='settings--sign-out')H.macAlert(s,APP,{title:'Sign out of this Mac?',body:'Local agents will stop and this Mac will be disconnected. Your conversations and files stay in your account.',glyph:'person_crop_square',tone:'danger',w:320,buttons:[['back','Cancel','secondary'],['signin','Sign out','danger']]});
 else{var sh=F({name:'plan-sheet',parent:s,dir:'col',gap:20,pad:24,w:560,radius:12,fill:H.sw(APP,'surface'),border:H.sw(APP,'line'),shadow:{color:'#00000040',blur:32,x:0,y:16,spread:0}});T(sh,'Choose your plan',{size:20,weight:7});T(sh,'A little help, or room for the whole team.',{color:H.sw(APP,'secondary')});[['Free','S$0','50,000 tokens / month · 1 device'],['Pro','S$32 / month','500,000 tokens / month · 5 devices'],['Team','S$96 / month','2 million tokens / month · Shared workspace']].forEach(function(p,i){var card=F({name:'link:settings-billing--plan',parent:sh,dir:'col',gap:8,pad:16,w:512,radius:10,fill:i===1?H.sw(APP,'accent-soft'):H.sw(APP,'canvas'),border:H.sw(APP,i===1?'accent':'line')});var r=F({name:'plan-title',parent:card,gap:8,pad:0,w:480});T(r,p[0],{size:15,weight:7});space(r);T(r,p[1],{weight:6});if(i===1)H.sf(r,'checkmark_circle_fill',{size:16,color:H.sw(APP,'accent')});H.order(r);T(card,p[2],{size:12,color:H.sw(APP,'secondary')});if(i===1)T(card,'Current plan · Renews 14 Oct 2026',{size:12,color:H.sw(APP,'accent')});H.order(card);});T(sh,'Prices in Singapore dollars. Changes apply at your next renewal.',{size:12,color:H.sw(APP,'secondary'),w:512});var acts=F({name:'sheet-actions',parent:sh,pad:0,gap:8,w:512,h:28});space(acts);button(acts,'Cancel','back');button(acts,'Change plan','settings-billing','primary');H.order(acts);H.order(sh);sh.frame.x=568;sh.frame.y=52;sh.moveToFront();}
 }
 console.log(JSON.stringify({id:ID,app:APP,frame:s.id,phase:phase}));
}

buildSettings(APP,"settings-general",PHASE);