from pathlib import Path
import json
P=Path('/tmp/harso-sk/lanes/controls')
bodies={}
bodies['Button']="""
['primary','secondary','outline','ghost','danger'].forEach(function(v){['xs','base'].forEach(function(sz){var r=row(v+' · '+sz+' · default / hover / focus / disabled / loading');['default','hover','focus','disabled','loading'].forEach(function(st){var c=fr(r,'pair','col',12);button(c,'Button/'+APP+'/'+v+'/'+sz+'/icon-text/'+st,v==='primary'?'Continue':v==='secondary'?'Not now':v==='danger'?'Remove':'Explore',v,st,sz==='xs',false,v==='danger'?'trash':v==='secondary'?'clock':'arrowRight');button(c,'Button/'+APP+'/'+v+'/'+sz+'/icon-only/'+st,'',v,st,sz==='xs',true,'plus');});});});
"""
bodies['IconButton']="""var r=row('Named actions · 36px hit targets');['default','hover','focus','disabled','loading'].forEach(st=>button(r,'IconButton/'+APP+'/base/'+st,'','ghost',st,false,true,'plus'));"""
bodies['ButtonGroup']="""['pdf','markdown','html'].forEach((selected)=>{var r=row('Export formats · '+selected);var s=sym(r,'formats/'+selected,'row',0,3,undefined,42,'panel','line',10);['PDF','Markdown','HTML'].forEach(x=>button(s,'segment',x,x.toLowerCase()===selected?'secondary':'ghost','default',false,false));s.layers.find(l=>l.layers&&l.layers.some(c=>c.text&&c.text.toLowerCase()===selected)).style.fills=[{color:H.sw(APP,'hover'),fillType:sketch.Style.FillType.Color}];});var r=row('Icon pair');var s=sym(r,'icons/default','row',0,3,undefined,42,'panel','line',10);button(s,'segment','','secondary','default',false,true,'mail');button(s,'segment','','ghost','default',false,true,'file');"""
bodies['LinkButton']="""var r=row('Inline links');['default','hover','focus','disabled'].forEach(st=>{var s=sym(r,'text/'+st,'col',2,6);var tx=t(s,'Explore buttons',st==='disabled'?'tertiary':st==='hover'?'accent':'ink');H.rect({parent:s,name:'underline',w:106,h:1,fill:H.sw(APP,st==='disabled'?'faint':'secondary')});if(st==='focus')s.style.borders=[{color:H.sw(APP,'accent'),thickness:2}];});"""
bodies['CloseButton']="""var r=row('Quiet icons. Full-sized hit targets.');['default','hover','focus','disabled'].forEach(st=>{var b=button(r,'CloseButton/'+APP+'/base/'+st,'','ghost',st,false,true,'x');var i=b.layers.find(l=>l.name==='icon');i.frame.width=18;i.frame.height=18;});"""
bodies['Input']="""['default','filled','focus','invalid','disabled'].forEach(st=>{var r=row(st);field(r,'Input/'+APP+'/base/'+st,'Project name *',st);field(r,'Input/'+APP+'/leading-icon/'+st,'Project name *',st,'leading');});var r=row('Trailing select · Textarea · Search');field(r,'Input/'+APP+'/trailing-select/default','', 'default','trailing');field(r,'Input/'+APP+'/textarea/default','', 'default','textarea');field(r,'Input/'+APP+'/search/default','', 'default','search');"""
bodies['InputOtp']="""['empty','partial','complete','invalid','disabled'].forEach(st=>{var r=row(st);var s=sym(r,'six-cells/'+st,'col',12);t(s,'One-time code *','secondary',13);var cells=fr(s,'cells','row',8);for(var i=0;i<6;i++){var focus=(st==='empty'&&i===0)||(st==='partial'&&i===3);var c=fr(cells,'cell','row',0,0,40,44,st==='disabled'?'panel':'surface',st==='invalid'?'negative':focus?'accent':'control-line',8);c.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;c.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;if(st==='complete'||st==='invalid'||st==='partial'&&i<3)t(c,String(i+1),st==='disabled'?'tertiary':'ink',16);else if(focus)H.rect({parent:c,w:1,h:18,fill:H.sw(APP,'accent')});}t(s,'Six characters. Paste or type; submit when ready.','tertiary',12);});"""
bodies['Select']="""['default','focus','disabled','open'].forEach(st=>{var r=row('Persistent choice · '+st);var s=sym(r,'popup/'+st,'col',8);t(s,'Audience','secondary',13);var b=fr(s,'field','row',12,{top:0,right:12,bottom:0,left:12},260,36,st==='disabled'?'panel':'surface',st==='focus'?'accent':'control-line',8);b.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;t(b,'Our team',st==='disabled'?'tertiary':'ink',14,208);ic(b,'chevronsUpDown');if(st==='open')menu(s,['Our team','Everyone','Partners','Only me'],0);});"""
bodies['Dropdown']="""['default','hover','disabled','open'].forEach(st=>{var r=row('Actions · '+st);var s=sym(r,'pulldown/'+st,'col',8);var b=button(s,'trigger','Choose model','secondary',st==='open'?'default':st,false,false);ic(b,'chevronDown');if(st==='open')menu(s,['Balanced','Fast','Reasoning','Research'],0);});"""
bodies['Checkbox']="""['off','on','indeterminate','disabled'].forEach(st=>{var r=row(st);['default','choice-card'].forEach(v=>{var s=sym(r,v+'/'+st,'row',12,v==='choice-card'?16:0,320,undefined,v==='choice-card'?'surface':null,v==='choice-card'?(st==='on'?'accent':'line'):null,12);var c=fr(s,'checkbox','row',0,0,18,18,st==='on'||st==='indeterminate'?'ink':st==='disabled'?'panel':'surface','control-line',4);c.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;c.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;if(st==='on'||st==='indeterminate')ic(c,st==='on'?'check':'minus','inverse',14);var cp=fr(s,'copy','col',4);t(cp,'Keep this draft',st==='disabled'?'tertiary':'ink');t(cp,'You can return to it later.','tertiary',12);});});"""
bodies['Radio']="""['off','on','disabled'].forEach(st=>{var r=row(st);['default','radio-card'].forEach(v=>{var s=sym(r,v+'/'+st,'row',12,v==='radio-card'?16:0,280,undefined,v==='radio-card'?'surface':null,v==='radio-card'?(st==='on'?'accent':'line'):null,12);var c=fr(s,'radio','row',0,0,18,18,st==='disabled'?'panel':'surface',st==='on'?'ink':'control-line',999);c.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;c.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;if(st==='on')H.rect({parent:c,w:10,h:10,fill:H.sw(APP,'ink'),oval:true});t(s,'Our team',st==='disabled'?'tertiary':'ink');});});"""
bodies['Switch']="""[['small',32,20],['base',40,24],['large',46,28]].forEach(sz=>{var r=row(sz[0]+' · off / on / disabled');['off','on','disabled'].forEach(st=>{var s=sym(r,sz[0]+'/'+st,'row',12);var track=fr(s,'track','row',0,2,sz[1],sz[2],st==='on'?'ink':'line-strong',null,999);track.stackLayout.justifyContent=st==='on'?sketch.StackLayout.JustifyContent.End:sketch.StackLayout.JustifyContent.Start;H.rect({parent:track,w:sz[2]-4,h:sz[2]-4,fill:H.sw(APP,st==='disabled'?'faint':'inverse'),oval:true});t(s,'Voice input',st==='disabled'?'tertiary':'ink');});});"""
bodies['Slider']="""['single','range'].forEach(v=>{var r=row(v+' · value bubble');var s=sym(r,v+'/default','col',12,0,340);t(s,v==='single'?'Volume · 40%':'Volume · 20–70%','secondary',13);var art=fr(s,'track and value','row',0,0,340,70);art.stackLayout=null;var bubble=fr(art,'value','row',0,6,44,28,'ink',null,6);t(bubble,v==='single'?'40%':'70%','inverse',12);bubble.frame.x=v==='single'?114:216;bubble.frame.y=0;H.rect({parent:art,name:'track',x:0,y:49,w:340,h:4,fill:H.sw(APP,'line'),radius:2});H.rect({parent:art,name:'active',x:v==='single'?0:68,y:49,w:v==='single'?136:170,h:4,fill:H.sw(APP,'ink'),radius:2});(v==='single'?[136]:[68,238]).forEach(x=>H.rect({parent:art,name:'thumb',x:x-8,y:43,w:16,h:16,fill:H.sw(APP,'surface'),border:H.sw(APP,'ink'),bw:2,oval:true}));});"""
bodies['DatePicker']="""['closed','open'].forEach(st=>{var r=row('Research window · '+st);var s=sym(r,'date/'+st,'col',8);var b=button(s,'date field','Sep 11, 2026','outline','default',false,false,'calendar');ic(b,'chevronDown');if(st==='open'){var cal=fr(s,'calendar','col',8,16,undefined,undefined,'surface','line',16);cal.style.shadows=[{color:'#0000001f',blur:24,spread:0,x:0,y:8}];var head=fr(cal,'month','row',12,0,252,32);head.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;ic(head,'arrowLeft');t(head,'September 2026','ink',14,196);ic(head,'arrowRight');var week=fr(cal,'week','row',0);['Su','Mo','Tu','We','Th','Fr','Sa'].forEach(d=>{var c=fr(week,'day name','row',0,0,36,28);c.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;t(c,d,'tertiary',12);});for(var wi=0;wi<5;wi++){var rw=fr(cal,'week','row',0);for(var di=0;di<7;di++){var day=wi*7+di-1;var c=fr(rw,'day','row',0,0,36,32,day===11?'ink':null,day===15?'accent':null,6);c.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;c.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;t(c,day<1?String(day+31):day>30?String(day-30):String(day),day===11?'inverse':day<1||day>30?'tertiary':'ink',13);}}}});"""
bodies['FileUpload']="""['idle','drag-over','files'].forEach(st=>{var r=row(st);var s=sym(r,'dropzone/'+st,'col',16,20,520,undefined,st==='drag-over'?'hover':'surface',st==='drag-over'?'accent':'line',12);var hd=fr(s,'heading','row',8);ic(hd,'upload');t(hd,'Reference files');t(s,st==='drag-over'?'Drop files to attach them.':'Choose files or drop them here.','ink',16);t(s,'Text or Markdown · up to 4 files · 1,024 bytes each.\\nThis example does not read or upload contents.','secondary',13,480);button(s,'choose','Choose Files','primary','default',false,false);if(st==='files'){['research-notes.md','project-brief.txt'].forEach((name,i)=>{var f=fr(s,'file','row',12,10,480,40,'panel',null,8);f.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;ic(f,'file');t(f,name,'ink',13,280);t(f,i?'512 B':'824 B','tertiary',12);ic(f,'x');});}else t(s,'No file chosen','tertiary',12);});"""
bodies['ThemeToggle']="""['system','light','dark'].forEach(sel=>{var r=row('Appearance · '+sel);var s=sym(r,'segmented/'+sel,'row',2,3,undefined,42,'panel','line',999);['System','Light','Dark'].forEach((x,i)=>{var b=button(s,'segment',x,x.toLowerCase()===sel?'secondary':'ghost','default',false,false,i===0?'settings':i===1?'sun':'moon');if(x.toLowerCase()===sel)b.style.fills=[{color:H.sw(APP,'hover'),fillType:sketch.Style.FillType.Color}];});});"""
bodies['Stepper']="""['default','focus','disabled'].forEach(st=>{var r=row('Embedded numeric stepper · '+st);var s=sym(r,'numeric/'+st,'row',0,{top:0,right:0,bottom:0,left:12},160,36,st==='disabled'?'panel':'surface',st==='focus'?'accent':'control-line',8);s.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;t(s,'12',st==='disabled'?'tertiary':'ink',14,114);var arrows=fr(s,'stepper','col',0,0,34,36,'panel','line',6);['chevronUp','chevronDown'].forEach(k=>{var hit=fr(arrows,'step','row',0,0,34,18);hit.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;hit.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;ic(hit,k,st==='disabled'?'tertiary':'secondary',12);});});"""
bodies['ComboBox']="""['default','focus','disabled','open'].forEach(st=>{var r=row('Editable choice · '+st);var s=sym(r,'editable/'+st,'col',8);var b=fr(s,'field','row',0,{top:0,right:0,bottom:0,left:12},260,36,st==='disabled'?'panel':'surface',st==='focus'?'accent':'control-line',8);b.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;t(b,'Research studio',st==='disabled'?'tertiary':'ink',14,212);var trigger=fr(b,'attached trigger','row',0,0,36,36,'panel','line',6);trigger.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;trigger.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;ic(trigger,'chevronDown');if(st==='open')menu(s,['Research studio','Product team','Engineering','Design partners'],0);});"""
# Social marks imported from actual bundled SVG assets; source injected separately.
bodies['SocialButton']="""['Google','GitHub','Apple'].forEach(provider=>{var r=row(provider);['default','hover','disabled','loading'].forEach(st=>{var b=button(r,'SocialButton/'+APP+'/'+provider.toLowerCase()+'/'+st,'Continue with '+provider,'outline',st,false,false);if(st!=='loading'){var svg=SOCIAL[provider].replace(/currentColor/g,H.hex(APP,st==='disabled'?'tertiary':'ink'));var mark=sketch.createLayerFromData(svg,'svg');mark.name='brand mark';mark.parent=b;mark.frame.width=16;mark.frame.height=16;var label=b.layers.find(l=>l.type==='Text');mark.index=0;label.index=1;}});});"""
common=(P/'common.js').read_text()
end="\nfinishOrder(sh);H.relayout(sh);var made=H.symbolize(sh,new RegExp('^'+FAMILY+'/'));H.out({ok:true,family:FAMILY,app:APP,sheet:String(sh.id),count:made.length,made:made,h:Math.round(sh.frame.height),w:Math.round(sh.frame.width),y:sh.frame.y});\n"
for fam,body in bodies.items():
 extra=''
 if fam=='SocialButton':
  asset=P/'social.json'
  if asset.exists():extra='var SOCIAL='+asset.read_text()+';\n'
 (P/(fam+'.js')).write_text("var APP = 'Light/Clean';\nvar FAMILY = '"+fam+"';\n"+extra+common+body+end)
(P/'families.json').write_text(json.dumps(list(bodies)))
print('Generators:',len(bodies))
