var APP = 'Light/Clean';
var FAMILY = 'Select';
var page=H.page('Controls');
var APPS=['Light/Clean','Light/Cozy','Dark/Clean','Dark/Cozy'];
var existing=page.layers.find(l=>l.name===FAMILY+' — '+APP); if(existing) throw new Error('Sheet already exists '+existing.id);
var previous=page.layers.filter(l=>l.name.endsWith(' — '+APP));
var Y=previous.reduce((m,l)=>Math.max(m,l.frame.y+l.frame.height+80),0);
var sh=H.sheet({name:FAMILY+' — '+APP,parent:page,x:APPS.indexOf(APP)*1600,y:Y,fill:H.sw(APP,'canvas-deep')});
function t(p,text,role,size,w){return H.text({parent:p,text:text,color:H.sw(APP,role||'ink'),size:size||14,weight:6,w:w});}
function fr(p,name,dir,gap,pad,w,h,fill,border,radius){return H.frame({parent:p,name:name||'container',dir:dir||'row',gap:gap||0,pad:pad||0,w:w,h:h,fill:fill?H.sw(APP,fill):null,border:border?H.sw(APP,border):null,radius:radius===undefined?8:radius,align:sketch.StackLayout.AlignItems.Start});}
function ic(p,key,role,size){return H.icon({parent:p,d:H.paths[key],color:H.hex(APP,role||'secondary'),size:size||16});}
function row(label){var wrap=fr(sh,'section','col',10);t(wrap,label,'secondary',12);var r=H.row(wrap,'specimens',APP,{pad:20,gap:20,align:sketch.StackLayout.AlignItems.Start});return r;}
function sym(p,v,dir,gap,pad,w,h,fill,border,radius){return fr(p,FAMILY+'/'+APP+'/'+v,dir,gap,pad,w,h,fill,border,radius);}
function finishOrder(root){(root.layers||[]).forEach(l=>{if(l.layers)finishOrder(l);});if(root.stackLayout)H.order(root);}
function button(p,name,label,variant,state,small,iconOnly,iconKey){var hh=small?28:36;var primary=variant==='primary';var disabled=state==='disabled';var fill=disabled?'panel':primary?'ink':variant==='secondary'?'panel':variant==='danger'?'negative-mark':state==='hover'?'hover':null;var text=disabled?'tertiary':primary?'inverse':variant==='danger'?'negative':'ink';if(variant==='danger')fill=state==='hover'?'hover':'panel';if(state==='hover'&&variant==='secondary')fill='hover';var b=fr(p,name,'row',8,{top:0,right:iconOnly?0:14,bottom:0,left:iconOnly?0:14},iconOnly?hh:undefined,hh,fill,state==='focus'?'accent':variant==='outline'?'control-line':null,primary?999:8);b.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;b.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;if(state==='focus'){b.style.borders=[{color:H.sw(APP,'accent'),thickness:2,position:sketch.Style.BorderPosition.Inside}];}if(iconKey||iconOnly||state==='loading')ic(b,state==='loading'?'loader':iconKey||'plus',text,small?14:16);if(!iconOnly)t(b,disabled?'Unavailable':state==='loading'?'Saving changes':label,text,small?12:14);return b;}
function field(p,name,label,state,kind){var box=fr(p,name,'col',8,0,300);if(label)t(box,label,'secondary',13);var b=fr(box,'field','row',10,{top:0,right:12,bottom:0,left:12},300,kind==='textarea'?88:36,state==='disabled'?'panel':state==='filled'?'panel':'surface',state==='focus'?'accent':state==='invalid'?'negative':'control-line',8);b.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;if(kind==='leading'||kind==='search')ic(b,kind==='search'?'search':'user');var tx=state==='filled'?'Research studio':kind==='search'?'Search anything…':kind==='textarea'?'Tell us about your project…':'A new beginning';t(b,tx,state==='disabled'?'tertiary':'secondary',14,kind==='search'?206:kind==='trailing'?222:240);if(kind==='search')t(b,'⌘K','tertiary',12);if(kind==='trailing')ic(b,'chevronsUpDown');if(label)t(box,state==='invalid'?'Enter a project name.':'A name your team can recognise.',state==='invalid'?'negative':'tertiary',12,300);return box;}
function menu(p,values,selected){var m=fr(p,'menu','col',2,6,260,undefined,'surface','line',16);m.style.shadows=[{color:'#0000001f',blur:24,spread:0,x:0,y:8}];values.forEach((x,i)=>{var r=fr(m,'option','row',8,{top:0,right:10,bottom:0,left:10},248,32,i===selected?'hover':null,null,6);r.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;t(r,x,'ink',14,196);if(i===selected)ic(r,'check','ink');});return m;}
t(sh,FAMILY+' — '+APP,'ink',20);t(sh,'HARSO  /  BOUNDARYLESS  /  CONTROLS','tertiary',12);
['default','focus','disabled','open'].forEach(st=>{var r=row('Persistent choice · '+st);var s=sym(r,'popup/'+st,'col',8);t(s,'Audience','secondary',13);var b=fr(s,'field','row',12,{top:0,right:12,bottom:0,left:12},260,36,st==='disabled'?'panel':'surface',st==='focus'?'accent':'control-line',8);b.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;t(b,'Our team',st==='disabled'?'tertiary':'ink',14,208);ic(b,'chevronsUpDown');if(st==='open')menu(s,['Our team','Everyone','Partners','Only me'],0);});
finishOrder(sh);H.relayout(sh);var made=H.symbolize(sh,new RegExp('^'+FAMILY+'/'));H.out({ok:true,family:FAMILY,app:APP,sheet:String(sh.id),count:made.length,made:made,h:Math.round(sh.frame.height),w:Math.round(sh.frame.width),y:sh.frame.y});
