// Lane-local native manage building blocks. No shared helper mutations.
var DOCID='40E7AE0D-B568-476B-9630-D3AB62280DBE';
doc=sketch.getDocuments().find(function(d){return String(d.id)===DOCID;}); H.doc=doc;
var IDS=['projects','projects--empty','project','recent','artifacts','artifacts--empty','artifacts--detail','routines','routines--new','customize','customize--profile'];
function C(role){return H.sw(APP,role);}
function F(p,n,w,h,dir,gap,pad,fill){var f=H.frame({parent:p,name:n,w:w,h:h,dir:dir||'col',gap:gap||0,pad:pad||0,fill:fill});f.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;return f;}
function T(p,t,size,role,w,bold){return H.sft({parent:p,text:t,size:size||13,weight:bold?7:5,color:C(role||'ink'),w:w});}
function R(p,n,w,h,gap){var r=F(p,n,w,h,'row',gap||8);r.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;return r;}
function spacer(p,vertical){var sp=F(p,'spacer',1,1);sp[vertical?'verticalSizing':'horizontalSizing']=sketch.FlexSizing.Fill;return sp;}
function icon(p,g,color,size){return H.sf(p,g,{size:size||15,weight:6,color:color||C('secondary')});}
function button(p,label,target,primary,glyph){var b=H.frame({parent:p,name:'link:'+target,dir:'row',gap:6,pad:{top:0,right:12,bottom:0,left:12},h:24,radius:5,fill:C(primary?'accent':'surface'),border:primary?null:C('line-strong')});if(glyph)icon(b,glyph,primary?'#ffffff':C('secondary'),12);T(b,label,13,primary?'on-accent':'ink');if(primary)b.layers.forEach(function(l){if(l.type==='Text')l.style.textColor='#ffffff';});H.order(b);return b;}
// Native controls always use system text; tint is local to this lane.
function btn(p,label,target,primary,glyph){var b=H.frame({parent:p,name:'link:'+target,dir:'row',gap:6,pad:{top:0,right:12,bottom:0,left:12},h:24,radius:5,fill:C(primary?'accent':'surface'),border:primary?null:C('line-strong')});if(glyph)icon(b,glyph,primary?'#ffffff':C('secondary'),12);H.sft({parent:b,text:label,size:13,weight:6,color:primary?'#ffffff':C('ink')});H.order(b);return b;}
function section(p,label,w){var r=R(p,'section',w,28);T(r,label.toUpperCase(),11,'tertiary',null,true);H.order(r);}
function line(p,w){H.rect({parent:p,name:'separator',w:w,h:1,fill:C('line')});}
function segment(p,labels,target){var sg=H.frame({parent:p,name:'segmented-control',dir:'row',gap:2,pad:2,h:24,radius:6,fill:H.alpha(H.hex(APP,'ink'),0.08)});labels.forEach(function(t,i){var b=H.frame({parent:sg,name:'link:'+target,dir:'row',pad:{top:0,right:18,bottom:0,left:18},h:20,radius:4,fill:i?null:C('surface'),shadow:i?null:{color:'#00000018',blur:2,x:0,y:1,spread:0}});T(b,t,12,'ink',null,!i);H.order(b);});H.order(sg);return sg;}
function field(p,label,value,w,multi,select){var row=R(p,'form:'+label,w,multi?76:28,12);row.stackLayout.alignItems=multi?sketch.StackLayout.AlignItems.Start:sketch.StackLayout.AlignItems.Center;var lab=T(row,label+':',13,'secondary',120);lab.style.alignment=sketch.Text.Alignment.right;var ctl=F(row,'control:'+label,w-132,multi?76:24,'row',6,{top:multi?8:0,right:8,bottom:0,left:8},C('canvas'));ctl.style.corners.radii=[5,5,5,5];ctl.style.borders=[{color:C('line-strong'),thickness:1,position:sketch.Style.BorderPosition.Inside}];ctl.stackLayout.alignItems=multi?sketch.StackLayout.AlignItems.Start:sketch.StackLayout.AlignItems.Center;T(ctl,value,13,'ink',w-168);if(select)icon(ctl,'chevron_down',C('secondary'),10);H.order(ctl);H.order(row);}
function group(p,title,w){var g=F(p,'GroupBox/'+title,w,null,'col',8,16,C('surface'));g.style.corners.radii=[10,10,10,10];g.style.borders=[{color:C('line'),thickness:1,position:sketch.Style.BorderPosition.Inside}];T(g,title,13,'ink',null,true);return g;}
function toggle(p,label,on,w,desc){var r=R(p,'link:customize--profile',w,desc?42:28,10);var tt=F(r,'text',w-70,null,'col',2);T(tt,label,13);if(desc)T(tt,desc,11,'tertiary');H.order(tt);spacer(r);var sw=H.frame({parent:r,name:'switch',w:32,h:18,pad:2,radius:9,fill:on?C('accent'):C('line-strong'),justify:on?sketch.StackLayout.JustifyContent.End:sketch.StackLayout.JustifyContent.Start});H.rect({parent:sw,name:'knob',w:14,h:14,oval:true,fill:'#ffffff'});H.order(sw);H.order(r);}
function titleBlock(p,title,subtitle,w){T(p,title,24,'ink',w,true);T(p,subtitle,13,'secondary',w);}
var conversations=[['Move the billing webhook handler','Weave Cloud','14:40','41k'],['Draft the Q3 investor update','Personal','13:12','18k'],['Why is the Mac build 40 MB bigger','Weave Cloud','11:48','27k'],['Review the SATS delivery packet','Aheli ops','10:30','12k'],['Compare project memory strategies','Personal','09:52','32k'],['Prepare the weekly engineering digest','Weave Cloud','09:06','16k'],['Reconcile August supplier invoices','Aheli ops','17:42','24k'],['Plan the September product milestones','Personal','16:18','21k'],['Audit the session persistence boundary','Weave Cloud','15:06','36k'],['Write the W Sentosa residency outline','Personal','14:22','15k'],['Check staging webhook replay safety','Weave Cloud','11:10','29k'],['Build a quarterly cash-flow forecast','Aheli ops','09:34','22k']];
function table(p,w,rows,header){var tb=F(p,'conversation-table',w,null,'col',0);if(header){var h=R(tb,'columns',w,28,12);icon(h,'bubble',C('tertiary'),13);T(h,'Title',11,'tertiary',w-460,true);T(h,'Project',11,'tertiary',150,true);T(h,'When',11,'tertiary',90,true);T(h,'Tokens',11,'tertiary',65,true);H.order(h);line(tb,w);}rows.forEach(function(d,i){var r=R(tb,'link:conversation',w,28,12);if(i%2===0)r.style.fills=[{color:H.alpha(H.hex(APP,'ink'),0.025),fillType:sketch.Style.FillType.Color}];r.stackLayout.padding={top:0,right:8,bottom:0,left:8};icon(r,'bubble',C('secondary'),13);T(r,d[0],13,'ink',w-468);T(r,d[1],12,'secondary',150);T(r,d[2],12,'tertiary',90);T(r,d[3],12,'tertiary',65);H.order(r);});H.order(tb);}
function empty(p,w,text,action,target){var e=F(p,'empty-state',w,680,'col',16);e.stackLayout.alignItems=sketch.StackLayout.AlignItems.Center;e.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;var ic=H.frame({parent:e,name:'sparkle-mark',w:64,h:64,pad:0,radius:18,fill:H.alpha('#d79439',0.12),justify:sketch.StackLayout.JustifyContent.Center});icon(ic,'sparkles','#c28734',32);H.order(ic);T(e,text,17,'secondary');btn(e,action,target,true,'plus');H.order(e);}
function projectCards(p,w){var grid=R(p,'project-grid',w,190,16);[['Personal','12 conversations · 8 artifacts','Active 13 minutes ago','#d28a37','Notes, plans and things worth remembering.'],['Weave Cloud','48 conversations · 24 artifacts','Active 2 minutes ago','#4388c6','Product engineering for the agent cloud.'],['Aheli ops','26 conversations · 16 artifacts','Active 2 hours ago','#59946e','Orders, deliveries and supplier accounts.']].forEach(function(d,i){var c=F(grid,'link:project',(w-32)/3,190,'col',10,16,C(i?'surface':'accent-soft'));c.style.corners.radii=[10,10,10,10];c.style.borders=[{color:C(i?'line':'accent'),thickness:1,position:sketch.Style.BorderPosition.Inside}];var top=R(c,'folder-row',(w-32)/3-32,38);var ic=H.frame({parent:top,name:'folder-squircle',w:38,h:38,pad:0,radius:10,fill:H.alpha(d[3],0.14),justify:sketch.StackLayout.JustifyContent.Center});icon(ic,'folder',d[3],22);H.order(ic);spacer(top);if(!i)icon(top,'checkmark_circle_fill',C('accent'),16);H.order(top);T(c,d[0],16,'ink',null,true);T(c,d[4],12,'secondary');T(c,d[1],12,'secondary');T(c,d[2],11,'tertiary');H.order(c);});H.order(grid);}
var artifacts=[['doc','Q3 investor update','Markdown · 18 KB','Personal · Today, 13:12','#bd8840','Q3 / 2026\n\nA focused quarter.\nA more reliable cloud.'],['chevron_left_right','Billing webhook extraction','TypeScript diff · 3 files','Weave Cloud · Today, 14:40','#539d76','+ enqueue(event.id)\n+ replayLedger(event)\n− await sendEmail()'],['photo_on_rectangle','Weave launch direction','PNG · 1440 × 900','Personal · Yesterday, 14:22','#727bc5','WEAVE\n\nA quieter kind of capable.'],['doc','SATS delivery checklist','Markdown · 12 KB','Aheli ops · Today, 10:30','#bd8840','DELIVERY / 18 SEPT\n\n01  Confirm dock slot\n02  Check cold-chain log'],['chevron_left_right','Session recovery tests','Swift · 6 tests','Weave Cloud · Yesterday, 15:06','#539d76','func testRecovery() {\n  restore(session)\n  assertNoLostTurns()\n}'],['doc','September milestones','Markdown · 9 KB','Personal · Yesterday, 16:18','#bd8840','SEPTEMBER\n\nShip the native Mac app.\nMake work inspectable.']];
function artifactGrid(p,w){for(var row=0;row<2;row++){var gr=R(p,'artifact-grid-row',w,242,16);artifacts.slice(row*3,row*3+3).forEach(function(d){var c=F(gr,'link:artifacts--detail',(w-32)/3,242,'col',10,12,C('surface'));c.style.corners.radii=[10,10,10,10];c.style.borders=[{color:C('line'),thickness:1,position:sketch.Style.BorderPosition.Inside}];var th=F(c,'thumbnail',(w-32)/3-24,142,'col',8,16,H.alpha(d[4],0.13));th.style.corners.radii=[6,6,6,6];icon(th,d[0],d[4],22);T(th,d[5],13,'secondary');H.order(th);T(c,d[1],14,'ink',null,true);T(c,d[2],12,'secondary');T(c,d[3],11,'tertiary');H.order(c);});H.order(gr);}}
function routines(p,w){var tab=F(p,'routines-list',w,null,'col',0);var hr=R(tab,'columns',w,28,12);T(hr,'Routine',11,'tertiary',300,true);T(hr,'Schedule',11,'tertiary',210,true);T(hr,'Last run',11,'tertiary',280,true);T(hr,'Actions',11,'tertiary',null,true);H.order(hr);line(tab,w);[['Daily brief','Inbox, calendar and open work','Every day · 08:00','Today, 08:00 · 42 sec',true],['Weekly digest','Decisions and milestones across projects','Friday · 17:00','11 Sep, 17:00 · 1 min 12 sec',false],['Delivery watch','Check SATS orders due in the next 48 hours','Weekdays · 16:00','Today, 16:00 · 28 sec',true],['Cloud health check','Summarize staging errors and failed runs','Every day · 09:00','Today, 09:00 · 36 sec',true]].forEach(function(d,i){var r=R(tab,'routine-row',w,68,12);var t=F(r,'name',300,null,'col',4);T(t,d[0],13,'ink',null,true);T(t,d[1],11,'tertiary');H.order(t);T(r,d[2],13,'secondary',210);var st=R(r,'status',280,28,8);H.rect({parent:st,name:'status-dot',w:6,h:6,oval:true,fill:C(d[4]?'positive':'tertiary')});T(st,d[4]?d[3]:'Paused · '+d[3],12,'secondary');H.order(st);H.sfBtn(r,'link:activity--work','play',APP,{w:28,h:28,size:13});H.sfBtn(r,'link:routines',d[4]?'pause':'arrow_clockwise',APP,{w:28,h:28,size:13});H.sfBtn(r,'link:routines--new','pencil',APP,{w:28,h:28,size:13});H.order(r);line(tab,w);});H.order(tab);}
function profiles(p,w){var r=R(p,'profiles',w,114,12);[['General','Ready · Default','Everyday work across your projects','sparkles'],['Reviewer','Ready','Code, risk and acceptance checks','checklist_shield'],['Research','Ready','Sources, evidence and synthesis','book']].forEach(function(d,i){var c=F(r,'link:customize--profile',(w-24)/3,114,'col',7,14,C(i?'surface':'accent-soft'));c.style.corners.radii=[10,10,10,10];c.style.borders=[{color:C(i?'line':'accent'),thickness:1,position:sketch.Style.BorderPosition.Inside}];var cr=R(c,'title',(w-24)/3-28,22);icon(cr,d[3],C('accent'),16);T(cr,d[0],14,'ink',null,true);spacer(cr);T(cr,d[1],11,'positive');H.order(cr);T(c,d[2],12,'secondary');T(c,i?'Click to configure':'Used for new conversations',11,'tertiary');H.order(c);});H.order(r);}
function buildShell(){var pn='Proto macOS '+APP.split('/')[0];var page=H.page(pn);var full='Screen/macos/'+APP+'/'+ID;page.layers.slice().forEach(function(l){if(l.name===full||(l.name.indexOf('caption/')===0&&l.name.split('/').pop()===ID))l.remove();});var s=H.screen({page:pn,platform:'macos',app:APP,id:ID,w:1440,h:900,x:IDS.indexOf(ID)*1560,y:1060});var base=ID.split('--')[0];var titles={projects:'Projects',project:'Personal',recent:'Recent',artifacts:'Artifacts',routines:'Routines',customize:ID==='customize--profile'?'General':'Customize'};var subtitles={projects:'3 projects',project:'12 conversations · 8 artifacts',recent:'All projects',artifacts:'48 published artifacts',routines:'3 active · 1 paused',customize:'Make Weave your own'};var tools=base==='projects'?[['link:project','plus','New project',true]]:base==='routines'?[['link:routines--new','plus','New routine',true]]:base==='recent'?[['link:new-conversation','square_pencil','New conversation',true]]:base==='project'?[['link:project','ellipsis']]:[];
var w=H.macWindow(s,APP,{active:base,title:titles[base],subtitle:ID.indexOf('--empty')>=0?'':subtitles[base],tools:tools,search:base!=='customize'&&base!=='project',inspector:base==='project'?'Project':false,gap:16});w.main.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;w.finish();s.frame.x=IDS.indexOf(ID)*1560;s.frame.y=1060;return s;}
function resolve(){return doc.pages.find(function(p){return p.name==='Proto macOS '+APP.split('/')[0];}).layers.find(function(l){return l.name==='Screen/macos/'+APP+'/'+ID;});}
function buildBody(s){var col=s.layers.find(function(l){return l.name==='content-col';});var m=col.layers.find(function(l){return l.name==='main';});var w=ID==='project'?808:1128;var base=ID.split('--')[0];
if(ID.indexOf('--empty')>=0){empty(m,w,base==='projects'?'A place for every part of your work.':'No artifacts are published yet',base==='projects'?'Create a project':'Start a conversation',base==='projects'?'project':'new-conversation');}
else if(base==='projects'){titleBlock(m,'Your projects','Keep conversations, files and memory together.',w);projectCards(m,w);var cr=R(m,'create-project',w,40,10);icon(cr,'plus',C('accent'),14);T(cr,'New project',13,'secondary',110);var inp=F(cr,'name-input',280,24,'row',0,{top:0,right:8,bottom:0,left:8},C('surface'));inp.style.corners.radii=[5,5,5,5];inp.style.borders=[{color:C('line-strong'),thickness:1,position:sketch.Style.BorderPosition.Inside}];T(inp,'September planning',13);H.order(inp);btn(cr,'Create','project',true);H.order(cr);section(m,'Latest across projects',w);table(m,w,conversations.slice(0,6),true);T(m,'Project memory and files stay separate. Choose a project to pick up where you left off.',12,'tertiary');}
else if(base==='project'){titleBlock(m,'Personal','Notes, plans and things worth remembering.',w);segment(m,['Conversations','Work'],'activity--work');section(m,'Recent conversations',w);var ls=F(m,'recent-conversations',w,null,'col',0);[conversations[1],conversations[4],conversations[7],conversations[9]].forEach(function(d,i){var r=R(ls,'link:conversation',w,48,12);icon(r,'bubble',C('secondary'),15);var tx=F(r,'text',580,null,'col',4);T(tx,d[0],13,'ink',null,true);T(tx,i<2?'Today · General':'Yesterday · General',11,'tertiary');H.order(tx);spacer(r);T(r,d[3]+' tokens',12,'tertiary');H.order(r);line(ls,w);});H.order(ls);section(m,'Work',w);[['checkmark_circle','Q3 update ready for review','18 KB · Markdown','positive'],['clock','Research memory strategies','Running · 2 min','accent'],['checkmark_circle','September milestones published','9 KB · Markdown','positive']].forEach(function(d){var r=R(m,'link:activity--work',w,36,10);icon(r,d[0],C(d[3]),15);T(r,d[1],13,'ink',490);spacer(r);T(r,d[2],12,'tertiary');H.order(r);});spacer(m,true);var cp=F(m,'link:conversation',w,86,'col',12,14,C('surface'));cp.style.corners.radii=[12,12,12,12];cp.style.borders=[{color:C('line-strong'),thickness:1,position:sketch.Style.BorderPosition.Inside}];T(cp,'Start a conversation in Personal',14,'tertiary');var rr=R(cp,'composer-actions',w-28,28);H.sfBtn(rr,'link:project','plus',APP,{w:28,h:28});spacer(rr);T(rr,'General',12,'secondary');H.sfBtn(rr,'link:conversation','arrow_up',APP,{w:28,h:28,radius:14,fill:C('accent'),color:'#ffffff'});H.order(rr);H.order(cp);var ins=s.layers.find(function(l){return l.name==='inspector';});var ib=F(ins,'inspector-body',320,null,'col',12,20);[['Instructions','Keep answers direct. Cite sources for research. Ask before sending anything externally.'],['Memory','Prefer Singapore time (SGT).\nUse SGD for financial planning.\nKeep personal and company work separate.'],['Sources','Q3 investor notes.md\nSeptember milestones.md\nProduct reading list.md'],['Working location','~/Developer/personal']].forEach(function(d){section(ib,d[0],280);T(ib,d[1],13,'secondary',280);line(ib,280);});var r=R(ib,'memory-status',280,28);icon(r,'lock',C('positive'),12);T(r,'Stored on this Mac',12,'tertiary');H.order(r);H.order(ib);H.order(ins);}
else if(base==='recent'){section(m,'Today',w);table(m,w,conversations.slice(0,6),true);section(m,'Yesterday',w);table(m,w,conversations.slice(6),false);T(m,'12 conversations · Sorted by last activity',12,'tertiary');}
else if(base==='artifacts'){var rr=R(m,'artifact-controls',w,28);segment(rr,['All','Documents','Code','Images'],'artifacts');spacer(rr);T(rr,'Last modified',12,'secondary');icon(rr,'chevron_down',C('tertiary'),10);H.order(rr);artifactGrid(m,w);T(m,'6 of 48 artifacts · Saved from your conversations',12,'tertiary');}
else if(base==='routines'){titleBlock(m,'Work that happens on schedule','Weave runs these routines even when you are away.',w);routines(m,w);section(m,'Recent runs',w);[['Daily brief','8 priorities from your inbox and calendar','Today, 08:00'],['Cloud health check','No new staging errors. 212 tests passing.','Today, 09:00'],['Delivery watch','2 orders due Thursday. Dock slot confirmed.','Yesterday, 16:00']].forEach(function(d){var r=R(m,'link:activity--work',w,48,12);icon(r,'checkmark_circle',C('positive'),16);T(r,d[0],13,'ink',180,true);T(r,d[1],13,'secondary',640);spacer(r);T(r,d[2],12,'tertiary');H.order(r);});T(m,'Schedules use Asia/Singapore (SGT). External actions still require your approval.',12,'tertiary');}
else if(ID==='customize--profile'){titleBlock(m,'General','Your default profile for thoughtful, everyday work.',w);var g=group(m,'Profile',760);field(g,'Name','General',728);field(g,'Description','Be direct, curious and practical. Explain trade-offs, cite evidence and turn decisions into clear next steps.',728,true);field(g,'Model','Claude Fable 5.1',728,false,true);H.order(g);var g2=group(m,'Tools',760);[['Web search',true],['Read and edit files',true],['Run terminal commands',true],['Send email',false]].forEach(function(d){var r=R(g2,'link:customize--profile',728,28,8);icon(r,d[1]?'checkmark_square':'rectangle_on_rectangle',C(d[1]?'accent':'tertiary'),16);T(r,d[0],13);H.order(r);});T(g2,'Terminal commands and external messages ask for approval.',12,'tertiary');H.order(g2);var act=R(m,'actions',760,28);spacer(act);btn(act,'Cancel','back');btn(act,'Save','customize',true);H.order(act);}
else if(base==='customize'){section(m,'Profiles',w);profiles(m,w);var cols=R(m,'settings-columns',w,null,20);cols.stackLayout.alignItems=sketch.StackLayout.AlignItems.Start;var left=F(cols,'voice-personality',554,null,'col',16);var v=group(left,'Voice',554);field(v,'Voice','Juniper · Warm and clear',522,false,true);field(v,'Speaking rate','Normal',522,false,true);toggle(v,'Read responses aloud',false,522);H.order(v);var per=group(left,'Personality',554);field(per,'Style','Direct and thoughtful',522,false,true);field(per,'Detail','Adapt to the task',522,false,true);toggle(per,'Remember my preferences',true,522);H.order(per);H.order(left);var right=F(cols,'tools-skills',554,null,'col',16);var tools=group(right,'Tools',554);toggle(tools,'Web search',true,522,'Find current information with sources');toggle(tools,'Files and terminal',true,522,'Ask before running commands');toggle(tools,'Connected apps',true,522,'Google Workspace, Linear and GitHub');H.order(tools);var skills=group(right,'Skills',554);toggle(skills,'Code review',true,522);toggle(skills,'Research & citations',true,522);toggle(skills,'Writing in my voice',false,522);H.order(skills);H.order(right);H.order(cols);T(m,'Changes apply to new conversations. Existing conversations keep their current profile.',12,'tertiary');}
H.order(m);col.stackLayout.apply();s.stackLayout.apply();s.frame.x=IDS.indexOf(ID)*1560;s.frame.y=1060;
}
function overlay(s){if(ID==='routines--new'){H.macScrim(s,APP);var sh=F(s,'sheet/New routine',520,null,'col',16,24,C('surface'));sh.style.corners.radii=[0,0,12,12];sh.style.shadows=[{color:'#00000040',blur:32,x:0,y:16,spread:0}];T(sh,'New Routine',15,'ink',null,true);T(sh,'Give a recurring task a name and a schedule.',13,'secondary');field(sh,'Name','Morning priorities',472);field(sh,'Prompt','Summarize my calendar, unread priority email and open Linear issues. Suggest the three most important actions for today.',472,true);field(sh,'Schedule','Every day at 08:00',472,false,true);field(sh,'Profile','General',472,false,true);field(sh,'Project','Personal',472,false,true);T(sh,'Timezone: Asia/Singapore · Requires approval to send messages.',11,'tertiary',472);var actions=R(sh,'sheet-actions',472,28);spacer(actions);btn(actions,'Cancel','back');btn(actions,'Create','routines',true);H.order(actions);H.order(sh);sh.frame.x=588;sh.frame.y=52;sh.moveToFront();}
if(ID==='artifacts--detail'){H.macScrim(s,APP);var sh=F(s,'sheet/Artifact detail',720,740,'col',16,24,C('surface'));sh.style.corners.radii=[0,0,12,12];sh.style.shadows=[{color:'#00000040',blur:32,x:0,y:16,spread:0}];var hd=R(sh,'header',672,30);icon(hd,'doc',C('accent'),18);T(hd,'Q3 investor update',15,'ink',null,true);spacer(hd);btn(hd,'Share','artifacts--detail',false,'square_and_arrow_up');btn(hd,'Done','back');H.order(hd);var rr=R(sh,'controls',672,28);segment(rr,['Preview','Code'],'artifacts--detail');spacer(rr);T(rr,'Markdown · 18 KB · v3',12,'tertiary');H.order(rr);line(sh,672);var paper=F(sh,'document-preview',672,500,'col',16,32,C('canvas'));T(paper,'STRAITS LAB / QUARTERLY LETTER',11,'tertiary',null,true);T(paper,'A focused quarter.\nA more reliable cloud.',28,'ink',580,true);T(paper,'15 September 2026 · Abhi Bansal',12,'tertiary');T(paper,'This quarter we concentrated on one promise: agents should make progress you can inspect, trust and recover.',15,'ink',580);T(paper,'What shipped',17,'ink',null,true);T(paper,'• Durable sessions with recovery across restarts\n• An inspectable work log for every tool run\n• Native Mac workflows for projects and artifacts',14,'secondary',580);T(paper,'What comes next',17,'ink',null,true);T(paper,'We are tightening onboarding and approval boundaries before opening the next cohort. Reliability remains the release gate.',14,'secondary',580);H.order(paper);var ft=R(sh,'footer',672,28);icon(ft,'bubble',C('tertiary'),13);T(ft,'From “Draft the Q3 investor update”',12,'secondary');spacer(ft);btn(ft,'Open conversation','conversation');H.order(ft);H.order(sh);sh.frame.x=488;sh.frame.y=52;sh.moveToFront();var pop=F(s,'popover/Share',244,null,'col',0,8,C('surface'));pop.style.corners.radii=[20,20,20,20];pop.style.borders=[{color:C('line-strong'),thickness:1,position:sketch.Style.BorderPosition.Inside}];pop.style.shadows=[{color:'#00000030',blur:24,x:0,y:8,spread:0}];[['link','Copy link'],['envelope','Mail'],['doc','Export Markdown']].forEach(function(d){var r=R(pop,'link:artifacts--detail',228,30,10);r.stackLayout.padding={top:0,right:10,bottom:0,left:10};icon(r,d[0],C('secondary'),14);T(r,d[1],13);H.order(r);});H.order(pop);pop.frame.x=938;pop.frame.y=126;var arrow=H.rect({parent:s,name:'popover-arrow',w:14,h:14,radius:2,fill:C('surface')});arrow.transform.rotation=45;arrow.frame.x=1080;arrow.frame.y=120;arrow.moveToFront();pop.moveToFront();}
}
function normalize(s){function walk(l){if(l.name.indexOf('link:')===0)l.name=l.name.replace(/ \d+$/,'');(l.layers||[]).forEach(walk);}walk(s);}

var APP="Dark/Clean";var ID="recent";
var s=resolve();buildBody(s);console.log(JSON.stringify({id:ID,app:APP,frame:String(s.id),stage:"body"}));