import { createContext, useContext, useEffect, useId, useRef, useState, type ComponentPropsWithRef, type CSSProperties, type ElementType, type ReactNode } from "react";
import { Button } from "./primitives";

type DivProps = ComponentPropsWithRef<"div">;
export type AttachmentData = { id: string; name?: string; url?: string; mediaType?: string; size?: number; status?: "queued" | "uploading" | "ready" | "error"; progress?: number; error?: string; [key: string]: unknown };
type AttachmentState = { data: AttachmentData; onRemove?: () => void; onRetry?: () => void; variant: "grid" | "inline" | "list" };
const AttachmentsContext = createContext<{ variant: "grid" | "inline" | "list" } | null>(null);
const AttachmentContext = createContext<AttachmentState | null>(null);
function useAttachments() { const state = useContext(AttachmentsContext); if (!state) throw new Error("Attachment parts require Attachments."); return state; }
function useAttachment() { const state = useContext(AttachmentContext); if (!state) throw new Error("Attachment parts require Attachment."); return state; }
export function getAttachmentLabel(data: AttachmentData) { return data.name || data.mediaType || "Attachment"; }
export function getMediaCategory(data: AttachmentData) { const category = data.mediaType?.split("/")[0]; return category === "image" || category === "video" || category === "audio" ? category : "file"; }
function formatBytes(size?: number) { if (!Number.isFinite(size) || size! < 0) return undefined; if (size! < 1024) return `${size} B`; if (size! < 1024 ** 2) return `${Math.round(size! / 1024)} KB`; return `${(size! / 1024 ** 2).toFixed(1)} MB`; }
function progressValue(value?: number) { return Number.isFinite(value) ? Math.min(100, Math.max(0, value!)) : undefined; }

export function Attachments({ variant = "grid", className = "", ...props }: DivProps & { variant?: "grid" | "inline" | "list" }) { return <AttachmentsContext value={{ variant }}><div {...props} className={`hk-attachments hk-attachments-${variant} ${className}`} /></AttachmentsContext>; }
export function Attachment({ data, onRemove, onRetry, children, className = "", ...props }: DivProps & { data: AttachmentData; onRemove?: () => void; onRetry?: () => void }) { const { variant } = useAttachments(); return <AttachmentContext value={{ data, onRemove, onRetry, variant }}><div {...props} className={`hk-attachment hk-attachment-${data.status ?? "ready"} ${className}`} data-attachment-id={data.id} aria-label={getAttachmentLabel(data)}>{children ?? <><AttachmentPreview /><AttachmentInfo /><AttachmentProgress />{data.status === "error" && onRetry && <AttachmentRetry />}{onRemove && <AttachmentRemove />}</>}</div></AttachmentContext>; }
export function AttachmentPreview({ fallbackIcon, className = "", ...props }: DivProps & { fallbackIcon?: ReactNode }) { const { data } = useAttachment(); const name = getAttachmentLabel(data); const category = getMediaCategory(data); return <div {...props} className={`hk-attachment-preview ${!data.url ? "hk-attachment-preview--fallback" : ""} ${className}`}>{category === "image" && data.url ? <img src={data.url} alt={name} /> : category === "video" && data.url ? <video src={data.url} aria-label={name} controls /> : category === "audio" && data.url ? <audio src={data.url} aria-label={name} controls /> : <span aria-hidden="true">{fallbackIcon ?? <svg aria-hidden="true" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h5"/></svg>}</span>}</div>; }
export function AttachmentInfo({ showMediaType = false, children, className = "", ...props }: DivProps & { showMediaType?: boolean }) { const { data } = useAttachment(); return <div {...props} className={`hk-attachment-info ${className}`}>{children ?? <><span className="hk-attachment-name" title={getAttachmentLabel(data)}>{getAttachmentLabel(data)}</span>{showMediaType && data.mediaType && <span className="hk-attachment-type">{data.mediaType}</span>}{formatBytes(data.size) && <span className="hk-attachment-size">{formatBytes(data.size)}</span>}{data.error && <span className="hk-attachment-error" role="alert">{data.error}</span>}</>}</div>; }
export function AttachmentProgress({ className = "", ...props }: DivProps) { const { data } = useAttachment(); const value = progressValue(data.progress); if (data.status !== "uploading" && data.status !== "queued") return null; return <div {...props} className={`hk-attachment-progress ${className}`} role="progressbar" aria-label={`Uploading ${getAttachmentLabel(data)}`} aria-valuemin={0} aria-valuemax={100} {...(value === undefined ? {} : { "aria-valuenow": value })}><span style={value === undefined ? undefined : { width: `${value}%` }} /></div>; }
export function AttachmentRemove({ label: removeLabel = "Remove", children, className = "", onClick, ...props }: ComponentPropsWithRef<typeof Button> & { label?: string }) { const { onRemove } = useAttachment(); return <Button {...props} type="button" aria-label={removeLabel} disabled={props.disabled || (!onRemove && !onClick)} className={`hk-attachment-remove ${className}`} onClick={event => { event.stopPropagation(); onClick?.(event); if (!event.defaultPrevented) onRemove?.(); }}>{children ?? <svg aria-hidden="true" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="m6 6 12 12M6 18 18 6"/></svg>}</Button>; }
export function AttachmentRetry({ label: retryLabel = "Retry", children, className = "", onClick, ...props }: ComponentPropsWithRef<typeof Button> & { label?: string }) { const { onRetry } = useAttachment(); return <Button {...props} type="button" aria-label={retryLabel} disabled={props.disabled || (!onRetry && !onClick)} className={`hk-attachment-retry ${className}`} onClick={event => { event.stopPropagation(); onClick?.(event); if (!event.defaultPrevented) onRetry?.(); }}>{children ?? "Retry"}</Button>; }
const HoverCardContext = createContext<{ open: boolean; identity: string; request: (open: boolean) => void } | null>(null);
export function AttachmentHoverCard({ children, as: Element = "div", open, defaultOpen = false, onOpenChange, openDelay = 700, closeDelay = 300, className = "", ...props }: DivProps & { as?: ElementType; open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void; openDelay?: number; closeDelay?: number }) {
  const identity = useId();
  const [localOpen, setLocalOpen] = useState(defaultOpen);
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const current = open ?? localOpen;
  const cancel = () => clearTimeout(timer.current);
  const request = (next: boolean) => { cancel(); if (next === current) return; if (open === undefined) setLocalOpen(next); onOpenChange?.(next); };
  useEffect(() => () => clearTimeout(timer.current), []);
  useEffect(() => { cancel(); }, [open]);
  return <HoverCardContext value={{ open: current, identity, request }}><Element {...props} className={`hk-attachment-hover-card ${className}`} data-open={current || undefined} onPointerEnter={(event: React.PointerEvent<HTMLDivElement>) => { props.onPointerEnter?.(event); if (!event.defaultPrevented) { cancel(); timer.current = setTimeout(() => request(true), Math.max(0, openDelay)); } }} onPointerLeave={(event: React.PointerEvent<HTMLDivElement>) => { props.onPointerLeave?.(event); if (!event.defaultPrevented && !event.currentTarget.contains(document.activeElement)) { cancel(); timer.current = setTimeout(() => request(false), Math.max(0, closeDelay)); } }} onFocus={(event: React.FocusEvent<HTMLDivElement>) => { props.onFocus?.(event); if (!event.defaultPrevented) request(true); }} onBlur={(event: React.FocusEvent<HTMLDivElement>) => { props.onBlur?.(event); if (!event.defaultPrevented && !event.currentTarget.contains(event.relatedTarget)) { if (current && !event.relatedTarget && event.target instanceof HTMLElement && event.target.matches(":disabled")) event.currentTarget.querySelector<HTMLElement>(`[aria-controls="${identity}"]:not(:disabled)`)?.focus(); else if (!event.currentTarget.matches(":hover")) request(false); } }} onKeyDown={(event: React.KeyboardEvent<HTMLDivElement>) => { props.onKeyDown?.(event); if (!event.defaultPrevented && event.key === "Escape") { event.preventDefault(); event.stopPropagation(); event.currentTarget.querySelector<HTMLElement>(`[aria-controls="${identity}"]`)?.focus(); request(false); } }}>{children}</Element></HoverCardContext>;
}
export function AttachmentHoverCardTrigger({ className = "", style, ...props }: ComponentPropsWithRef<"button">) { const card = useContext(HoverCardContext); return <button {...props} style={{ ...style, anchorName: card ? `--hk-hover-${card.identity.replace(/[^a-z0-9_-]/gi, "")}` : undefined } as CSSProperties} type="button" aria-expanded={card?.open} aria-controls={card?.identity} className={`hk-attachment-hover-trigger ${className}`} onClick={event => { props.onClick?.(event); if (!event.defaultPrevented) card?.request(!card.open); }} />; }
export function AttachmentHoverCardContent({ align = "start", className = "", style, ...props }: DivProps & { align?: "start" | "center" | "end" }) { const card = useContext(HoverCardContext); return <div {...props} style={{ ...style, positionAnchor: card ? `--hk-hover-${card.identity.replace(/[^a-z0-9_-]/gi, "")}` : undefined } as CSSProperties} id={card?.identity} hidden={!card?.open} data-align={align} className={`hk-attachment-hover-content ${className}`} />; }
export function AttachmentEmpty({ children = "No attachments", className = "", ...props }: DivProps) { return <div {...props} className={`hk-attachment-empty ${className}`}>{children}</div>; }
