import { createContext, useContext, useState, type ComponentPropsWithRef, type ReactNode } from "react";

type Usage = { inputTokens?: number; outputTokens?: number; reasoningTokens?: number; cachedInputTokens?: number };
type ContextState = { maxTokens: number; usedTokens: number; usage?: Usage; modelId?: string; cost?: number; open: boolean; setOpen: (open: boolean) => void };
const ContextValue = createContext<ContextState | null>(null);
function useContextValue() { const value = useContext(ContextValue); if (!value) throw new Error("Context parts require Context."); return value; }
function formatTokens(value: number) { if (!Number.isFinite(value) || value < 0) return "Unavailable"; if (value >= 1_000_000_000) return `${(value / 1_000_000_000).toFixed(1)}B`; if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`; if (value >= 1_000) return `${(value / 1_000).toFixed(1)}K`; return String(Math.round(value)); }
function percentage(used: number, max: number) { return Number.isFinite(used) && used >= 0 && Number.isFinite(max) && max > 0 ? Math.min(100, Math.round((used / max) * 100)) : undefined; }
function formatCost(cost: number) { return Number.isFinite(cost) && cost >= 0 ? `$${cost.toFixed(4)}` : "Cost unavailable"; }

export type ContextProps = ComponentPropsWithRef<"div"> & { maxTokens: number; usedTokens: number; usage?: Usage; modelId?: string; cost?: number; open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void };
export function Context({ maxTokens, usedTokens, usage, modelId, cost, open, defaultOpen = false, onOpenChange, children, className = "", ...props }: ContextProps) { const [localOpen, setLocalOpen] = useState(defaultOpen); const currentOpen = open ?? localOpen; const setOpen = (next: boolean) => { if (open === undefined) setLocalOpen(next); onOpenChange?.(next); }; return <ContextValue value={{ maxTokens, usedTokens, usage, modelId, cost, open: currentOpen, setOpen }}><div {...props} className={`hk-context ${className}`} data-open={currentOpen || undefined}>{children}</div></ContextValue>; }
export function ContextTrigger({ children, className = "", ...props }: ComponentPropsWithRef<"button">) { const context = useContextValue(); const percent = percentage(context.usedTokens, context.maxTokens); const label = percent === undefined ? "Context usage unavailable" : `${percent}% context used`; return <button {...props} type="button" aria-expanded={context.open} aria-label={props["aria-label"] ?? label} className={`hk-context-trigger ${className}`} onClick={event => { props.onClick?.(event); if (!event.defaultPrevented) context.setOpen(!context.open); }}><span className="hk-context-ring" style={{ "--hk-context-progress": percent ?? 0 } as React.CSSProperties} aria-hidden="true" /><span className="hk-context-caption">Context used</span><span>{children ?? (percent === undefined ? "—" : `${percent}%`)}</span></button>; }
export function ContextContent({ className = "", ...props }: ComponentPropsWithRef<"div">) { const context = useContextValue(); return <div {...props} hidden={!context.open} className={`hk-context-content ${className}`} />; }
export function ContextContentHeader({ children, className = "", ...props }: ComponentPropsWithRef<"div">) { const context = useContextValue(); const percent = percentage(context.usedTokens, context.maxTokens); return <div {...props} className={`hk-context-header ${className}`}><div>{children ?? <><strong>{percent === undefined ? "Context usage unavailable" : `${percent}% used`}</strong><span>{formatTokens(context.usedTokens)} / {formatTokens(context.maxTokens)} tokens</span></>}</div><div className="hk-context-bar"><span style={{ width: `${percent ?? 0}%` }} /></div></div>; }
export function ContextContentBody({ children, className = "", ...props }: ComponentPropsWithRef<"div">) { return <div {...props} className={`hk-context-body ${className}`}>{children}</div>; }
export function ContextContentFooter({ children, className = "", ...props }: ComponentPropsWithRef<"div">) { const context = useContextValue(); return <div {...props} className={`hk-context-footer ${className}`}>{children ?? <>{context.modelId && <span>{context.modelId}</span>}{context.cost !== undefined && <strong>{formatCost(context.cost)}</strong>}</>}</div>; }
type UsageProps = ComponentPropsWithRef<"div"> & { children?: ReactNode; label?: string; value?: number; cost?: number };
function UsageRow({ label, value, cost, children, className = "", ...props }: UsageProps) { return <div {...props} className={`hk-context-usage ${className}`}><span>{label}</span>{children ?? <span>{formatTokens(value ?? NaN)}{cost !== undefined && ` · ${formatCost(cost)}`}</span>}</div>; }
export function ContextInputUsage(props: UsageProps) { const context = useContextValue(); return <UsageRow {...props} label={props.label ?? "Input"} value={props.value ?? context.usage?.inputTokens} />; }
export function ContextOutputUsage(props: UsageProps) { const context = useContextValue(); return <UsageRow {...props} label={props.label ?? "Output"} value={props.value ?? context.usage?.outputTokens} />; }
export function ContextReasoningUsage(props: UsageProps) { const context = useContextValue(); return <UsageRow {...props} label={props.label ?? "Reasoning"} value={props.value ?? context.usage?.reasoningTokens} />; }
export function ContextCacheUsage(props: UsageProps) { const context = useContextValue(); return <UsageRow {...props} label={props.label ?? "Cached"} value={props.value ?? context.usage?.cachedInputTokens} />; }
export { formatTokens };
