import type { ComponentPropsWithRef, ReactNode } from "react";

export type SchemaParameter = { name: string; type: string; required?: boolean; description?: string; location?: "path" | "query" | "header" };
export type SchemaProperty = { name: string; type: string; required?: boolean; description?: string; properties?: readonly SchemaProperty[]; items?: SchemaProperty };
export type SchemaMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
export type SchemaDisplayProps = ComponentPropsWithRef<"section"> & { method: SchemaMethod; path: string; description?: string; parameters?: readonly SchemaParameter[]; requestBody?: readonly SchemaProperty[]; responseBody?: readonly SchemaProperty[] };

export function SchemaDisplay({ method, path, description, parameters, requestBody, responseBody, children, className = "", ...props }: SchemaDisplayProps) {
  return <section {...props} className={`hk-schema-display ${className}`}><SchemaDisplayHeader><SchemaDisplayMethod method={method} /><SchemaDisplayPath path={path} /></SchemaDisplayHeader>{description && <SchemaDisplayDescription>{description}</SchemaDisplayDescription>}<SchemaDisplayContent>{children ?? <>{parameters?.length ? <SchemaDisplayParameters parameters={parameters} /> : null}{requestBody?.length ? <SchemaDisplayRequest><SchemaDisplayPropertyList properties={requestBody} /></SchemaDisplayRequest> : null}{responseBody?.length ? <SchemaDisplayResponse><SchemaDisplayPropertyList properties={responseBody} /></SchemaDisplayResponse> : null}</>}</SchemaDisplayContent></section>;
}
export function SchemaDisplayHeader({ className = "", ...props }: ComponentPropsWithRef<"header">) { return <header {...props} className={`hk-schema-header ${className}`} />; }
export function SchemaDisplayMethod({ method, className = "", ...props }: ComponentPropsWithRef<"span"> & { method: SchemaMethod }) { return <span {...props} className={`hk-schema-method hk-schema-method--${method.toLowerCase()} ${className}`}>{method}</span>; }
export function SchemaDisplayPath({ path, className = "", ...props }: ComponentPropsWithRef<"code"> & { path: string }) { return <code {...props} aria-label={props["aria-label"] ?? path} className={`hk-schema-path ${className}`}>{path.split(/([{}])/).map((part, index) => part === "{" || part === "}" ? <span key={index} className="hk-schema-path-marker">{part}</span> : part)}</code>; }
export function SchemaDisplayDescription({ className = "", ...props }: ComponentPropsWithRef<"p">) { return <p {...props} className={`hk-schema-description ${className}`} />; }
export function SchemaDisplayContent({ className = "", ...props }: ComponentPropsWithRef<"div">) { return <div {...props} className={`hk-schema-content ${className}`} />; }
export function SchemaDisplayParameters({ parameters = [], children, className = "", ...props }: ComponentPropsWithRef<"details"> & { parameters?: readonly SchemaParameter[] }) { return <details {...props} className={`hk-schema-section ${className}`}><summary>Parameters <span>{parameters.length}</span></summary>{children ?? <div className="hk-schema-parameter-list">{parameters.map(parameter => <SchemaDisplayParameter key={`${parameter.location ?? "query"}:${parameter.name}`} parameter={parameter} />)}</div>}</details>; }
export function SchemaDisplayParameter({ parameter, className = "", ...props }: ComponentPropsWithRef<"div"> & { parameter: SchemaParameter }) { return <div {...props} className={`hk-schema-parameter ${className}`}><div><code>{parameter.name}</code>{parameter.required && <b aria-label="Required">*</b>}</div><span>{parameter.type} · {parameter.location ?? "query"}</span>{parameter.description && <p>{parameter.description}</p>}</div>; }
export function SchemaDisplayRequest({ children, className = "", ...props }: ComponentPropsWithRef<"details">) { return <details {...props} className={`hk-schema-section ${className}`}><summary>Request body</summary>{children}</details>; }
export function SchemaDisplayResponse({ children, className = "", ...props }: ComponentPropsWithRef<"details">) { return <details {...props} className={`hk-schema-section ${className}`}><summary>Response body</summary>{children}</details>; }
export function SchemaDisplayProperty({ schemaProperty, className = "", ...props }: ComponentPropsWithRef<"div"> & { schemaProperty: SchemaProperty }) { const nested = schemaProperty.properties?.length || schemaProperty.items; return <div {...props} className={`hk-schema-property ${className}`}><div className="hk-schema-property-row"><code>{schemaProperty.name}</code>{schemaProperty.required && <b aria-label="Required">*</b>}<span>{schemaProperty.type}</span></div>{schemaProperty.description && <p>{schemaProperty.description}</p>}{nested && <div className="hk-schema-property-nested">{schemaProperty.properties?.map(child => <SchemaDisplayProperty key={child.name} schemaProperty={child} />)}{schemaProperty.items && <SchemaDisplayProperty schemaProperty={schemaProperty.items} />}</div>}</div>; }
export function SchemaDisplayPropertyList({ properties, className = "", ...props }: ComponentPropsWithRef<"div"> & { properties: readonly SchemaProperty[] }) { return <div {...props} className={`hk-schema-property-list ${className}`}>{properties.map(property => <SchemaDisplayProperty key={property.name} schemaProperty={property} />)}</div>; }
export function SchemaDisplayExample({ children, className = "", ...props }: ComponentPropsWithRef<"pre"> & { children?: ReactNode }) { return <pre {...props} className={`hk-schema-example ${className}`}>{children}</pre>; }
