// Lane-local repair pass; preserves refined frames and every navigation target.
H.iosStatusBar=function(parent,app){var s=H.frame({name:'status-bar',parent:parent,dir:'row',pad:{top:14,right:28,bottom:0,left:28},w:390,h:54,gap:6});H.text({parent:s,text:'9:41',size:15,weight:7,color:H.sw(app,'ink')});var sp=H.frame({parent:s,name:'spacer',h:1});sp.horizontalSizing=sketch.FlexSizing.Fill;H.icon({parent:s,name:'cellular-signal',d:'<path d="M3 19v-3m5 3v-7m5 7V8m5 11V4"/>',size:18,color:H.hex(app,'ink')});H.icon({parent:s,name:'wifi',d:'<path d="M2 8a16 16 0 0 1 20 0M5 12a11 11 0 0 1 14 0m-11 4a6 6 0 0 1 8 0"/><circle cx="12" cy="20" r="1"/>',size:16,color:H.hex(app,'ink')});H.icon({parent:s,name:'battery',d:'<rect x="1" y="6" width="19" height="12" rx="3"/><path d="M23 10v4M5 10h11v4H5z"/>',size:24,color:H.hex(app,'ink')});H.order(s);return s;};
H.iosButtonStyle=function(f,app,danger){f.style.fills=[{color:H.sw(app,danger?'hover':'ink'),enabled:true}];(f.layers||[]).filter(l=>l.type==='Text').forEach(t=>t.style.textColor=H.sw(app,danger?'negative':'inverse'));};
H.fixIOS=function(s,APP,ID){
function all(l){var a=[l];(l.layers||[]).forEach(c=>a=a.concat(all(c)));return a;}
function texts(t){return all(s).filter(l=>l.type==='Text'&&l.text===t);}
function change(a,b){texts(a).forEach(l=>l.text=b);}
function disclosure(r){if(!r||!r.stackLayout)return;var icons=r.layers.filter(l=>l.name==='disclosure');if(icons.length)return;var i=H.icon({parent:r,name:'disclosure',d:H.paths.chevronRight,size:16,color:H.hex(APP,'tertiary')});i.index=0;r.stackLayout.apply();}
var x=s.frame.x,y=s.frame.y;var top=s.layers.find(l=>l.name==='top');if(top){var old=top.layers.find(l=>l.name==='status-bar');var idx=old.index;old.remove();H.iosStatusBar(top,APP).index=idx;H.relayout(top);}
all(s).filter(l=>l.type==='Text').forEach(t=>{var p=t.parent;if(!p||!p.style||!p.style.fills.length)return;var fill=String(p.style.fills[0].color).slice(0,7).toLowerCase();if((fill===H.hex(APP,'accent').toLowerCase()||fill===H.hex(APP,'negative').toLowerCase())&&p.name.indexOf('link:')===0)H.iosButtonStyle(p,APP,fill===H.hex(APP,'negative').toLowerCase());});
// Local SearchField replacement removes blank accessory and duplicate query override.
all(s).filter(l=>l.type==='SymbolInstance'&&l.symbolId&&l.master&&l.master.name.indexOf('SearchField/')===0).forEach(l=>{var p=l.parent,idx=l.index,w=l.frame.width;l.remove();var r=H.frame({parent:p,name:'link:search',dir:'row',gap:10,pad:12,w:w,h:44,radius:12,fill:H.sw(APP,'surface'),border:H.sw(APP,'line')});H.icon({parent:r,d:H.paths.search,size:18,color:H.hex(APP,'secondary')});var t=H.text({parent:r,text:ID==='search'?'billing':'Search',size:15,color:H.sw(APP,ID==='search'?'ink':'tertiary')});t.horizontalSizing=sketch.FlexSizing.Fill;if(ID==='search'){var c=H.frame({parent:r,name:'link:search',w:24,h:24,justify:sketch.StackLayout.JustifyContent.Center});H.icon({parent:c,d:H.paths.x,size:16,color:H.hex(APP,'secondary')});H.order(c);}H.order(r);r.index=idx;});
all(s).filter(l=>l.type==='Text'&&l.text.indexOf('Running only')===0).forEach(l=>{l.text="Running only the billing webhook tests.\nI'll ask before executing anything.";l.frame.width=342;l.fixedWidth=true;});
change('Awaiting permission to run the test command.','Review approval ›');
change('Always allow','Always allow npm test in Personal');texts('Always allow npm test in Personal').forEach(l=>{l.style.fontSize=14;});
change('You’re up to date','End of recent activity');change('Attempt 1 · Running','Attempt 1 · Waiting for approval');change('IN PROGRESS','NEEDS YOUR INPUT');change('Respond','Review approval');
if(ID==='activity'||ID.indexOf('conversation')===0)change('● RUNNING','WAITING FOR APPROVAL');
if(ID.indexOf('project')===0&&ID.indexOf('projects')!==0)texts('Personal').filter(l=>l.style.fontSize>=24).forEach(l=>l.remove());
change('Every 1d · No project · Scheduled','Every day · No project · Scheduled');
['Language','Text size','Voice'].forEach(t=>texts(t).forEach(l=>{if(l.parent.name==='copy'){l.frame.width=155;disclosure(l.parent.parent);}}));
texts('Paused').forEach(l=>{var r=l.parent;var c=r.layers.find(v=>v.name==='copy');if(c)c.layers.filter(v=>v.type==='Text').forEach(v=>v.frame.width=180);disclosure(r);});
['Sign out','Copy link','Save to Files','Delete account','Export data'].forEach(t=>texts(t).forEach(l=>{if(l.parent.name==='copy'){var r=l.parent.parent;r.layers.filter(v=>v.name==='icon'&&v.frame.width===16).forEach(v=>v.remove());}}));
if(ID==='customize'){texts('✓').forEach(l=>l.remove());['General','Research'].forEach(t=>texts(t).forEach(l=>{var r=l.parent.parent;r.layers.filter(v=>v.name==='icon'&&v.frame.width===16).forEach(v=>v.remove());H.icon({parent:r,name:'profile-selection',d:t==='General'?H.paths.circleCheck:H.paths.circle,size:20,color:H.hex(APP,t==='General'?'accent':'tertiary')}).index=0;}));}
change('CONVERSATIONS',ID==='settings-general'?'DEVICE PREFERENCES':'CONVERSATIONS');
change('Remote session revocation requires the account service.','To sign out another device, select it and review its session.');
if(ID==='settings-devices'){['This iPhone','MacBook Pro'].forEach(t=>texts(t).forEach(l=>{var r=l.parent.parent;var i=r.layers.find(v=>v.name==='icon'&&v.frame.width===20);if(i){var idx=i.index;i.remove();H.icon({parent:r,name:'device-icon',size:20,color:H.hex(APP,'accent'),d:t==='This iPhone'?'<rect x="6" y="2" width="12" height="20" rx="3"/><path d="M10 18h4"/>':'<rect x="4" y="3" width="16" height="13" rx="2"/><path d="m4 16-3 4h22l-3-4"/>'}).index=idx;}}));}
if(ID==='settings-privacy'){texts('Share diagnostic data').forEach(l=>{var r=l.parent;H.icon({parent:r,name:'diagnostics-icon',d:H.paths.shield,size:20,color:H.hex(APP,'accent')}).index=r.layers.length-1;r.stackLayout.gap=12;});}
change('iOS prototype','1.0.0 (1)');
texts('Available').forEach(l=>{l.text='32k / 200k';var c=l.parent.layers.find(v=>v.name==='copy');if(c)c.layers.filter(v=>v.type==='Text').forEach(v=>{if(v.text==='Usage this month')v.text='Tokens this month';if(v.text==='Account-wide usage')v.text='Requests: 41 / 500';v.frame.width=170;});});
texts('Only real deliverables land here — results without output stay with their task').forEach(l=>l.remove());
if(ID==='artifacts--code'){all(s).filter(l=>l.type==='Text'&&l.text.indexOf('export async')===0).forEach(l=>{l.text='<article>\n  <small>MIGRATION NOTES</small>\n  <h1>A safer billing pipeline</h1>\n  <p>One ledger client.\n  Idempotent retries.\n  Clear ownership.</p>\n  <p>✓ Webhook handler migrated</p>\n  <ol>\n    <li>Validate event signature</li>\n    <li>Apply ledger transaction</li>\n    <li>Acknowledge delivery</li>\n  </ol>\n</article>';l.style.fontSize=11;});}
if(ID==='settings-billing--plan'){change('Monthly','Monthly · US$300');change('Annual','Annual · US$3,000');texts('Monthly · US$300').concat(texts('Annual · US$3,000')).forEach(l=>l.style.fontSize=12);change('Review pricing and payment details at checkout.','US$300 billed monthly. Renews monthly until canceled. Annual: US$3,000 per year.');texts('US$300 billed monthly. Renews monthly until canceled. Annual: US$3,000 per year.').forEach(l=>{l.fixedWidth=true;l.frame.width=342;});}
if(ID==='routines--new'){texts('Summarize my priorities for today').forEach(l=>{l.text='Summarize my priorities for today.\nHighlight deadlines and next steps.';var r=l.parent;r.frame.height=88;r.verticalSizing=sketch.FlexSizing.Fixed;l.frame.width=326;l.fixedWidth=true;});texts('Every day at 9:00 AM').forEach(l=>{l.frame.width=290;disclosure(l.parent);});}
// ActionSheet cancellation is its own surface with an 8pt separation.
if(ID==='conversation--menu'){var p=s.layers.find(l=>l.name.indexOf('ActionSheet/')===0);if(p){var c=p.layers.find(l=>all(l).some(t=>t.text==='Cancel'));if(c){c.parent=s;c.frame.x=24;c.frame.y=752;c.style.fills=[{color:H.sw(APP,'surface'),enabled:true}];H.relayout(p);p.frame.y=744-p.frame.height;}}}
H.relayout(s);
s.layers.filter(l=>l.name==='Sheet').forEach(p=>{p.frame.y=810-p.frame.height;});
if(ID==='conversation--approval'){var p=s.layers.find(l=>l.name.indexOf('Sheet/')===0);if(p){p.frame.height=430;p.frame.y=380;}}
// Pinned native home indicator above scrim, never a layout child.
s.stackLayout=null;s.layers.filter(l=>l.name==='gesture-indicator'||l.name==='home-indicator-native').forEach(l=>l.remove());H.rect({parent:s,name:'home-indicator-native',x:128,y:824,w:134,h:5,radius:3,fill:H.sw(APP,'ink')});
all(s).filter(l=>l.name.indexOf('link:')===0).forEach(l=>l.name=l.name.replace(/ \d+$/,''));s.frame.x=x;s.frame.y=y;s.frame.width=390;s.frame.height=844;
H.out({id:ID,app:APP,frame:s.id,x:x,y:y,w:s.frame.width,h:s.frame.height,links:Array.from(new Set(all(s).filter(l=>l.name.indexOf('link:')===0).map(l=>l.name)))});
};
