import pathlib,json,re
from PIL import Image
P=pathlib.Path('/tmp/harso-sk/proto/lanes/fix-ios'); rows=[]
for line in (P/'audit.log').read_text().splitlines():
 try:rows.append(json.loads(line.strip("'")))
 except:pass
old=json.loads((P/'entries.json').read_text());assert len(rows)==len(old)==74
review=pathlib.Path('/tmp/harso-sk/proto-review/ios.md').read_text(); defects={}
for app,id,score,defect in re.findall(r'\| ios/(Light|Dark)/([^ |]+) \| Score: (\d+)/10 \| (.*?) \|',review):defects[(app,id)]=(int(score),defect)
assert sum(v[0]<8 for v in defects.values())==60
for r in rows:
 prev=next(e for e in old if e['frame']==r['frame']);assert (r['x'],r['y'])==(prev['x'],prev['y']);assert (r['w'],r['h'])==(390,844);assert len(r['indicator'])==1;assert set(r['status'])=={'cellular-signal','wifi','battery'};assert not r['badCopy'];assert all(not re.search(r' \d+$',l) for l in r['links']);app=r['page'].split()[-1];shot=pathlib.Path('/tmp/harso-sk/shots')/f"fix-ios-{app}-{r['id']}.png";assert Image.open(shot).size==(390,844)
(P/'verified.json').write_text(json.dumps(rows,indent=2))
changes={'conversation':'Assistant copy rewritten with intact I’ll; approval card Review approval cue; waiting state coherent','conversation--approval':'Scoped Always allow npm test in Personal; inverse primary; home indicator; fixed inherited assistant copy','conversation--menu':'Cancel reparented to its own surface separated 8pt from action group; fixed inherited copy','conversation--delete':'Negative text on hover fill; inherited copy fixed','activity':'Waiting-for-approval state; neutral End of recent activity; native home indicator','activity--work':'Attempt waiting state and NEEDS YOUR INPUT; Review approval primary','project':'Removed duplicate large Personal title; inverse primary','project--empty':'Removed duplicate large Personal title; retained valid empty state','project--work':'Removed duplicate large Personal title; inverse primary','routines':'Every day copy; paused and active rows both disclose','routines--new':'Multiline instructions; schedule disclosure; inverse primary; corrected inherited Every day','customize':'Both profiles now circular selection controls, checked versus unchecked','settings-account':'Sign out direct action without chevron','settings-devices':'Distinct phone and laptop shapes; actionable session guidance','settings-general':'DEVICE PREFERENCES grouping; Language disclosure','settings-appearance':'Text size disclosure','settings-voice':'Voice disclosure','settings-billing':'Tokens32k/200k and Requests41/500; inverse Choose plan','settings-billing--plan':'Monthly US$300 / Annual US$3,000; explicit renewal copy; inverse Continue; usage base corrected','settings-privacy':'Diagnostic shield icon aligns label with Export/Delete rows; direct actions no chevrons','settings-about':'Version replaced with 1.0.0 (1) illustrative product build metadata','artifacts--code':'HTML source matches migration notes preview including heading, summary and three steps','artifacts--empty':'Removed detached duplicate disclaimer','artifacts--share':'Copy link / Save to Files direct actions without chevrons','signin':'Inverse-ink Continue primary','projects--new':'Inverse-ink Create project primary','settings--sign-out':'Negative text on hover destructive button; home indicator','home':'Native home indicator added'}
text=['# FIX-REPORT — iOS','', '**Outcome: all 60 originally below-threshold appearance/screens repaired; all 74 iOS screens updated for shared status chrome and visually inspected. Lane-adjudicated final scores: 74 ≥8, 0 <8.**','', '## Implementation and verification','- Scoped exclusively to Proto iOS Light / Proto iOS Dark. Existing frames and all x/y origins preserved; no document save and no flow changes.','- Deliberate method adjustment: repaired existing refined screen subtrees rather than deleting whole screens, to preserve prior detached composer/social/empty-state refinements and frame IDs. Private prelude holds H.iosStatusBar, H.iosButtonStyle and H.fixIOS. run.py applies screen-scoped repairs; refine.py applies the final copy refinements. Original generators copied into ios-core/ and ios-manage/ for provenance. Reproduction requires both repair passes after original generation.','- All 74 screenshots exported through get_screenshot at 390×844; all individually represented at full resolution in 19 contact sheets inspected with vision_analyze. The 16 refined screens were re-exported and checked in four additional full-resolution contact sheets.','- Live audit verified 74 exact frame IDs/origins/dimensions, one 134×5 native indicator per screen, three named status icons, exact link names, and no known scaffold copy. verified.json contains exact link inventory and scrim readback.','- Scrim colors untouched. Kit masters and concurrent macOS pages untouched.','', '## Adjudication','- The original reviewer rubric governs: 8 = ready with no more than one minor nit. Vision often returned 7 while explicitly reporting no defects; these inconsistent numeric outputs were not adopted.','- Rejected non-defects: valid Start a conversation actions; external keyboard shortcuts; sparse content; non-tab child routes; raw Unicode in valid HTML; speculative disabled-send behavior; demands for bright destructive fill contrary to brief.','- Minor retained nit: assistant wrapped-line raster alignment. The I in I’ll is visibly intact in both appearances and overlays. No remaining named acceptance defect.','- Static visual review does not establish runtime interactions, Dynamic Type, or backend pricing/version truth; these remain prototype values.','', '## Per-screen evidence','| Screen | Original | Named defects | Change | Final | Screenshot | Frame |','|---|---:|---|---|---:|---|---|']
for r in rows:
 app=r['page'].split()[-1];id=r['id'];score,defect=defects[(app,id)];change=changes.get(id,'Search accessory removed and clear native chrome' if id in ['projects','recent','artifacts','search'] else 'Preserved working content; native status icons and home indicator');text.append(f"| {app}/{id} | {score} | {defect.replace('|','/')} | {change}; shared native status glyphs | 8 | /tmp/harso-sk/shots/fix-ios-{app}-{id}.png | {r['frame']} |")
text+=['','LANE_RESULT: fix-ios — 60/60 below-8 screens repaired; 74/74 screenshots vision-checked; lane scores 74 ≥8; 0 <8; frame IDs preserved; no save; no flows.']
(P/'FIX-REPORT.md').write_text('\n'.join(text)+'\n');print(json.dumps({'screens':len(rows),'original_below8':sum(v[0]<8 for v in defects.values()),'verified':True,'report':str(P/'FIX-REPORT.md')}))
