from pathlib import Path
import re
P=Path('/tmp/harso-sk/lanes/fix-display-nav')
D=Path('/tmp/harso-sk/lanes/display'); N=Path('/tmp/harso-sk/lanes/navigation')
fams=['Avatar','Badge','Chip','Announcement','Tooltip','Carousel','Pagination','Breadcrumb','Tabs','SegmentedControl','Table','Typography','Menu','Popover','Sidebar','SettingsModal','ActionSheet','NotificationCenter']
B={}
for f in fams:
 src=(D if (D/(f+'.js')).exists() else N)/(f+'.js')
 t=src.read_text(); B[f]=t
# retain exact live grid anchors, remove only scoped family
for f,t in B.items():
 page='Display' if f in fams[:12] else 'Navigation'
 start=t.index('var APPS=') if page=='Display' else t.index('var page=')
 end=t.index('function tx(')
 init="""var APPS=['Light/Clean','Light/Cozy','Dark/Clean','Dark/Cozy'], apps=APPS;
var page=H.page('PAGE');
var prior=page.layers.find(l=>l.name===FAMILY+' — '+APP);if(!prior)throw Error('Missing original '+FAMILY+' '+APP);
var oldX=prior.frame.x,oldY=prior.frame.y;H.dropSheet('PAGE',FAMILY+' — '+APP);var existing=null;
var sh=H.sheet({name:FAMILY+' — '+APP,parent:page,x:oldX,y:oldY,fill:H.sw(APP,'canvas-deep')});
""".replace('PAGE',page)
 t=t[:start]+init+t[end:]
 # local Start fix only; do not mutate shared prelude
 t=t.replace("var APP = 'Dark/Cozy';", "var APP = 'Light/Clean';")
 t="var originalFrame=H.frame;H.frame=function(o){var f=originalFrame(o);if(o.align!==undefined)f.stackLayout.alignItems=o.align;return f;};\n"+t
 t=t.replace('H.out({','sh.frame.x=oldX;sh.frame.y=oldY;H.out({')
 B[f]=t
# body replacements keep common funcs

def body(f,s):
 t=B[f]; marker="tx(sh,FAMILY+' — '+APP,20,'ink',null,6);";i=t.index(marker)+len(marker)
 B[f]=t[:i]+'\n'+s+'\nfinish();\n'
body('Avatar',r'''function av(p,n,s,image,status){var a=sy(p,n,{w:s+4,h:s+4});a.stackLayout=null;a.clipsContent=false;H.rect({parent:a,x:2,y:2,w:s,h:s,radius:999,fill:H.sw(APP,'surface'),border:H.sw(APP,'line')});var t=image?ic(a,'user',s===24?14:20):tx(a,s===24?'JL':s===32?'S':'AM',s===24?12:14,'ink',null,6);t.frame.x=2+(s-t.frame.width)/2;t.frame.y=2+(s-t.frame.height)/2;if(status){H.rect({parent:a,name:'online',x:s-4,y:s-4,w:8,h:8,oval:true,fill:H.sw(APP,'positive-mark'),border:H.sw(APP,'canvas'),bw:2});}return a;}
[24,32,40].forEach(s=>{var r=row(s+'px · initials, placeholder, online');av(r,s+'/initials',s,false,false);av(r,s+'/image-placeholder',s,true,false);av(r,s+'/status',s,false,true);});
var r=row('Avatar group');var g=sy(r,'group/default',{gap:0});['AM','S','JL','+2'].forEach(t=>{var a=fr(g,'avatar',{w:32,h:32,radius:999,fill:H.sw(APP,'surface'),border:H.sw(APP,'line'),justify:sketch.StackLayout.JustifyContent.Center});tx(a,t,12,'ink',null,6);});''')
B['Badge']=B['Badge'].replace("['neutral','secondary','Draft'],['positive'","['neutral','secondary','Draft'],['accent','accent','Working'],['positive'").replace(",['accent','accent','Working']];", "];")
body('Chip',r'''var states=[['neutral','secondary','Draft'],['accent','accent','Working'],['positive','positive','Ready'],['attention','attention','Needs input'],['negative','negative','Couldn’t finish']];
['Bold','Subtle','Caption'].forEach(v=>{var r=row(v);states.forEach(a=>{var role=a[1],bold=v==='Bold';var fill=bold?H.sw(APP,role):v==='Subtle'?H.alpha(H.hex(APP,role),0.10):null;var textRole=bold?'canvas':role;var b=sy(r,v.toLowerCase()+'/'+a[0],{gap:6,pad:{top:4,right:8,bottom:4,left:8},radius:999,fill:fill});dot(b,6,textRole);tx(b,a[2],12,textRole,null,6);});});
var r=row('Dismissible · leading icon');['dismissible','leading-icon'].forEach(v=>{var b=sy(r,v+'/default',{gap:6,pad:{top:4,right:8,bottom:4,left:8},radius:999,fill:H.sw(APP,'hover')});if(v==='leading-icon')ic(b,'sparkles',14);tx(b,'Working',12,'ink',null,6);if(v==='dismissible')ic(b,'x',14);});''')
body('Announcement',r'''[['info','accent','sparkles'],['attention','attention','alert'],['negative','negative','circleX']].forEach(a=>{var r=row(a[0]);var b=sy(r,a[0]+'/default',{gap:12,pad:16,radius:16,fill:H.sw(APP,'surface'),border:H.sw(APP,'line'),align:sketch.StackLayout.AlignItems.Start});ic(b,a[2],20,a[1]);var c=col(b,'content',{gap:8});tx(c,'A little more room to think.',14,'ink',450,6);tx(c,'Your work, with fewer distractions.',13,'secondary',450);pill(c,'Take a look →',false);ic(b,'x',16);});
var r=row('Title only');var b=sy(r,'info/title-only',{gap:12,pad:16,radius:16,fill:H.sw(APP,'surface'),border:H.sw(APP,'line'),w:530});ic(b,'info',20,'accent');tx(b,'A title is sometimes enough.',14,'ink',null,6);''')
body('Tooltip',r'''['top','bottom'].forEach(v=>{var r=row(v+' arrow');var b=sy(r,v+'/default',{w:190,h:40});b.stackLayout=null;var body=fr(b,'hint',{pad:{top:8,right:12,bottom:8,left:12},radius:999,fill:H.sw(APP,'ink')});tx(body,'Copy a link to this sample',13,'inverse');H.relayout(body);var w=body.frame.width,h=body.frame.height;b.frame.width=w;b.frame.height=h+6;body.frame.x=0;body.frame.y=v==='top'?6:0;
var d=v==='top'?'M0 6 L6 0 L12 6 Z':'M0 0 L6 6 L12 0 Z';var svg='<svg xmlns="http://www.w3.org/2000/svg" width="12" height="6"><path d="'+d+'" fill="'+H.hex(APP,'ink')+'"/></svg>';var tip=sketch.createLayerFromData(svg,'svg');tip.name='attached half diamond';tip.parent=b;tip.frame.x=(w-12)/2;tip.frame.y=v==='top'?0:h;});''')
body('Carousel',r'''var r=row('Four slides · first active · next slide peek');var b=sy(r,'peek/four',{dir:'col',gap:20,w:660,align:sketch.StackLayout.AlignItems.Start});var viewport=fr(b,'slide viewport',{w:660,h:236,gap:16,clip:true});
[['01 / Research','A clearer direction'],['02 / Research','Make room for what matters']].forEach((a,i)=>{var c=col(viewport,'slide',{w:560,h:236,pad:24,gap:12,radius:12,fill:H.sw(APP,'surface'),border:H.sw(APP,'line')});tx(c,a[0],12,'tertiary');tx(c,a[1],20,'ink',512,6);tx(c,'A quiet place for the things worth keeping.',14,'secondary',512);if(i===0){tx(c,'Note',13,'secondary');var input=fr(c,'input',{w:512,h:36,pad:10,radius:8,fill:H.sw(APP,'canvas'),border:H.sw(APP,'control-line')});tx(input,'Draft insight',14);}else tx(c,'Explore result →',14,'accent');});
var nav=fr(b,'page control',{gap:16,w:660,justify:sketch.StackLayout.JustifyContent.Center});ic(nav,'<path d="m15 18-6-6 6-6"/>');var dots=fr(nav,'dots',{gap:8});[0,1,2,3].forEach(i=>H.rect({parent:dots,w:i===0?20:6,h:6,radius:3,fill:H.sw(APP,i===0?'ink':'faint')}));ic(nav,'chevronRight');''')
body('Pagination',r'''[['tail','2',['‹','1','2','3','…','12','›']],['double-sided','12',['‹','1','…','11','12','13','…','24','›']],['compact','1',['‹','1','›']]].forEach(a=>{var r=row(a[0]);var b=sy(r,a[0]+'/default',{gap:6});a[2].forEach(t=>{var p=fr(b,'page',{w:32,h:32,radius:8,fill:t==='…'||(a[0]==='compact'&&t!=='1')?null:H.sw(APP,t===a[1]?'ink':'hover'),justify:sketch.StackLayout.JustifyContent.Center});tx(p,t,14,t===a[1]?'inverse':'ink',null,6);});});''')
body('Breadcrumb',r'''var r=row('Compound nodes');var b=sy(r,'default',{gap:8});var first=fr(b,'workspace',{gap:6});ic(first,'home');tx(first,'Workspace',14,'secondary');ic(b,'chevronRight',14,'tertiary');var second=fr(b,'project',{gap:6});var av=fr(second,'avatar',{w:24,h:24,radius:999,fill:H.sw(APP,'surface'),border:H.sw(APP,'line'),justify:sketch.StackLayout.JustifyContent.Center});tx(av,'HL',12,'ink',null,6);tx(second,'Harso launch',14,'secondary');ic(b,'chevronRight',14,'tertiary');tx(b,'Launch research',14,'ink',null,6);''')
B['SegmentedControl']=B['SegmentedControl'].replace("['three','four','icons','disabled']","['two','three','four','icons','disabled']").replace("(v==='four'?", "(v==='two'?['Comfortable','Compact']:v==='four'?")
B['Typography']=B['Typography'].replace('Heading · 24','Display · 24').replace('Title · 20','Heading · 20').replace("['Body · 15'","['Section · 16','Everything in its right place',16,'ink',6],['Body · 15'")
# Tabs preserve prior variants, add exact pane
B['Tabs']=B['Tabs'].replace('\nfinish();',r'''
var r=row('Overview pane · History disabled');var b=sy(r,'pane/default',{dir:'col',gap:20,w:560,align:sketch.StackLayout.AlignItems.Start});var bar=fr(b,'tabs',{gap:0});['Overview','Sources','History'].forEach((t,i)=>{var tab=col(bar,'tab',{gap:10});var q=fr(tab,'label row',{h:32,pad:{left:16,right:16,top:0,bottom:0},gap:8});if(i===0)ic(q,'file');tx(q,t,14,i===2?'tertiary':i===0?'ink':'secondary',null,6);if(i===1){var badge=fr(q,'count',{pad:4,radius:999,fill:H.sw(APP,'hover')});tx(badge,'6',12,'secondary');}H.rect({parent:tab,w:140,h:2,fill:H.sw(APP,i===0?'ink':'line')});});var pane=col(b,'panel',{gap:10,w:560});tx(pane,'Start smaller.',16,'ink',null,6);tx(pane,'Make the first experience exceptional.',14,'secondary');tx(pane,'Draft title',13,'secondary');var input=fr(pane,'input',{w:420,h:36,pad:10,radius:8,fill:H.sw(APP,'surface'),border:H.sw(APP,'control-line')});tx(input,'A focused launch',14);
finish();''')
body('Table',r'''var r=row('A small evidence set');var b=sy(r,'basic/default',{dir:'col',gap:0,w:700,align:sketch.StackLayout.AlignItems.Start});[['Source','Disposition'],['Firsthand observations','Keep'],['Unverified assumptions','Revisit']].forEach((a,i)=>{var q=fr(b,'row',{h:44,gap:24,pad:12});tx(q,a[0],13,i===0?'secondary':'ink',400,i===0?6:5);tx(q,a[1],13,i===0?'secondary':'ink',200,i===0?6:5);if(i<2)line(b,700);});
var r=row('Work records · sortable · hover · selected');var b=sy(r,'default',{dir:'col',gap:12,w:780,pad:16,radius:12,fill:H.sw(APP,'surface'),border:H.sw(APP,'line'),align:sketch.StackLayout.AlignItems.Start});tx(b,'Search records',13,'secondary');var search=fr(b,'search',{w:360,h:36,pad:10,radius:8,fill:H.sw(APP,'canvas'),border:H.sw(APP,'control-line')});ic(search,'search');tx(search,'Find work records...',13,'tertiary');var table=col(b,'table',{gap:0});[['Work','Sources','Status'],['Audience interviews','3','Review'],['Launch positioning','10','Ready'],['Product comparisons','0','Ready'],['A focused first week','7','Review']].forEach((a,i)=>{var q=fr(table,'row',{gap:16,pad:{top:0,right:12,bottom:0,left:12},h:44,w:748,radius:6,fill:i===2?H.sw(APP,'hover'):i===3?H.sw(APP,'accent-soft'):null});var check=fr(q,'checkbox',{w:16,h:16,radius:3,border:H.sw(APP,'control-line'),fill:i===3?H.sw(APP,'ink'):null,justify:sketch.StackLayout.JustifyContent.Center});if(i===3)ic(check,'check',12,'inverse');var title=fr(q,'work',{w:292,gap:8});tx(title,a[0],13,i===0?'secondary':'ink',null,i===0?6:5);if(i===0)ic(title,'chevronsUpDown',14);var sources=fr(q,'sources',{w:108,gap:8});tx(sources,a[1],13,i===0?'secondary':'ink');if(i===0)ic(sources,'chevronsUpDown',14);var status=fr(q,'status',{w:150,gap:6});if(i)dot(status,6,a[2]==='Ready'?'positive-mark':'attention-mark');tx(status,a[2],13,i===0?'secondary':a[2]==='Ready'?'positive':'attention');if(i===0)tx(q,'Action',13,'secondary',60,6);else{var action=fr(q,'view',{w:60,h:28,justify:sketch.StackLayout.JustifyContent.Center});ic(action,'eye');}if(i<4)line(table,748);});''')
# navigation scoped fixes
B['Menu']=B['Menu'].replace("menu(wrap,'main menu',false);var sub=card(wrap,'submenu',220,6,12);", "var parentMenu=menu(wrap,'main menu',false);var fly=fr(wrap,'flyout anchor','col',220,undefined,0,0);var trigger=parentMenu.layers.find(l=>l.name==='row'&&sketch.find('Text',l).some(t=>t.text==='Move to project'));spacer(fly,trigger.frame.y);var sub=card(fly,'submenu',220,6,12);").replace('done(sub);done(wrap);','done(sub);done(fly);done(wrap);').replace("undefined,undefined,0,8);wrap.stackLayout", "undefined,undefined,0,4);wrap.stackLayout")
B['ActionSheet']=B['ActionSheet'].replace("var cancel=card(c,'cancel',374,8,16);btn(cancel,'Cancel',false,358);done(cancel);", "var cancel=fr(c,'cancel','row',374,44,8,0,'surface',16);cancel.style.borders=[{color:H.sw(APP,'line'),thickness:1}];cancel.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;tx(cancel,'Cancel',14,'ink',undefined,6);done(cancel);")
B['Sidebar']=B['Sidebar'].replace("var h=fr(c,'workspace'", "var header=fr(c,'header','row',224,32,8,8);tx(header,'Research desk',14,'ink',undefined,6);flex(header);ic(header,'panelLeft');done(header);var h=fr(c,'workspace'").replace("spacer(c,64);", "var notice=card(c,'announcement',224,12,12);var nh=fr(notice,'header','row',200,20,0,8);ic(nh,'info',16,'accent');flex(nh);ic(nh,'x',14);done(nh);tx(notice,'A little more room',14,'ink',200,6);tx(notice,'A sample announcement from the workspace.',13,'secondary',200);done(notice);").replace("'folder','settings'", "'folder','layers'")
B['Sidebar']=B['Sidebar'].replace("'Research desk','folder'", "'Projects','folder'")
B['SettingsModal']=B['SettingsModal'].replace('c.frame.height=520','c.frame.height=590').replace("672,368,0,24", "672,438,0,24").replace("tx(form,'Current plan'", "var banner=fr(form,'plan banner','row',456,76,16,8,'hover',12);ic(banner,'layers',32,'tertiary');done(banner);tx(form,'Current plan'").replace(",['Notifications','When work is ready']", "").replace("tx(form,'Local preview", "var pref=fr(form,'notification preference','row',456,32,0,8);var check=fr(pref,'checked','row',16,16,0,0,'ink',3);ic(check,'check',12,'inverse');done(check);tx(pref,'Notify me when work is ready',13);done(pref);tx(form,'Local preview")
B['NotificationCenter']=B['NotificationCenter'].replace("tx(h,'Notifications',16,'ink',undefined,6);flex(h);", "tx(h,'Notifications',16,'ink',undefined,6);var count=fr(h,'unread count','row',20,20,0,0,'hover',999);count.stackLayout.justifyContent=sketch.StackLayout.JustifyContent.Center;tx(count,'2',12,'secondary',undefined,6);done(count);flex(h);").replace("done(h);[['Today'", "done(h);var filters=fr(c,'filters','row',328,36,4,4,'hover',8);['All','Mentions','System'].forEach((t,i)=>{var f=fr(filters,'filter','row',undefined,28,{left:12,right:12,top:0,bottom:0},0,i===0?'surface':null,6);tx(f,t,13,i===0?'ink':'secondary',undefined,6);done(f);});done(filters);[['Today'")
# popover triangle with surface base mask, border only on outer sides
old="var a=H.rect({parent:root,name:'arrow',w:8,h:8,fill:H.sw(APP,'surface')});a.transform.rotation=45; a.frame.x=pos==='left'?6:pos==='right'?326:166;a.frame.y=pos==='top'?6:pos==='bottom'?body.frame.height+6:70;"
new=r'''var paths={top:'M0 8 L8 0 L16 8',bottom:'M0 0 L8 8 L16 0',left:'M8 0 L0 8 L8 16',right:'M0 0 L8 8 L0 16'};var vertical=pos==='top'||pos==='bottom';var svg='<svg xmlns="http://www.w3.org/2000/svg" width="'+(vertical?16:8)+'" height="'+(vertical?8:16)+'"><path d="'+paths[pos]+' Z" fill="'+H.hex(APP,'surface')+'"/><path d="'+paths[pos]+'" fill="none" stroke="'+H.hex(APP,'line')+'" stroke-width="1"/></svg>';var a=sketch.createLayerFromData(svg,'svg');a.name='merged pointer';a.parent=root;a.frame.x=pos==='left'?2:pos==='right'?330:162;a.frame.y=pos==='top'?2:pos==='bottom'?body.frame.height+10:70;H.rect({parent:root,name:'base border knockout',x:pos==='left'?9:pos==='right'?329:163,y:pos==='top'?9:pos==='bottom'?body.frame.height+9:71,w:vertical?14:2,h:vertical?2:14,fill:H.sw(APP,'surface')});'''
B['Popover']=B['Popover'].replace(old,new)
for f,t in B.items(): (P/(f+'.js')).write_text(t)
(P/'families.json').write_text(__import__('json').dumps(fams))
print('Generated',len(B))
